"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../lib/supabase";
import {cartPrice,readCart,saveCart,type CartItem} from "../../lib/cart";
import {ADDONS,resolveCatalog} from "../../lib/product-catalog";

export default function Cart(){
 const[userId,setUserId]=useState(""),[items,setItems]=useState<CartItem[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const client=getSupabaseBrowserClient();if(!client){setLoading(false);return}const sync=(id?:string)=>{setUserId(id||"");setItems(id?readCart(id):[]);setLoading(false)};void client.auth.getSession().then(({data})=>sync(data.session?.user.id));const{data}=client.auth.onAuthStateChange((_event,session)=>sync(session?.user.id));return()=>data.subscription.unsubscribe()},[]);
 function remove(id:string){try{const next=items.filter(item=>item.id!==id);saveCart(userId,next);setItems(next)}catch{setError("Your cart could not be saved. Please enable browser storage.")}}
 async function checkout(){setBusy(true);setError("");try{const session=(await getSupabaseBrowserClient()?.auth.getSession())?.data.session;if(!session){setUserId("");return}const response=await fetch("/api/cart/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({items}),signal:AbortSignal.timeout(30000)}),data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||"Checkout could not be opened.");location.assign(data.url)}catch(error){setError(error instanceof Error?error.message:"Checkout could not be opened.")}finally{setBusy(false)}}
 return <main className="orderPage cartPage"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><section><div className="eyebrow">Your keepsakes</div><h1>Shopping cart</h1>{loading?<p>Loading your cart…</p>:!userId?<><p>Sign in to save keepsakes and use your cart.</p><a className="button gold" href="/login?return_to=%2Fcart">Sign in →</a></>:items.length?<><div className="cartItems">{items.map(item=>{const catalog=resolveCatalog(item.product,item.tier);return <article key={item.id}><div><h2>{catalog.displayName}</h2>{item.addon!=="none"&&<p>{ADDONS[item.addon as keyof typeof ADDONS].name}</p>}<p>{item.customization?"Your saved design is attached.":catalog.fulfillmentWorkflow==="digital_map"?"Digital access for your account.":"Personalization and proof review follow purchase."}</p><strong>${(cartPrice(item)/100).toFixed(2)}</strong></div><button className="button light" disabled={busy} onClick={()=>remove(item.id)} aria-label={`Remove ${catalog.displayName}`}>Remove</button></article>})}</div><p className="cartTotal">Subtotal <b>${(items.reduce((sum,item)=>sum+cartPrice(item),0)/100).toFixed(2)}</b></p><p>Review the final total in Stripe. Each keepsake will have its own order and next steps in your account.</p><button className="button gold" disabled={busy} onClick={checkout}>{busy?"Opening secure checkout…":"Pay for all items →"}</button></>:<p>Your cart is empty. Choose a keepsake to get started.</p>}{error&&<p className="authError" role="alert">{error}</p>}<div className="buttonRow"><a className="textLink" href="/#keepsakes">Continue shopping →</a>{userId&&<a className="textLink" href="/account">My account</a>}</div></section></main>;
}
