import {deckTiers,orderHref} from "../../lib/product-tiers";
export const metadata={title:"The Memento Deck | Memento House",description:"An interactive wedding guestbook your guests create for you—made during your wedding, discovered afterward, and kept long after."};
const dividers=[["097","005","Remember"],["098","020","Advise"],["099","036","Predict"],["100","053","Adventure"],["101","069","Together"],["102","084","Confess"]];
export default function MementoDeck(){return <main className="productPage">
 <nav className="houseNav"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/#keepsakes">All keepsakes</a><a href="/create/deck" className="button small">Create your deck</a></div><details className="mobileMenu"><summary>Menu</summary><div><a href="/#keepsakes">All keepsakes</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></div></details></nav>
 <section className="productHero"><div><div className="eyebrow">The Memento Deck</div><h1>Your guests don’t just sign it.<br/><em>They create it.</em></h1><p>A personalized collection of memories, predictions, advice, stories, and future messages created by the people who celebrated with you.</p><p className="heroPromise">Made during your wedding. Discovered after it. Kept long after.</p><div className="heroActions"><a href="/create/deck" className="button gold">Create Your Deck →</a><a href="#how" className="button light">See How It Works</a></div></div><figure className="deckHero"><img src="/brand/memento-deck-cover.webp" alt="Personalized Memento Deck cover"/><img src="/brand/memento-deck-card.webp" alt="Memento Deck story card"/></figure></section>
 <section className="deckManifesto"><div className="eyebrow">We create the cards. Your guests create the keepsake.</div><h2>It begins as a personalized deck.<br/>It comes home overflowing with notes from your guests.</h2><p>No need to stop and read cards during your celebration. Guests choose, write, sign, and add each one to the Completed Mementos box. The discovery is waiting for you afterward.</p></section>
 <section id="how" className="productSteps"><div className="eyebrow">The full experience</div><h2>Personalized before. Created during. Discovered after.</h2><div><article><b>01</b><h3>Personalize</h3><p>Choose your deck, colors, names, date, photos, and the available story details that make it yours.</p></article><article><b>02</b><h3>Guests pick + write</h3><p>Guests draw from six categories, answer a thoughtful prompt, sign their name, and place it in the completed collection.</p></article><article><b>03</b><h3>Your First Read</h3><p>After the wedding, sit down together and discover everything your guests wrote.</p></article></div></section>
 <section className="deckCategories"><div className="eyebrow">Six ways to leave a memento</div><h2>A beautiful category system makes it easy to begin.</h2><p>Hover or tap a card to see the kind of prompt guests answer.</p><div className="dividerGallery">{dividers.map(([front,back,label])=><figure className="deckFlip" key={label}><div><img src={`/brand/deck/Robinson_${front}_Divider_Front.png`} alt={`${label} category divider card`}/><img src={`/brand/deck/Robinson_${back}_${label}_Back.png`} alt={`${label} guest prompt card`}/></div></figure>)}</div></section>
 <section className="promptExamples"><div><div className="eyebrow">What guests actually write</div><h2>Prompts turn “sign here” into something worth keeping.</h2><p>Every card gives guests a way in—whether they know the couple’s oldest stories or simply want to give them something joyful for the future.</p></div><div className="promptFan"><figure><img src="/brand/deck/Robinson_052_Adventure_Back.png" alt="Adventure prompt asking guests to send the couple somewhere"/></figure><figure><img src="/brand/deck/Robinson_068_Together_Back.png" alt="Together prompt asking guests for a tradition to start"/></figure></div></section>
 <section className="transformation"><div className="eyebrow">The transformation</div><h2>Unanswered at the beginning.<br/><em>Irreplaceable by the end.</em></h2><div><article><span>BEFORE</span><h3>Your personalized deck</h3><p>Beautiful cards, carefully chosen prompts, and space waiting for the people you love.</p></article><b>→</b><article><span>AFTER</span><h3>Your one-of-one guestbook</h3><p>Memories, advice, predictions, jokes, signatures, and adventures, written <strong>by</strong> your guests.</p></article></div></section>
 <section className="firstRead"><div><div className="eyebrow">Your First Read</div><h2>One last part of your wedding is waiting at home.</h2><p>Read memories. Laugh at confessions. Compare predictions. Save advice. Choose adventures. Discover the messages you completely missed while the day was happening.</p><blockquote>“Our guests fill this out during the wedding, then we get to discover everything they wrote afterward.”</blockquote></div><div className="firstReadCard"><span>AFTER THE WEDDING</span><h3>Open together.<br/>Take your time.</h3><p>The wedding may be over. This part has not happened yet.</p></div></section>
 <section className="rareSection"><div><div className="eyebrow rareEyebrow">Rare Cards · Story and Bespoke tiers</div><h2>The cards guests hope they draw.</h2><p><b>Story is our $219 personalization tier.</b> It includes ten uniquely personalized Rare Cards written from the couple’s actual people, pets, places, and memories. They feel collectible and exceptional without turning the guestbook into a game.</p></div><figure><img src="/brand/deck/Robinson_002_Remember_Back.png" alt="A personalized Story-tier Rare Card referencing the couple’s pets"/></figure></section>
 <section className="openWhen"><div><div className="eyebrow">Open When cards</div><h2>Some memories are meant for tomorrow. Some are meant to find you years later.</h2><p>Guests complete these during the wedding, but you intentionally save them past the First Read. Open them on your first anniversary, when you buy a home, when marriage feels hard, when you need a laugh, or in five years.</p><ul><li>Completed by your guests at the wedding</li><li>Sealed and held for a future milestone</li><li>A new wedding-day message waiting later in your marriage</li></ul></div><div className="delayedCards delayedCardsSingle"><figure><img src="/brand/deck/Robinson_083_Delayed_Back.png" alt="Open on your first anniversary card"/></figure></div></section>
 <section className="deckStyleExamples"><div><div className="eyebrow">Choose a direction</div><h2>Your names, photo, and style come together before checkout.</h2><p>Try the customer studio, compare distinct card treatments, and carry the exact tier you select into checkout.</p><a href="/create/deck" className="button gold">Customize your deck →</a></div><div><img src="/brand/examples/carter-deck-midnight.webp" alt="Midnight blue Olivia and James Memento Deck example"/><img src="/brand/examples/carter-deck-editorial.webp" alt="Editorial blue Olivia and James Memento Deck example"/></div></section>
 <section className="pricingSection" id="pricing"><div className="eyebrow">Find your deck</div><h2>The same meaningful experience, with more capacity and personalization as you grow.</h2><div className="shippingBanner">Premium full-color cards and free shipping are included with every deck.</div><div className="pricingGrid four">{deckTiers.map(t=><article className={`priceCard ${t.popular?"popular":""}`} key={t.id}>{t.popular&&<span className="popularTag">MOST POPULAR</span>}<h3>{t.name}</h3><strong>${t.price}</strong><p>{t.subtitle}</p><ul>{t.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a href={`/create/deck?tier=${t.id}`} className="button gold">Customize {t.name} →</a></article>)}</div></section>
 <section className="addons"><div className="eyebrow">Add future moments</div><h2>Open When Collections</h2><div><article><h3>5-card Collection <b>+$40</b></h3><p>Five milestone cards, completed at the wedding and held back from your First Read.</p><a href="#pricing" className="textLink">Choose a deck, then add this at checkout →</a></article><article><h3>10-card Expanded Collection <b>+$60</b></h3><p>Ten future moments across the years ahead. Already included with Bespoke.</p><a href="#pricing" className="textLink">Choose a deck, then add this at checkout →</a></article></div></section>
 <section className="deckFaq"><div className="eyebrow">Questions, answered</div><h2>Designed to be effortless at the wedding.</h2><details><summary>Do we read the cards during the reception?</summary><p>You can, but there is no need to pause the celebration. Most couples let guests add completed cards to the collection, then enjoy their First Read together afterward.</p></details><details><summary>What do guests do?</summary><p>Pick a category, draw a card, answer the prompt, sign it, and place it in Completed Mementos.</p></details><details><summary>Can the deck reflect our actual story?</summary><p>Yes. The Story pricing tier includes ten cards personalized around your relationship; Bespoke adds deeper custom categories, prompts, and visual concepts.</p></details><details><summary>What happens after the First Read?</summary><p>Revisit stories, see which predictions came true, follow date and travel ideas, display favorites, and open milestone cards later.</p></details></section>
 <section className="houseCta"><div className="eyebrow">Made by everyone you invited</div><h2>Your guests create it.<br/>You get to discover it.</h2><div><a href="#pricing" className="button gold">Create Your Deck →</a></div></section>
 <footer className="houseFooter"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/memento-map">Memento Map</a><a href="/unity-tile-signature-board">Unity Tile</a><a href="/shipping">Shipping</a><a href="/refunds">Refunds</a><a href="/contact">Contact</a></div><small>© 2026 Memento House</small></footer>
 </main>}
