import {deckTiers,orderHref} from "../../lib/product-tiers";
export const metadata={title:"The Memento Deck | Memento House",description:"A collectible interactive guestbook created by your wedding guests, one card at a time."};
const categories=["REMEMBER — memories and stories","ADVISE — marriage wisdom","PREDICT — glimpses of your future","ADVENTURE — places and bucket-list ideas","TOGETHER — dates and traditions","CONFESS — funny, revealing stories"];
export default function MementoDeck(){return <main className="productPage">
 <nav className="houseNav"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/#keepsakes">All keepsakes</a><a href={orderHref("deck","story")} className="button small">Choose a deck</a></div></nav>
 <section className="productHero"><div><div className="eyebrow">Collectible interactive guestbook</div><h1>The Memento<br/><em>Deck</em></h1><p>A personalized deck of oversized 3.5 × 5 collectible cards whose final content is created by your guests during the wedding. They choose a category, draw a prompt, answer it, sign it, and add it to your Completed Mementos.</p><a href={orderHref("deck","story")} className="button gold">Choose your deck →</a></div><figure className="deckHero"><img src="/brand/memento-deck-cover.webp" alt="Personalized Memento Deck cover"/><img src="/brand/memento-deck-card.webp" alt="Memento Deck story card"/></figure></section>
 <section className="productSteps"><div className="eyebrow">The wedding experience</div><h2>Your guests create the guestbook.</h2><div><article><b>01</b><h3>Choose + draw</h3><p>Guests choose a prompt category, then draw a different card so the collection gathers many kinds of stories.</p></article><article><b>02</b><h3>Answer + sign</h3><p>They write a memory, prediction, confession, or piece of advice in their own voice and sign the card.</p></article><article><b>03</b><h3>Complete the deck</h3><p>Cards go into the Completed Mementos box, ready for the couple’s private First Read after the wedding.</p></article></div></section>
 <section className="categorySection"><div><div className="eyebrow">Six ways to leave a memento</div><h2>Not everyone answers the same questions.</h2><p>Each category contains many prompts. Card fronts can feature names, wedding date, photos, colors, icons, stats, rarity treatments, and artwork; backs hold the prompt, response, and signature.</p></div><div className="categoryGrid">{categories.map(c=><span key={c}>{c}</span>)}</div></section>
 <section className="pricingSection"><div className="eyebrow">Find your deck</div><h2>From classic prompts to a deck built around your story.</h2><div className="pricingGrid four">{deckTiers.map(t=><article className={`priceCard ${t.popular?"popular":""}`} key={t.id}>{t.popular&&<span className="popularTag">MOST POPULAR</span>}<h3>{t.name}</h3><strong>${t.price}</strong><p>{t.subtitle}</p><ul>{t.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a href={orderHref("deck",t.id)} className="button gold">{t.cta} →</a></article>)}</div></section>
 <section className="addons"><div className="eyebrow">Keep part of the story for later</div><h2>Open When Collections</h2><div><article><h3>Open When Collection <b>+$40</b></h3><p>Five sets for milestones such as your first anniversary, first home, first big adventure, or a day you need a reminder of the wedding.</p></article><article><h3>Expanded Collection <b>+$60</b></h3><p>Ten Open When sets. Bespoke already includes an Open When package, so no duplicate add-on is needed.</p></article></div></section>
 <footer className="houseFooter"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/memento-map">Memento Map</a><a href="/unity-tile-guestbook">Unity Tile Signature Board</a></div><small>© 2026 Memento House</small></footer>
 </main>}
