"use client";
import {FormEvent,useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../../lib/supabase";

const transitions:Record<string,string[]>={payment_pending:["paid","cancelled"],paid:["awaiting_customer_information","ready_for_design","account_ready","refunded"],awaiting_customer_information:["ready_for_design","cancelled","refunded"],ready_for_design:["design_in_progress","cancelled","refunded"],design_in_progress:["proof_ready","cancelled","refunded"],proof_ready:["awaiting_customer_approval","cancelled","refunded"],awaiting_customer_approval:["changes_requested","approved","cancelled","refunded"],changes_requested:["design_in_progress","cancelled","refunded"],approved:["in_production","cancelled","refunded"],in_production:["ready_to_ship","cancelled","refunded"],ready_to_ship:["shipped","cancelled","refunded"],shipped:["delivered","refunded"],delivered:["completed","refunded"],account_ready:["active","refunded"],active:["refunded"],completed:["refunded"]};
const human=(value="")=>value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());

export default function AdminOrders(){
 const[orders,setOrders]=useState<any[]>([]),[catalog,setCatalog]=useState<any[]>([]),[analytics,setAnalytics]=useState<any>(),[tab,setTab]=useState<"orders"|"analytics">("orders"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[open,setOpen]=useState<string|null>(null),[proofUpload,setProofUpload]=useState<{id:string;state:"uploading"|"uploaded"}|null>(null);
 async function token(){return(await getSupabaseBrowserClient()?.auth.getSession())?.data.session?.access_token}
 async function load(){setLoading(true);setError("");try{const value=await token();if(!value){location.href="/login";return}const response=await fetch("/api/admin/orders",{headers:{authorization:`Bearer ${value}`}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Administrator console failed (${response.status}).`);setOrders(data.orders||[]);setCatalog(data.catalog||[]);setAnalytics(data.analytics)}catch(reason){setError(reason instanceof Error?reason.message:"Administrator console could not be loaded.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function request(method:string,body:any){setError("");setNotice("");const value=await token(),response=await fetch("/api/admin/orders",{method,headers:{"content-type":"application/json",authorization:`Bearer ${value}`},body:JSON.stringify(body)}),data=await response.json();if(!response.ok){setError(data.error||"The order could not be updated.");return false}await load();return true}
 async function uploadProof(order:any,event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;setError("");setNotice("");setProofUpload({id:order.id,state:"uploading"});try{const form=new FormData(formElement),value=await token();if(!value)throw new Error("Your administrator session expired. Sign in again and retry.");form.set("orderId",order.id);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);let response:Response;try{response=await fetch("/api/admin/proofs",{method:"POST",headers:{authorization:`Bearer ${value}`},body:form,signal:controller.signal})}finally{clearTimeout(timer)}const raw=await response.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={error:raw}}if(!response.ok)throw new Error(data.error||`Proof upload failed (${response.status}).`);formElement.reset();setProofUpload({id:order.id,state:"uploaded"});setNotice(data.notice||`Proof uploaded and sent to ${order.customer_email} for approval.`);await load()}catch(reason){setProofUpload(null);setError(reason instanceof DOMException&&reason.name==="AbortError"?"The upload took longer than one minute. Refresh the order to check whether the proof completed before retrying.":reason instanceof Error?reason.message:"Proof upload failed.");await load()}}
 async function openProof(id:string){const value=await token(),response=await fetch(`/api/admin/proofs?id=${encodeURIComponent(id)}`,{headers:{authorization:`Bearer ${value}`}}),data=await response.json();if(!response.ok||!data.url){setError(data.error||"Proof could not be opened.");return}window.open(data.url,"_blank","noopener,noreferrer")}
 async function change(order:any,status:string){if(status==="shipped"){setError("Enter shipping details below before marking this order shipped.");return}await request("PATCH",{id:order.id,order_status:status})}
 async function ship(order:any,event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),tracking_number=String(form.get("tracking_number")||"").trim(),shipping_carrier=String(form.get("shipping_carrier")||"").trim(),tracking_url=String(form.get("tracking_url")||"").trim();if(!tracking_number||!shipping_carrier){setError("Carrier and tracking number are required.");return}if(await request("PATCH",{id:order.id,order_status:"shipped",tracking_number,shipping_carrier,tracking_url}))setNotice(`Shipment saved and notification sent to ${order.customer_email}.`)}
 async function remove(order:any){if(!confirm(order.is_test?"Permanently delete this test order?":"Archive this order? Payment and activity records will remain auditable."))return;await request("DELETE",{id:order.id})}
 return <main className="adminOrders"><header><a href="/dashboard">← Dashboard</a><div><span className="eyebrow">Private operations</span><h1>Orders & fulfillment</h1><p>Customer ownership, proofs, approvals, production, shipping, and analytics in one console.</p></div></header>
  <nav className="adminTabs"><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Order console</button><button className={tab==="analytics"?"active":""} onClick={()=>setTab("analytics")}>Analytics</button><a href="/admin/deck-studio">Deck studio</a><a href="/admin/word-grid-studio">Unity studio</a></nav>
  {loading&&<p>Loading…</p>}{error&&<p className="authError" role="alert">{error}</p>}{notice&&<p className="adminNotice">{notice}</p>}
  {tab==="analytics"&&analytics&&<><section className="orderStats"><b>{analytics.orders}<small>Active orders</small></b><b>${(analytics.revenue/100).toLocaleString()}<small>Revenue</small></b><b>${(analytics.averageOrder/100).toFixed(0)}<small>Average order</small></b><b>{analytics.awaitingApproval}<small>Awaiting approval</small></b><b>{analytics.toShip}<small>Production / shipping queue</small></b></section><section className="adminAnalytics"><h2>Sales by product</h2>{analytics.byProduct.map((row:any)=><article key={row.key}><b>{row.key}</b><span>{row.orders} orders</span><strong>${(row.revenue/100).toLocaleString()}</strong></article>)}</section></>}
  {tab==="orders"&&<><section className="adminCatalog"><div className="eyebrow">Products and release state</div>{catalog.map(item=><article key={item.key}><b>{item.displayName}</b><span>${(item.price/100).toFixed(2)}</span><small>{item.entitlement} · {item.fulfillmentWorkflow}</small></article>)}</section><div className="orderConsole">{orders.map(order=>{const questionnaire=order.questionnaires?.[0],proof=order.proofs?.[0];return <article key={order.id} className="adminOrderCard"><button className="orderExpand" onClick={()=>setOpen(open===order.id?null:order.id)}><span><i className={order.is_test?"testBadge":"paidBadge"}>{order.is_test?"TEST":"ORDER"}</i><b>{order.customer_name||order.customer_email}</b><small>{new Date(order.created_at).toLocaleString()} · {order.catalog_key} · ${(order.amount_total/100).toFixed(2)}</small></span><strong>{human(order.order_status)} {open===order.id?"−":"+"}</strong></button>{open===order.id&&<div className="orderDetails"><section className="orderSnapshot"><p><b>Account:</b> {order.customer_user_id?"Connected":"Needs account linkage"}</p><p><b>Questionnaire:</b> {questionnaire?human(questionnaire.status):"Not required"}</p><p><b>Latest proof:</b> {proof?`Version ${proof.version} · ${human(proof.status)}`:"Not uploaded"}</p><p><b>Shipping:</b> {order.tracking_number?`${order.shipping_carrier||"Carrier"} · ${order.tracking_number}`:"Not shipped"}</p></section>
   <section className="orderIdentity"><p><b>Customer:</b> {order.customer_name||"Name not provided"} · {order.customer_email}</p><p><b>Ordered:</b> {new Date(order.created_at).toLocaleString()}</p></section><label>Next workflow state<select value="" onChange={event=>{void change(order,event.target.value);event.currentTarget.value=""}}><option value="">Choose next action…</option>{(transitions[order.order_status]||[]).map(value=><option value={value} key={value}>{human(value)}</option>)}</select></label>
   {order.kind!=="digital"&&<form className="proofUpload" onSubmit={event=>void uploadProof(order,event)}><h3>Customer proof</h3><p>Upload the customer-facing PNG or PDF. Sending it moves the order into customer approval.</p><input name="file" type="file" accept="image/png,image/jpeg,application/pdf" required/><textarea name="message" placeholder="Optional note for the customer"/><button className="button gold" disabled={proofUpload?.id===order.id&&proofUpload?.state==="uploading"}>{proofUpload?.id===order.id?(proofUpload?.state==="uploaded"?"Uploaded ✓":"Uploading…"):"Upload and send proof"}</button>{proof&&<button type="button" className="button light" onClick={()=>void openProof(proof.id)}>Open latest proof ↗</button>}</form>}
   {order.fulfillment_workflow!=="digital_map"&&<><form className="shippingForm" onSubmit={event=>void ship(order,event)}><h3>Shipping & customer notification</h3><p>Marking shipped automatically emails the customer through Memento House.</p><div className="twoCols"><label>Carrier<input name="shipping_carrier" defaultValue={order.shipping_carrier||""} required/></label><label>Tracking number<input name="tracking_number" defaultValue={order.tracking_number||""} required/></label></div><label>Tracking URL<input name="tracking_url" type="url" defaultValue={order.tracking_url||""}/></label><button className="button gold" disabled={order.order_status!=="ready_to_ship"}>Mark shipped & email customer →</button></form>{order.product==="unity"&&order.customization&&<a className="button light" href={`/admin/word-grid-studio?order=${order.id}`}>Open saved board · export PNG/PDF →</a>}</>}{order.customization&&<details><summary>Saved customization</summary><pre>{JSON.stringify(order.customization.payload,null,2)}</pre></details>}<label className="orderNotes">Internal notes<textarea defaultValue={order.internal_notes||""} onBlur={event=>void request("PATCH",{id:order.id,internal_notes:event.target.value})}/></label><div className="orderDanger"><button onClick={()=>void remove(order)}>{order.is_test?"Delete test order":"Archive order"}</button><small>Paid orders are archived, not erased, to preserve financial and fulfillment history.</small></div></div>}</article>})}</div></>}
 </main>
}
