import type {MementoMapType} from '../../lib/memento-map-types';
const guidance:Record<MementoMapType,{name:string;question:string;steps:[string,string][]}>={
 wedding:{name:'From wedding day to life together',question:'Do you want guest origins, future trip ideas, or a chronological relationship story?',steps:[['A simple guest interaction','Scan the QR sign, choose a place, add your name and a short memory or recommendation, and submit. A simple place contribution can take about 30 seconds; longer stories take as long as guests need.'],['Before and during the wedding','Add the couple and venue details, test the link on a phone, and print your QR sign. Display it where guests can pause and contribute; a tablet or screen can show the map.'],['After the celebration','Revisit guest origins together. With Plus, organize suggested adventures and record visits; Timeline Plus connects milestones in chronological order.']]},
 family_reunion:{name:'Meet the Bennett family · fictional example',question:'Are you collecting where everyone lives today, family history, or both?',steps:[['Invite every branch','The Bennett reunion host shares the same link by message with cousins who cannot attend. Relatives can contribute from home without an account.'],['Keep the family connections clear','Ask contributors to include their family branch in their name or story, such as “Sam · Eleanor’s branch.” Add dates to distinguish childhood homes and past reunions.'],['Between reunions','One owner maintains the map. Keep contributions open for more stories, or pause them while organizing the collection. A permanently closed map cannot accept new guest submissions.']]},
 celebration_of_life:{name:'Remembering Eleanor Bennett · fictional example',question:'Would places and written memories fit your tribute, or would a chronological life story help?',steps:[['Begin gently','Start with a name, a favorite place, and one memory, such as Eleanor’s garden in Asheville. Add dates and further chapters when you feel ready.'],['Understand who can see it','Share the map link only with the people you intend to invite. Anyone who receives or is forwarded the link can open the shared map; it is not a password-protected family space.'],['Choose what is shared','Places and guest memories publish immediately; there is no pre-approval queue. Owners can hide map contributions and use Timeline Plus controls to manage published memories. Pause submissions while you organize, or close them permanently when the tribute is ready.']]},
 next_chapter:{name:'A gift for the chapter ahead',question:'Which occasion are you celebrating, and who will organize the contributions?',steps:[['Choose the occasion','Graduation, retirement, baby shower, new home, and milestone birthday each have their own example places and prompts. For a move or housewarming, choose New Home.'],['Choose an owner','The celebrant or a friend or family member can purchase and organize the map from their own account. The purchasing account remains the owner.'],['Plan a surprise thoughtfully','A friend can gather contributions before sharing the link with the recipient. Ask contributors to keep it secret; anyone who receives the link can view it. Account ownership does not automatically transfer when you share the gift.']]},
 events_community:{name:'Oakwood Community Day · fictional example',question:'Are you showing attendee reach, collecting community memories, or building an event history?',steps:[['Invite participation','An Oakwood organizer displays the QR sign at check-in. Attendees add their hometown or a memory such as the community garden’s first planting.'],['Display and preserve the gathering','Open the shared map on an organizer-provided screen. Plus includes a map export; Timeline Plus adds a chronological story and combined keepsake.'],['Plan recurring use','One purchase creates one map owned by the purchasing account. Reuse it while contributions remain open and within its media limits. Separate event maps require separate purchases; this is not a multi-user organization subscription.']]}
};
export function AudienceGuidance({type}:{type:MementoMapType}){const item=guidance[type];return <section className="how typeHow"><div className="eyebrow">Plan your experience</div><h2>{item.name}</h2><p>{item.question}</p><div className="steps">{item.steps.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div>{type==='celebration_of_life'&&<a className="textLink" href="/contact?celebration=Celebration%20of%20Life">Ask for help getting your tribute started →</a>}{type==='wedding'&&<a className="textLink" href="/map/jonah-kate">Try the guest interaction in the wedding demo →</a>}</section>}
