import type {MementoMapType} from "../../lib/memento-map-types";

type MapTypeVisuals={hero:{src:string;alt:string};map:{src:string;alt:string};keepsake:{src:string;alt:string}};

export const MEMENTO_MAP_TYPE_VISUALS:Record<MementoMapType,MapTypeVisuals>={
 wedding:{hero:{src:"/brand/map-wedding-hero.webp",alt:"A wedding guest scanning the couple's Memento House QR sign beside their interactive map"},map:{src:"/brand/map-wedding-map.webp",alt:"Wedding Memento Map with guest origins, recommendations, relationship places, and a chronological timeline"},keepsake:{src:"/brand/map-wedding-keepsake.webp",alt:"A finished Wedding Memento Map framed in the couple's home"}},
 family_reunion:{hero:{src:"/brand/map-family-reunion-hero.webp",alt:"Several generations sharing family origins and memories through a Memento House QR sign and map"},map:{src:"/brand/map-family-reunion-map.webp",alt:"Family Reunion Memento Map showing family origins, homes, reunion cities, trips, and family history"},keepsake:{src:"/brand/map-family-reunion-keepsake.webp",alt:"A framed Family Reunion Memento Map displayed with a family album and photograph"}},
 celebration_of_life:{hero:{src:"/brand/map-celebration-of-life-hero.webp",alt:"Family and friends sharing memories through a Celebration of Life Memento Map"},map:{src:"/brand/map-celebration-of-life-map.webp",alt:"Celebration of Life Memento Map with childhood, school, work, travel, favorite-place, and memory pins"},keepsake:{src:"/brand/map-celebration-of-life-keepsake.webp",alt:"A warm framed memorial map preserving the meaningful places and chapters of a life"}},
 next_chapter:{hero:{src:"/brand/map-next-chapter-hero.webp",alt:"A person opening a hopeful next chapter with contributed memories and future-place ideas"},map:{src:"/brand/map-next-chapter-map.webp",alt:"Next Chapter Memento Map balancing past memories with restaurants, destinations, and future ideas"},keepsake:{src:"/brand/map-next-chapter-keepsake.webp",alt:"A framed Next Chapter map displayed in a warm new home or study"}},
 events_community:{hero:{src:"/brand/map-events-hero.webp",alt:"Conference attendees scanning a Memento House QR sign beside a community map"},map:{src:"/brand/map-events-map.webp",alt:"Events and Communities Memento Map showing attendee origins, organizations, venues, stories, and reach"},keepsake:{src:"/brand/map-events-keepsake.webp",alt:"A framed community reach map displayed in a modern organization space"}},
};
