const examples=[
 {title:"Graduation",image:"/brand/celebrations/graduation-1.webp",alt:"Friends celebrating a graduation",copy:"Classmates, mentors, and family can map the places that shaped the graduate and add ideas for the city, campus, or opportunities ahead.",pins:["School memories","Mentors & friends","Future cities"]},
 {title:"Retirement",image:"/brand/celebrations/retirement-1.webp",alt:"Colleagues celebrating a retirement",copy:"Colleagues can connect career chapters to real offices, project sites, and people, while friends and family contribute places for the freedom ahead.",pins:["Career chapters","Colleague memories","Retirement plans"]},
 {title:"Moving or a new home",image:"/brand/celebrations/new-home-1.webp",alt:"Friends welcoming someone to a new home",copy:"Preserve favorite places from the old neighborhood, gather local recommendations for the new one, and record the first traditions created there.",pins:["Homes so far","Local favorites","New traditions"]},
 {title:"Career transition",image:"/brand/map-next-chapter-map.webp",alt:"A Next Chapter map connecting past places and future opportunities",copy:"Friends and mentors can mark formative workplaces, share advice tied to meaningful places, and point toward industries, cities, or experiences worth exploring.",pins:["Work that shaped me","Mentor advice","Possibilities ahead"]},
 {title:"Going away",image:"/brand/map-next-chapter-keepsake.webp",alt:"A finished Next Chapter map displayed as a keepsake",copy:"Turn a farewell into a geographic collection of shared memories, hometown anchors, and recommendations that travel with the person leaving.",pins:["Places we shared","People back home","Where to visit next"]}
];

export function NextChapterExamples(){return <section className="nextChapterExamples" aria-labelledby="next-chapter-examples-title"><header><div className="eyebrow">Five ways to begin</div><h2 id="next-chapter-examples-title">One experience, shaped for the chapter ahead.</h2><p>These examples use the same Next Chapter Memento Map. The prompts, map layers, and contributions change to fit the milestone.</p></header><div>{examples.map(example=><article key={example.title}><img src={example.image} alt={example.alt}/><div><h3>{example.title}</h3><p>{example.copy}</p><ul>{example.pins.map(pin=><li key={pin}>⌖ {pin}</li>)}</ul></div></article>)}</div></section>}
