import {mapTiers,orderHref} from "../../lib/product-tiers";
import {AccountLink} from "../account-link";
export const metadata={title:"Memento Map — Interactive wedding map",description:"Guests help create the map at the wedding. The couple keeps building it afterward.",alternates:{canonical:"/memento-map"}};
const schema={"@context":"https://schema.org","@type":"SoftwareApplication",name:"Memento Map",applicationCategory:"LifestyleApplication",operatingSystem:"Web",description:"An interactive wedding map for guest origins, travel recommendations, bucket-list places, and relationship milestones.",offers:{"@type":"AggregateOffer",priceCurrency:"USD",lowPrice:"99",highPrice:"179",offerCount:3,url:"https://mementohouse.com/memento-map#pricing"}};
export default function MementoMap(){return <main className="landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<nav className="nav"><a href="/" className="brand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><span>Memento <i>Map</i><small>by Memento House</small></span></a><div className="navLinks"><a href="#how">How it works</a><AccountLink/><a href="#pricing" className="button small">Create your map</a></div><details className="mobileMenu"><summary>Menu</summary><div><a href="#how">How it works</a><a href="#pricing">Plans</a><AccountLink/></div></details></nav>
<section className="hero"><div className="eyebrow">A wedding map shaped by the people who came</div><h1>See how far your people came.<br/>Save where they think you should <em>go next.</em></h1><p>Guests pin the place they traveled from, then leave a real destination they hope you experience together. By the end of the celebration, you have a map of the people who showed up and the places they sent you toward.</p><div className="heroActions"><a href="/map/jonah-kate" className="button">Explore the demo map <span>→</span></a><a href="#pricing" className="button light">Choose your map</a></div><div className="trust"><span>♡ No guest accounts required</span><span>⌂ See where everyone traveled from</span><span>✦ Save real travel recommendations</span><span>↗ Add up the miles traveled to celebrate</span></div></section>
<section className="productExperience"><img src="/brand/memento-map-product-mockup.webp" alt="Memento Map wedding display with QR invitation, interactive phone map, and framed world-map keepsake"/><div className="experienceCaption"><span>AT THE WEDDING</span><b>Scan. Recommend. Remember.</b><p>Every suggestion resolves to a real address or coordinate and appears on the couple’s live map.</p></div></section>
<section id="how" className="how"><div className="eyebrow">Beautifully simple</div><h2>One wedding map.<br/><em>Two layers of meaning.</em></h2><div className="steps"><article><b>01</b><h3>Create your map</h3><p>Add your wedding details and share your unique map or QR code.</p></article><article><b>02</b><h3>Map the gathering</h3><p>Each guest pins where they came from, showing how far your people traveled to celebrate.</p></article><article><b>03</b><h3>Recommend adventures</h3><p>Guests add real venues, addresses, landmarks, or cities for the couple to experience together.</p></article><article><b>04</b><h3>Keep it forever</h3><p>Turn the combined map into trips and a print-ready record of the people behind every place.</p></article></div></section>
<section className="categorySection"><div><div className="eyebrow">One map, coordinated layers</div><h2>Category tells you what a pin means. Status tells you where the journey stands.</h2><p>Wedding-coordinated colors keep Our Story, Travel Recommendations, Guest Origins, and Couple Bucket List places distinct. Want to Go, Planning, and Visited appear as a secondary status—never replacing the category color.</p></div><div className="layerPreview"><span><i className="storyLayer"/>Our Story</span><span><i className="recLayer"/>Travel Recommendations</span><span><i className="originLayer"/>Guest Origins</span><span><i className="futureLayer"/>Couple Bucket List</span></div></section>
<section className="pricingSection" id="pricing"><div className="eyebrow">Choose your map</div><h2>Create it. Live it. Keep it.</h2><div className="pricingGrid three">{mapTiers.map(t=><article className={`priceCard ${t.popular?"popular":""}`} key={t.id}>{t.popular&&<span className="popularTag">MOST POPULAR</span>}<h3>{t.name}</h3><strong>${t.price}</strong><p>{t.subtitle}</p><ul>{t.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a href={orderHref("map",t.id)} className="button gold">{t.cta} →</a></article>)}</div></section>
<section className="comparison"><div className="eyebrow">Feature comparison</div><h2>Choose the experience that fits what you want to keep.</h2><div className="comparisonTable threePlans"><div><b>Feature</b><b>Map</b><b>Plus</b><b>Timeline Plus</b></div>{[["Interactive map + wedding QR","Yes","Yes","Yes"],["Guest origins + recommendations","Yes","Yes","Yes"],["Venue distance traveled","Yes","Yes","Yes"],["Voting + advanced statistics","—","Yes","Yes"],["Want to Go / Planning / Visited","—","Yes","Yes"],["Photos + post-wedding memories","—","Yes","Yes"],["Print-ready PNG + PDF export","—","Yes","Yes"],["Chronological relationship timeline","—","—","Yes"],["Guest timeline memories + approval","—","—","Yes"],["Private-link and public story views","—","—","Yes"],["Combined map + timeline keepsake","—","—","Yes"]].map(r=><div key={r[0]}>{r.map((c,i)=><span key={i}>{c}</span>)}</div>)}</div></section>
<section className="houseCta"><div className="eyebrow">Your story starts here</div><h2>Guests help create it now.<br/>You keep building it together.</h2><div><a href={orderHref("map","plus")} className="button gold">Choose Map Plus →</a><a href="/map/jonah-kate" className="button light">Explore the demo</a></div></section>
<footer><a href="/" className="brand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><span>Memento <i>Map</i></span></a><p>Made for the moment. Kept for a lifetime.</p><div className="footerLinks"><a href="/">Memento House</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></div></footer>
</main>}
