export const metadata={title:"Memento Map — A wedding adventure map by Memento House",description:"Turn your guests’ favorite places into your next adventure."};
export default function MementoMap(){return <main className="landing">
<nav className="nav"><a href="/" className="brand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><span>Memento <i>Map</i><small>by Memento House</small></span></a><div className="navLinks"><a href="#how">How it works</a><a href="/login">Couple login</a><a href="/signup" className="button small">Create your map</a></div></nav>
<section className="hero"><div className="eyebrow">A wedding keepsake for everyone who gathered—and every adventure ahead</div><h1>Map the people who came.<br/>Then map where you’ll <em>go together.</em></h1><p>Guests first pin where they live and traveled from for your wedding. Then they recommend meaningful places for your life ahead—creating one map of the people who gathered and the adventures still to come.</p><div className="heroActions"><a href="/map/jonah-kate" className="button">Explore the demo map <span>→</span></a><a href="/signup" className="button light">Create your map</a></div><div className="trust"><span>♡ No guest accounts</span><span>⌂ Guest origins</span><span>✦ Travel recommendations</span></div></section>
<section className="productExperience"><img src="/brand/memento-map-product-mockup.png" alt="Memento Map wedding display with QR invitation, interactive phone map, and framed world-map keepsake"/><div className="experienceCaption"><span>AT THE WEDDING</span><b>Scan. Recommend. Remember.</b><p>Every suggestion resolves to a real address or coordinate and appears on the couple’s live map.</p></div></section>
<section id="how" className="how"><div className="eyebrow">Beautifully simple</div><h2>One wedding map.<br/><em>Two layers of meaning.</em></h2><div className="steps"><article><b>01</b><h3>Create your map</h3><p>Add your wedding details and share your unique map or QR code.</p></article><article><b>02</b><h3>Map the gathering</h3><p>Each guest pins where they came from, showing how far your people traveled to celebrate.</p></article><article><b>03</b><h3>Recommend adventures</h3><p>Guests add real venues, addresses, landmarks, or cities for the couple to experience together.</p></article><article><b>04</b><h3>Keep it forever</h3><p>Turn the combined map into trips and a print-ready record of the people behind every place.</p></article></div></section>
<section className="houseCta"><div className="eyebrow">Your story starts here</div><h2>Build the map you’ll keep<br/>throughout your marriage.</h2><div><a href="/signup" className="button gold">Create your map →</a><a href="/map/jonah-kate" className="button light">Explore the demo</a></div></section>
<footer><a href="/" className="brand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><span>Memento <i>Map</i></span></a><p>Made for the moment. Kept for a lifetime.</p><a href="/">Visit Memento House →</a></footer>
</main>}
