import {forwardRef,useRef} from 'react';
import type {PhotoState,Piece,Project} from '../types';
import {cardNumber,formatDate,isRarePiece,promptForPiece} from '../utils';
import {palettes,themes} from '../data';
const rgb=(hex:string)=>{const n=parseInt(hex.replace('#','').padEnd(6,'0').slice(0,6),16);return[n>>16,(n>>8)&255,n&255]};
const luminance=(hex:string)=>rgb(hex).map(v=>{const c=v/255;return c<=.03928?c/12.92:Math.pow((c+.055)/1.055,2.4)}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);
const contrast=(a:string,b:string)=>{const [hi,lo]=[luminance(a),luminance(b)].sort((x,y)=>y-x);return(hi+.05)/(lo+.05)};
const readable=(surface:string,preferred:string)=>contrast(preferred,surface)>=4.5?preferred:['#111111','#ffffff'].sort((a,b)=>contrast(b,surface)-contrast(a,surface))[0];
export const CardCanvas=forwardRef<HTMLDivElement,{project:Project;piece:Piece;exporting?:boolean;onPhotoChange?:(photo:PhotoState)=>void}>(({project:p,piece,exporting,onPhotoChange},ref)=>{
 const pal=p.settings.paletteId==='custom'?p.settings.customPalette:palettes[p.settings.paletteId],t=p.templates.find(x=>x.id===piece.category),relatedT=p.templates.find(x=>x.id===piece.relatedCategory),number=cardNumber(piece,p),prompt=promptForPiece(p,piece),rare=isRarePiece(p,piece),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),names=`${p.info.partner1} + ${p.info.partner2}`;
 const darkFront=['moody','celestial'].includes(p.settings.theme)&&p.settings.paletteId!=='blackWhite',frontSurface=darkFront?pal.primary:pal.background,frontText=p.settings.frontTextColor||readable(frontSurface,darkFront?pal.background:pal.primary),backText=p.settings.backTextColor||readable(pal.background,pal.primary);
 const style={'--bg':pal.background,'--ink':pal.primary,'--accent':pal.accent,'--front-text':frontText,'--back-text':backText,'--display':p.settings.fonts.display||'Cormorant Garamond','--body':p.settings.fonts.body||'Georgia','--label':p.settings.fonts.label||'Arial','--name-size':`${names.length>34?19:names.length>27?22:names.length>21?26:30}px`,'--title-size':`${(t?.title.length||0)>24?23:(t?.title.length||0)>18?27:31}px`,'--prompt-size':`${prompt.length>120?11:prompt.length>85?13:15}px`} as React.CSSProperties;
 const Logo=({className='mh-logo'}:{className?:string})=><img className={className} src="/studios/deck/memento-house-logo-transparent-v5.png" alt="Memento House"/>;
 const Portrait=()=> <div className={`photo-frame ${onPhotoChange?'adjustable':''}`} onPointerDown={e=>{if(onPhotoChange){drag.current={x:p.photo.x,y:p.photo.y,px:e.clientX,py:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(drag.current&&onPhotoChange)onPhotoChange({...p.photo,x:drag.current.x+e.clientX-drag.current.px,y:drag.current.y+e.clientY-drag.current.py})}} onPointerUp={()=>drag.current=null}>{p.photo.dataUrl?<img src={p.photo.dataUrl} style={{transform:`translate(${p.photo.x}px,${p.photo.y}px) rotate(${p.photo.rotation}deg) scale(${p.photo.zoom})`}} draggable={false}/>:<div className="photo-placeholder"><Logo/><small>COUPLE PORTRAIT</small></div>}<div className="photo-frame-overlay"/>{onPhotoChange&&p.photo.dataUrl&&<span className="drag-hint">DRAG TO REPOSITION</span>}</div>;
 const Footer=({text}:{text:string})=><div className="card-footer"><span>{text}</span><b>{number}</b></div>;
 const Front=()=>{if(piece.category==='firstRead')return <><div className="card-kicker">THE MEMENTO DECK · AFTER THE WEDDING</div><Logo className="ritual-logo"/><div className="front-copy ritual-copy"><div className="surname">THE FIRST READ</div><h2>You Made the Memories.<br/><i>Now Read Them.</i></h2><p>Open together after the honeymoon.</p></div><Footer text={p.settings.showBranding?'MEMENTO HOUSE':''}/></>;if(piece.category==='divider')return <><div className="card-kicker">THE {p.info.lastName.toUpperCase()} MEMENTO DECK</div><div className="divider-art"><Logo/></div><div className="front-copy divider-copy"><div className="surname">CATEGORY DIVIDER</div><h2>{relatedT?.badge}</h2><p>{relatedT?.purpose}</p></div><Footer text="ARCHIVE BY CATEGORY"/></>;if(piece.category==='delayed')return <><div className="card-kicker">A MEMENTO FOR LATER</div><Logo className="ritual-logo"/><div className="front-copy ritual-copy"><div className="surname">FOR {piece.recipient?.toUpperCase()} · DO NOT OPEN YET</div><h2>{piece.openLabel}</h2><p>Keep this sealed until the moment arrives.</p></div><Footer text={`THE ${p.info.lastName.toUpperCase()}S`}/></>;return <><div className="card-kicker">THE {p.info.lastName.toUpperCase()} MEMENTO DECK</div><div className={`badge ${rare?'rare':''}`}>{rare?'RARE MEMENTO':piece.category==='couple'?'COUPLE COVER':t?.badge||'MEMENTO'}</div><Portrait/><div className="front-copy"><div className="surname">{piece.category==='couple'?`THE ${p.info.lastName.toUpperCase()}S`:t?.title.toUpperCase()}</div><h2 title={names}>{p.info.partner1||'Partner 1'} <i>+</i> {p.info.partner2||'Partner 2'}</h2><p>{formatDate(p.info.weddingDate)}</p><p>{piece.category==='couple'?[p.info.city,p.info.state].filter(Boolean).join(', '):t?.purpose}</p><em>{rare?'GOLDEN MEMENTO':`MEMENTO No. ${String(piece.number).padStart(3,'0')}`}</em></div><Footer text={p.settings.showBranding?'MEMENTO HOUSE':''}/></>};
 const Back=()=> piece.category==='couple'?<><div className="back-head"><span>OUR STORY</span><h2>{p.info.partner1} <i>+</i> {p.info.partner2}</h2></div><div className="story">“{p.info.story}”</div><div className="story-grid"><div><b>FIRST MET</b>{p.info.firstMet}</div><div><b>FIRST DATE</b>{p.info.firstDate}</div><div><b>ENGAGED</b>{formatDate(p.info.engagementDate)}</div><div><b>WEDDING</b>{formatDate(p.info.weddingDate)}</div></div><Footer text={p.info.venue}/></>:piece.category==='instruction'?<><div className="back-head"><span>{(p.settings.experienceMode||'mixed').toUpperCase()} MODE</span><h2>Leave Us a Memento</h2></div><div className="instruction-copy">{p.instructionText.split('\n').map(x=><p key={x}>{x}</p>)}</div><Footer text={p.settings.showBranding?'MADE FOR THE MOMENT':''}/></>:piece.category==='firstRead'?<><div className="back-head"><span>A QUIET NIGHT TOGETHER</span><h2>Welcome Back to Your Wedding Day</h2></div><div className="instruction-copy"><p>Pour something you love.</p><p>Put your phones away.</p><p>Take turns drawing a card.</p><p>Read every memory, prediction, adventure and confession aloud.</p></div><Footer text="THE FIRST READ"/></>:piece.category==='divider'?<><div className="divider-back"><Logo/><h2>{relatedT?.badge}</h2><p>{relatedT?.purpose}</p><small>THE {p.info.lastName.toUpperCase()} MEMENTO DECK</small></div></>:piece.category==='delayed'?<><Logo className="delayed-back-logo"/><div className="back-head"><span>{piece.openLabel}</span><h2>A Note for Our Future</h2><p>{prompt}</p></div><div className={`writing-space ${p.settings.writingLines}`}></div><div className="fields"><div><b>To:</b><span>{piece.recipient}</span></div><div><b>From:</b><span>{piece.sender}</span></div></div><Footer text="SEALED AT OUR WEDDING"/></>:<><div className="back-head"><span>{rare?'RARE MEMENTO':t?.badge}</span><h2>{t?.title}</h2><p>{prompt}</p></div><div className={`writing-space ${p.settings.writingLines}`}></div><div className="fields">{t?.fields.map(f=><div key={f.label}><b>{f.label}:</b><span/></div>)}</div><Footer text={piece.customPrompt?'PERSONALIZED MEMENTO':p.settings.showBranding?'MEMENTO HOUSE':''}/></>;
 if(piece.category==='tableSign')return <div ref={ref} className={`card-canvas sign palette-${p.settings.paletteId} ${themes[p.settings.theme].className}`} style={style}><div className="sign-inner"><Logo className="sign-logo"/><span>THE {p.info.lastName.toUpperCase()}S · {p.info.weddingYear}</span><h1>LEAVE US<br/>A <i>MEMENTO</i></h1>{p.signText.split('\n').map((x,i)=><p key={i}>{x||' '}</p>)}<small>{p.settings.showBranding?'MEMENTO HOUSE · MADE FOR THE MOMENT. KEPT FOR A LIFETIME.':''}</small></div>{p.settings.showGuides&&!exporting&&<Guides/>}</div>;
 return <div ref={ref} className={`card-canvas ${piece.side} ${piece.category} palette-${p.settings.paletteId} ${themes[p.settings.theme].className}`} style={style}><div className="inner-border">{piece.side==='front'?<Front/>:<Back/>}</div>{p.settings.showGuides&&!exporting&&<Guides/>}</div>
});
function Guides(){return <><div className="guide trim"><span>TRIM</span></div><div className="guide safe"><span>SAFE</span></div></>}
