"use client";
import {getSupabaseBrowserClient} from "../../../lib/supabase";

type Props={section:string;setSection:(value:string)=>void;items:string[];tier:string;email:string;initials:string;names:string;date:string;mapPath:string;switchTier:(tier:string)=>void;testPurchase:(tier:"map"|"plus"|"timeline-plus")=>void};

export function DashboardSidebar({section,setSection,items,tier,email,initials,names,date,mapPath,switchTier}:Props){
 const admin=email.toLowerCase()==="jonahnr@gmail.com",plan=tier==="timeline-plus"?"Timeline Plus":tier==="plus"?"Map Plus":"Memento Map Standard";
 async function signOut(){await getSupabaseBrowserClient()?.auth.signOut();location.href="/login"}
 return <aside><div className="brand splitBrand"><a href="/" aria-label="Memento House home"><img src="/brand/memento-house-logo.webp" alt=""/></a><button onClick={()=>setSection("Overview")}><span>Memento <i>Map</i><small>by Memento House</small></span></button></div><div className="coupleChip"><span>{initials[0]}<span>&</span>{initials[1]}</span><div><b>{names}</b><small>{date}</small></div></div><div className="planBadge"><small>CURRENT PLAN</small><b>{plan}</b>{admin&&<select aria-label="Admin tier tester" value={tier} onChange={e=>switchTier(e.target.value)}><option value="map">Preview Standard</option><option value="plus">Preview Plus</option><option value="timeline-plus">Preview Timeline Plus</option></select>}</div><nav>{items.map((x,i)=>{const locked=tier==="map"&&["Our Story","Travel Journal","Keepsake"].includes(x);return <button key={x} title={locked?`${x} is included with Map Plus`:x} onClick={()=>locked?setSection("Settings"):setSection(x)} className={section===x?"active":""}><i>{["⌂","♥","✦","✓","◷","⌖","▦","◇","⚙"][i]||"·"}</i>{x}{locked&&<span className="navLock"> 🔒</span>}</button>})}</nav><div className="dashboardExit"><a href="/">← Memento House home</a><a href="/#keepsakes">Browse all keepsakes</a><a href={mapPath}>↗ Open adventure map</a>{admin&&<a href="/admin/orders">Order & fulfillment console</a>}<button type="button" onClick={signOut}>Log out</button></div></aside>
}
