"use client";
import {CartLink} from "../../cart-link";
import {getSupabaseBrowserClient} from "../../../lib/supabase";
import {mapExperienceLabels,type MementoMapType} from "../../../lib/memento-map-types";

type Props={section:string;setSection:(value:string)=>void;items:string[];tier:string;email:string;initials:string;names:string;date:string;mapPath:string;mapType?:MementoMapType;switchTier:(tier:string)=>void;testPurchase:(tier:"map"|"plus"|"timeline-plus")=>void;displayLabels?:Record<string,string>};

export function DashboardSidebar({section,setSection,items,tier,email,initials,names,date,mapPath,mapType,switchTier,displayLabels={}}:Props){
 const experience=mapExperienceLabels(mapType);
 const admin=email.toLowerCase()==="jonahnr@gmail.com",plan=tier==="timeline-plus"?"Timeline Plus":tier==="plus"?"Map Plus":"Memento Map Standard";
 async function signOut(){await getSupabaseBrowserClient()?.auth.signOut();location.href="/login"}
 const icon=(label:string)=>({"Overview":"overview","Our Story":"our-story","Recommendations":"recommendations","Travel Journal":"travel-journal","Timeline Plus":"timeline-plus","QR Code":"qr-code","Keepsake":"keepsake","Event Details":"event-details","My Account":"my-account"}[label]||"event-details");
 return <aside><div className="brand splitBrand"><a href="/" aria-label="Memento House home"><img src="/brand/memento-house-logo.webp" alt=""/></a><button onClick={()=>setSection("Overview")}><span>Memento <i>Map</i><small>by Memento House</small></span></button></div><div className="coupleChip"><span>{initials[0]}{initials.length>1&&<><span>&</span>{initials[1]}</>}</span><div><b>{names}</b><small>{date}</small></div></div><div className="planBadge"><small>CURRENT PLAN</small><b>{plan}</b>{admin&&<select aria-label="Admin tier tester" value={tier} onChange={e=>switchTier(e.target.value)}><option value="map">Preview Standard</option><option value="plus">Preview Plus</option><option value="timeline-plus">Preview Timeline Plus</option></select>}</div><nav>{items.map(x=>{const locked=tier==="map"&&["Our Story","Travel Journal","Keepsake"].includes(x),label=displayLabels[x]||x;return <button key={x} title={locked?`${label} is included with Map Plus`:label} onClick={()=>locked?setSection("Settings"):setSection(x)} className={section===x?"active":""}><i aria-hidden="true"><img src={`/brand/navigation/${icon(x)}.webp`} alt="" width={28} height={28}/></i>{label}{locked&&<span className="navLock"> 🔒</span>}</button>})}<CartLink label/></nav><div className="dashboardExit"><a href="/">← Memento House home</a><a href="/#keepsakes">Browse all keepsakes</a><a href={mapPath}>↗ {experience.openMap}</a>{admin&&<a href="/admin/orders">Order & fulfillment console</a>}<button type="button" onClick={signOut}>Log out</button></div></aside>
}
