"use client";
import {useEffect,useRef} from "react";
export const tourSteps=[
 {section:"Overview",title:"Overview",text:"See your map and setup progress at a glance. View Guest Map and Open QR Code take you to the guest experience. Before your event, complete the Get Your Map Ready checklist."},
 {section:"Our Story",title:"Our Chronological Story",text:"Tell your relationship story through dated milestones: how you met, your first date, trips, engagement, major moments, and your wedding. Guest memories can join your story."},
 {section:"Travel Journal",title:"Travel Journal",text:"Add dream destinations and future trips, rank places, and update your journey from Want to Go to Planning and Visited. Expand Guest Recommendations to review destinations from guests and add them to your journal."},
 {section:"QR Code",title:"QR Code",text:"Access your event QR code and printable materials. Guests scan the code to explore and contribute to your Memento Map."},
 {section:"Resources",title:"Resources",text:"Review the Guest Participation guide before your event. A QR code alone may not generate strong participation: use multiple locations, a DJ or emcee announcement, and a guest reminder."},
 {section:"Keepsake",title:"Keepsake",text:"After your event, prepare and download your completed Memento Map to print or frame as a physical keepsake."},
 {section:"Event Details",title:"Wedding Details",text:"Configure couple names, venue, event details, welcome message, typography, and the other available map customization settings."},
 {section:"My Account",title:"My Account",text:"Review your account and purchases, including your currently selected Memento Map plan."},
];
export function Optimize({focusGuide=false,onStart,onViewed}:{focusGuide?:boolean;onStart:()=>void;onViewed:()=>Promise<void>}){
 const guide=useRef<HTMLElement>(null),viewed=useRef(false);
 useEffect(()=>{if(focusGuide)guide.current?.scrollIntoView({block:"start"})},[focusGuide]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)&&!viewed.current){viewed.current=true;void onViewed()}},{threshold:0.1});if(guide.current)observer.observe(guide.current);return()=>observer.disconnect()},[onViewed]);
 return <div className="optimizeResources"><section className="panel optimizeIntro"><small>YOUR RESOURCE CENTER</small><h2>Make every guest part of the story.</h2><p>Prepare your map with confidence, encourage contributions, and keep the memories together.</p><button className="button gold" onClick={onStart}>Start Guided Walkthrough →</button></section><section className="panel participationGuide" id="guest-participation" ref={guide}><small>BEFORE YOUR EVENT</small><h2>Guest Participation</h2><p>A few reminders throughout your celebration can make a big difference.</p><a href="/brand/guest-participation-guide.png" target="_blank" rel="noreferrer">Open full-size participation guide ↗</a><img src="/brand/guest-participation-guide.png" alt="How to Get More Guests to Participate: place QR codes in multiple areas; ask your DJ or emcee to make an announcement; mention Memento Map more than once; send a guest text reminder; ask your wedding party or close family to help."/><p><b>Recommended setup:</b> QR codes in multiple locations + one DJ or emcee announcement + one guest reminder.</p><ol className="participationTips"><li>Place QR codes at guest tables, the welcome area, bar, and keepsake table.</li><li>Ask your DJ or emcee to invite guests to scan and contribute.</li><li>Mention Memento Map during cocktail hour, dinner, speeches, and reception.</li><li>Include a Memento Map link in an event-day guest text reminder.</li><li>Ask the wedding party or close family to help remind guests.</li></ol></section><section className="panel"><small>KEEP EXPLORING</small><h3>More ways to make it yours</h3><p>Return to this resource center for setup guidance and future optimization resources.</p></section></div>
}
export function DashboardTour({index,onMove,onExit,onFinish,mandatory=false,saving=false,error=""}:{index:number;onMove:(index:number)=>void;onExit:()=>void;onFinish?:()=>void;mandatory?:boolean;saving?:boolean;error?:string}){
 const panel=useRef<HTMLElement>(null),complete=index===tourSteps.length,step=tourSteps[index];
 useEffect(()=>{panel.current?.focus({preventScroll:true});if(step)document.querySelector(`[data-tour-nav="${step.section}"]`)?.scrollIntoView({block:"nearest",inline:"center"});document.querySelector(".dashMain header")?.scrollIntoView({block:"start"});const targets=step?.section==="Overview"?document.querySelectorAll('.welcome a,.welcome button,.onboardingChecklist'):step?.section==="Resources"?document.querySelectorAll('.participationGuide'):document.querySelectorAll('.dashMain > .panel,.travelJournal,.storyWorkspace');targets.forEach(target=>target.classList.add('tourFeatureHighlight'));return()=>targets.forEach(target=>target.classList.remove('tourFeatureHighlight'))},[index,step]);
 return <section className="dashboardTour" ref={panel} tabIndex={-1} aria-label="Guided dashboard walkthrough" onKeyDown={event=>{if(event.key==="Escape"&&!mandatory)onExit()}}><small>{complete?"WALKTHROUGH COMPLETE":`STEP ${index+1} OF ${tourSteps.length}`}</small><h2>{complete?"You’ve finished the tour!":step.title}</h2><p>{complete?"You’re ready to prepare your Memento Map. Complete your readiness checklist and review the participation guide before your event.":step.text}</p>{mandatory&&!complete&&<p className="requiredTourNote">Complete this quick walkthrough to unlock your dashboard and start adding memories and places.</p>}{error&&<p role="alert" className="authError">{error}</p>}<div className="buttonRow"><button className="button light" disabled={index===0||saving} onClick={()=>onMove(index-1)}>Back</button>{!complete&&<button className="button gold" onClick={()=>onMove(index+1)}>Next →</button>}{(complete||!mandatory)&&<button className="button light" disabled={saving} onClick={complete?onFinish||onExit:onExit}>{saving?"Saving…":complete?"Finish":"Exit Walkthrough"}</button>}</div></section>
}
