"use client";
import {useState,type FormEvent} from "react";
import {getSupabaseBrowserClient} from "../../../lib/supabase";
import {LocationSearch} from "../../map/[slug]/location-search";
export type StoryMemory={id:string;title:string;story:string;category:string;contributor_name:string;sort_date:string;date_value:string|null;approximate_date_label:string|null;visibility:"private"|"link"|"public";status:"pending"|"published"|"private"|"rejected";destination?:{location_name:string;latitude:number;longitude:number}|null};

// Edits the existing record in place; media and map relationships remain attached.
export function StoryMemoryEditor({mapId,entry,onSaved,onClose}:{mapId:string;entry:StoryMemory;onSaved:(entry:StoryMemory)=>void;onClose:()=>void}){
 const [form,setForm]=useState({title:entry.title,story:entry.story,date:entry.date_value||entry.sort_date,visibility:entry.visibility,status:entry.status}),[location,setLocation]=useState(entry.destination),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{
  const client=getSupabaseBrowserClient();if(!client)throw new Error("Account service is unavailable.");let destinationId: string|undefined;
  if(location&&(location.latitude!==entry.destination?.latitude||location.longitude!==entry.destination?.longitude||location.location_name!==entry.destination?.location_name)){
   const normalized=location.location_name.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();const found=await client.from("destinations").select("id").eq("wedding_id",mapId).eq("normalized_location_name",normalized).maybeSingle();if(found.error)throw found.error;
   if(found.data)destinationId=found.data.id;else{const created=await client.from("destinations").insert({wedding_id:mapId,normalized_location_name:normalized,...location}).select("id").single();if(created.error)throw created.error;destinationId=created.data.id}
  }
  const dateChanged=form.date!==(entry.date_value||entry.sort_date),result=await client.from("timeline_entries").update({title:form.title,story:form.story,visibility:form.visibility,status:form.visibility==="private"&&form.status==="published"?"private":form.status,...(dateChanged?{date_value:form.date,sort_date:form.date,date_precision:"exact",approximate_date_label:null}:{}),...(destinationId?{destination_id:destinationId}:{}),updated_at:new Date().toISOString()}).eq("id",entry.id).eq("wedding_id",mapId).select("*,destination:destinations(id,location_name,latitude,longitude)").single();if(result.error)throw result.error;onSaved(result.data as unknown as StoryMemory);onClose();
 }catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
 return <form className="storyMemoryReview" onSubmit={save}><h4>Edit saved chapter</h4><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Date<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Location<LocationSearch value={location?.location_name||""} onSelect={place=>setLocation({location_name:place.name,latitude:place.lat,longitude:place.lng})}/></label><label>Story<textarea required value={form.story} onChange={e=>setForm({...form,story:e.target.value})}/></label><label>Visibility<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as StoryMemory["visibility"]})}><option value="private">Owner only</option><option value="link">Anyone with the map link</option><option value="public">Public</option></select></label><label>Review status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as StoryMemory["status"]})}><option value="published">Approved</option><option value="pending">Awaiting review</option><option value="private">Private</option><option value="rejected">Rejected</option></select></label><button className="button gold" disabled={busy}>{busy?"Saving…":"Save chapter"}</button><button type="button" className="button light" onClick={onClose}>Cancel</button>{error&&<p role="alert">{error}</p>}</form>
}
