import {AccountLink} from "../../account-link";
import {notFound,permanentRedirect} from "next/navigation";
import Image from "next/image";
import {CELEBRATIONS,NEXT_CHAPTER_SCENARIO_SLUGS,celebrationBySlug} from "../../../lib/celebrations";

export function generateStaticParams(){return CELEBRATIONS.filter(item=>!NEXT_CHAPTER_SCENARIO_SLUGS.includes(item.slug as typeof NEXT_CHAPTER_SCENARIO_SLUGS[number])).map(item=>({slug:item.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const item=celebrationBySlug((await params).slug);return item?{title:`${item.name} keepsakes`,description:item.intro,alternates:{canonical:`/celebrations/${item.slug}`}}:{} }

export default async function CelebrationPage({params}:{params:Promise<{slug:string}>}){const slug=(await params).slug;if(NEXT_CHAPTER_SCENARIO_SLUGS.includes(slug as typeof NEXT_CHAPTER_SCENARIO_SLUGS[number]))permanentRedirect("/celebrations/next-chapter");const item=celebrationBySlug(slug);if(!item)notFound();return <main className="celebrationExperiencePage"><nav><a href="/" className="houseBrand"><Image src="/brand/memento-house-logo.webp" alt="" width={72} height={72}/><span>Memento House<small>Made for the moment. Kept for a lifetime.</small></span></a><a href="/#celebrations">All celebrations</a><div className="mobileAccountAccess"><AccountLink mobile/></div></nav><header><div><span className="eyebrow">{item.status} · {item.name}</span><h1>{item.headline}</h1><p>{item.intro}</p><a className="button gold" href="#collection">{item.status==="Available now"?"Explore the collection →":"Join the early-access list →"}</a></div><Image src={({"celebration-of-life":"map-celebration-of-life-hero","events-communities":"map-events-hero","next-chapter":"map-next-chapter-hero"} as Record<string,string>)[item.slug]?`/brand/${({"celebration-of-life":"map-celebration-of-life-hero","events-communities":"map-events-hero","next-chapter":"map-next-chapter-hero"} as Record<string,string>)[item.slug]}.webp`:`/brand/celebrations/${item.slug}-1.webp`} alt={`${item.name} Memento House celebration experience`} width={1200} height={1320} sizes="(max-width: 900px) 100vw, 48vw" priority/></header><section className="celebrationStory"><Image src={({"celebration-of-life":"map-celebration-of-life-hero","events-communities":"map-events-hero","next-chapter":"map-next-chapter-hero"} as Record<string,string>)[item.slug]?`/brand/${({"celebration-of-life":"map-celebration-of-life-hero","events-communities":"map-events-hero","next-chapter":"map-next-chapter-hero"} as Record<string,string>)[item.slug]}.webp`:`/brand/celebrations/${item.slug}-2.webp`} alt={`Guests creating a ${item.name.toLowerCase()} keepsake together`} width={1200} height={1320} sizes="(max-width: 900px) 100vw, 48vw"/><div><span className="eyebrow">Made together</span><h2>The celebration becomes part of the keepsake.</h2><p>Each experience is designed to give guests a clear, meaningful way to participate. They add the words, places, stories, and messages that could only come from the people who were there.</p><ul>{item.moments.map(moment=><li key={moment}>{moment}</li>)}</ul></div></section><section className="celebrationProducts" id="collection"><span className="eyebrow">Experiences for {item.name.toLowerCase()}</span><h2>Choose what you want everyone to help create.</h2><div>{item.products.map(product=><a key={product.name} href={product.href}><h3>{product.name}</h3><p>{product.description}</p><span>{item.status==="Available now"?"Explore this experience →":"Tell me when it launches →"}</span></a>)}</div></section><footer><a href="/contact">Questions or a custom celebration? Talk with us →</a></footer></main>}
