import {expect,test,type Page} from "@playwright/test";

const email=process.env.E2E_ADMIN_EMAIL,password=process.env.E2E_ADMIN_PASSWORD,weddingId=process.env.E2E_WEDDING_ID;
async function login(page:Page){await page.goto("/login");await page.getByLabel("Email").fill(email!);await page.getByLabel("Password").fill(password!);await Promise.all([page.waitForURL(/\/(account|admin|dashboard)/),page.getByRole("button",{name:/Sign in/}).click()])}
async function api(page:Page,path:string,method="GET",body?:unknown){return page.evaluate(async({path,method,body})=>{const raw=Object.entries(localStorage).find(([,value])=>value.includes("access_token"))?.[1];if(!raw)throw new Error("Supabase browser session was not found");const parsed=JSON.parse(raw),token=parsed.access_token||parsed?.[0]?.access_token;const response=await fetch(path,{method,headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});return{status:response.status,data:await response.json().catch(()=>({}))}}, {path,method,body})}
async function purchase(page:Page,product:string,tier:string){const result=await api(page,"/api/admin/test-purchase","POST",{product,tier});expect(result.status).toBe(200);expect(result.data.order.id).toBeTruthy();return result.data.order.id as string}

test("@public location search is same-origin and returns coordinates",async({request})=>{const response=await request.get("/api/location-search?q=Cleveland%20Ohio");expect(response.ok()).toBeTruthy();const data=await response.json();expect(data.places.length).toBeGreaterThan(0);expect(Number.isFinite(data.places[0].lat)).toBeTruthy()});

test.describe.serial("@stateful verified commerce and fulfillment lifecycle",()=>{
 test.skip(!email||!password,"Set E2E_ADMIN_EMAIL and E2E_ADMIN_PASSWORD for authenticated lifecycle tests.");
 let mapOrder:string,boardOrder:string,bespokeOrder:string;
 test.beforeEach(async({page})=>login(page));
 test("map purchase creates an entitlement and confirmation event",async({page})=>{mapOrder=await purchase(page,"map","timeline-plus");const result=await api(page,`/api/admin/orders?id=${mapOrder}`);expect(result.data.order.entitlements).toContainEqual(expect.objectContaining({entitlement:"map_timeline_plus",status:"active"}));expect(result.data.order.events).toContainEqual(expect.objectContaining({event_type:expect.stringMatching(/order_confirmation_(sent|email_failed)/)}))});
 test("signature board purchase creates physical fulfillment",async({page})=>{boardOrder=await purchase(page,"unity","signature-board");const result=await api(page,`/api/admin/orders?id=${boardOrder}`);expect(result.data.order.fulfillment_workflow).toBe("custom_print")});
 test("bespoke physical purchase creates a questionnaire",async({page})=>{bespokeOrder=await purchase(page,"deck","bespoke");const result=await api(page,`/api/admin/orders?id=${bespokeOrder}`);expect(result.data.order.questionnaires[0].questionnaire_type).toBe("deck_bespoke")});
 test("questionnaire submission advances the bespoke order",async({page})=>{const result=await api(page,"/api/questionnaire","PUT",{orderId:bespokeOrder,submit:true,answers:{palette:"Warm ivory and gold",prompt_requests:"Family stories and adventures",topic_categories:"Travel, family, future"}});expect(result.status).toBe(200);expect(result.data.questionnaire.status).toBe("submitted")});
 test("proof upload and customer approval advance production",async({page})=>{const upload=await page.evaluate(async orderId=>{const raw=Object.entries(localStorage).find(([,value])=>value.includes("access_token"))?.[1],parsed=JSON.parse(raw!),token=parsed.access_token||parsed?.[0]?.access_token,form=new FormData();form.set("orderId",orderId);form.set("file",new File(["proof image"],"proof.png",{type:"image/png"}));const response=await fetch("/api/admin/proofs",{method:"POST",headers:{authorization:`Bearer ${token}`},body:form});return{status:response.status,data:await response.json()}},bespokeOrder);expect(upload.status).toBe(200);const approval=await api(page,"/api/proof-response","POST",{proofId:upload.data.proof.id,decision:"approved",feedback:"APPROVE"});expect(approval.status).toBe(200);expect(approval.data.orderStatus).toBe("in_production")});
 test("shipping records tracking and a notification outcome",async({page})=>{for(const status of ["proof_ready","awaiting_customer_approval","in_production","ready_to_ship"])await api(page,"/api/admin/orders","PATCH",{id:boardOrder,order_status:status});await api(page,"/api/admin/orders","PATCH",{id:boardOrder,order_status:"shipped",shipping_carrier:"E2E Carrier",tracking_number:"E2E-123",tracking_url:"https://example.com/track/E2E-123"});const order=await api(page,`/api/admin/orders?id=${boardOrder}`);expect(order.data.order.tracking_number).toBe("E2E-123");expect(order.data.order.events).toContainEqual(expect.objectContaining({event_type:"admin_transition",to_status:"shipped"}))});
 test("refund revokes entitlement and queued fulfillment",async({page})=>{const refund=await api(page,"/api/admin/refunds","POST",{id:mapOrder,reason:"Automated lifecycle verification"});expect(refund.status).toBe(200);const result=await api(page,`/api/admin/orders?id=${mapOrder}`);expect(result.data.order.payment_status).toBe("refunded");expect(result.data.order.entitlements).toContainEqual(expect.objectContaining({status:"revoked"}))});
});

test("@stateful guest recommendation, memory publication, and rate limiting",async({request})=>{test.skip(!weddingId,"Set E2E_WEDDING_ID to a disposable active test wedding.");const anonymousId=crypto.randomUUID(),startedAt=Date.now()-3000,base={weddingId,anonymousId,startedAt,website:"",place:"E2E Test Place",guest:`E2E ${Date.now()}`,lat:41.4993,lng:-81.6944};const first=await request.post("/api/contribution",{data:{...base,contributionType:"recommendation",message:"A verified automated recommendation",category:"Adventure"}});expect(first.status()).toBe(200);for(let index=0;index<3;index++)await request.post("/api/contribution",{data:{...base,place:`E2E Test Place ${index}`,guest:`${base.guest}-${index}`,message:"Another verified recommendation"}});const limited=await request.post("/api/contribution",{data:{...base,place:"E2E Rate Limited",guest:`${base.guest}-limited`,message:"This request should be limited"}});expect(limited.status()).toBe(429);const memory=await request.post("/api/timeline-memory",{multipart:Object.fromEntries(Object.entries({...base,title:"Automated guest memory",story:"This memory is published immediately by the acceptance test.",date:"2025-06-14"}).map(([name,value])=>[name,String(value)]))});expect(memory.status()).toBe(200);expect((await memory.json()).entry.title).toBe("Automated guest memory")});
