"use client";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import {getSupabaseBrowserClient} from "../../../lib/supabase";

export default function TestSuccess(){
 const id=useSearchParams().get("order")||"",[data,setData]=useState<any>({status:"loading"});
 useEffect(()=>{let stopped=false;async function load(){if(!id){setData({status:"error",message:"The test order reference is missing."});return}const client=getSupabaseBrowserClient(),session=(await client?.auth.getSession())?.data.session;if(!session){location.href=`/login?next=${encodeURIComponent(`/order/test-success?order=${id}`)}`;return}const response=await fetch(`/api/admin/orders?id=${encodeURIComponent(id)}`,{headers:{authorization:`Bearer ${session.access_token}`}}),json=await response.json().catch(()=>({}));if(!stopped)setData(response.ok?{status:"ready",...json}:{status:"error",message:json.error||"The test order could not be loaded."})}load();return()=>{stopped=true}},[id]);
 const order=data.order,bespoke=order?.tier==="bespoke",nextSteps=order?.product==="map"?["Open the test account and confirm the correct map tier is active.","Complete the couple and venue setup as the customer.","Test the guest link, QR code, map layers, and export experience."]:order?.product==="deck"?(bespoke?["Open the Bespoke creative-direction questionnaire.","Complete the custom visual and story direction.","Move the order through proof, approval, production, and shipping in the admin console."]:["Open the saved deck customization attached to this order.","Review the names, date, photo, style, and selected tier.","Move the order through proof, approval, production, and shipping in the admin console."]):(bespoke?["Open the Bespoke creative-direction questionnaire.","Complete palette, typography, artwork, and wording direction.","Move the order through proof, approval, production, and shipping in the admin console."]:["Open the finished Unity design attached to this order.","Download the customer-created board file and review it for production.","Move the order through proof, approval, production, and shipping in the admin console."]);
 return <main className="orderPage"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><section><div className="eyebrow">Private admin test · no charge</div>{data.status==="loading"?<><h1>Confirming the simulated order.</h1><p role="status">Loading the fulfillment record created by the payment bypass…</p></>:data.status==="ready"?<><h1>Your test order was created.</h1><p>This followed the real post-payment fulfillment path without charging a card or sending a Stripe receipt.</p><dl className="testOrderSummary"><div><dt>Order</dt><dd>{order.id}</dd></div><div><dt>Product</dt><dd>{order.catalog_key||`${order.product}:${order.tier}`}</dd></div><div><dt>Customer</dt><dd>{order.customer_email}</dd></div><div><dt>Status</dt><dd>{order.order_status}</dd></div></dl><h2>Continue the customer journey</h2><ol className="successSteps">{nextSteps.map((step:string)=><li key={step}>{step}</li>)}</ol><div className="buttonRow">{order.questionnaires?.length>0&&<a href={`/account/questionnaire?order=${order.id}`} className="button gold">Open Bespoke questionnaire →</a>}{order.product==="map"&&<a href="/dashboard" className="button light">Open test account</a>}<a href="/admin/orders" className="button light">Open fulfillment console</a></div></>:<><h1>We could not load this test order.</h1><p>{data.message}</p><div className="buttonRow"><a href="/admin/orders" className="button gold">Open fulfillment console →</a><a href="/" className="button light">Return home</a></div></>}</section></main>
}
