import assert from "node:assert/strict";
import test from "node:test";
import {PRODUCT_CATALOG,resolveCatalog} from "../lib/product-catalog.ts";
import {assertTransition,canTransition,initialPaidState} from "../lib/order-domain.ts";
import {hasCapability} from "../lib/capabilities.ts";
import {exportDimensions,geographicBounds,MAP_STYLES} from "../lib/map-export.ts";
import {readFile} from "node:fs/promises";
import {deckCustomizationSchema,mapContributionSchema,summarizeDeckCustomization,timelineChapterSchema} from "../lib/domain-schemas.ts";

test("catalog has unique authoritative product/tier keys",()=>{assert.equal(PRODUCT_CATALOG.length,9);assert.equal(new Set(PRODUCT_CATALOG.map(x=>x.key)).size,PRODUCT_CATALOG.length);for(const item of PRODUCT_CATALOG){assert.ok(item.stripePriceEnv);assert.ok(item.entitlement);assert.ok(item.questionnaireType);assert.ok(item.fulfillmentWorkflow);assert.ok(item.nextSteps.length)}});
test("every supported product/tier resolves and invalid pairings fail",()=>{for(const item of PRODUCT_CATALOG)assert.equal(resolveCatalog(item.productId,item.tierId).key,item.key);assert.throws(()=>resolveCatalog("map","bespoke"));assert.throws(()=>resolveCatalog("deck","unknown"));assert.throws(()=>resolveCatalog("unity","signature-board",["open-5"]))});
test("add-ons follow tier rules",()=>{assert.equal(resolveCatalog("deck","essential",["open-5"]).key,"deck:essential");assert.throws(()=>resolveCatalog("deck","bespoke",["open-5"]));assert.deepEqual(resolveCatalog("deck","bespoke").includedAddons,["open-10"])});
test("physical and digital order state machines reject invalid jumps",()=>{assert.equal(initialPaidState("digital_map",false),"account_ready");assert.equal(initialPaidState("custom_print",true),"awaiting_customer_information");assert.equal(initialPaidState("custom_print",false),"ready_for_design");assert.ok(canTransition("awaiting_customer_information","ready_for_design"));assert.ok(!canTransition("awaiting_customer_information","shipped"));assert.throws(()=>assertTransition("paid","fulfilled"))});
test("capabilities cannot be elevated by unknown browser tier",()=>{assert.ok(hasCapability("map_plus","map.travel"));assert.ok(!hasCapability("map_basic","map.travel"));assert.ok(!hasCapability("plus","map.travel"));assert.ok(!hasCapability("unknown","map.export.premium"))});
test("print export presets and fit bounds preserve expected dimensions",()=>{assert.deepEqual(exportDimensions("18x24"),{width:5400,height:7200,dpi:300});assert.deepEqual(exportDimensions("8x10","preview"),{width:600,height:750,dpi:72});const b=geographicBounds([{lng:-84.5,lat:39.1},{lng:2.35,lat:48.86}]);assert.ok(b.west<-84.5&&b.east>2.35&&b.south<39.1&&b.north>48.86);assert.deepEqual(MAP_STYLES,["atlas","states","counties","minimal","heritage","botanical","midnight"])});
test("migration contains database-level commerce uniqueness and server-only tables",async()=>{const sql=await readFile(new URL("../supabase/migrations/006_commerce_fulfillment_architecture.sql",import.meta.url),"utf8");for(const expected of ["stripe_events","orders_external_reference_key","orders_payment_intent_uidx","unique(order_id,entitlement)","questionnaires","fulfillment_jobs","order_events","reorder_couple_destinations"])assert.match(sql,new RegExp(expected.replace(/[()]/g,"\\$&"),"i"));assert.match(sql,/revoke all on public\.checkout_customizations/)});
test("canonical Deck customization survives review and fulfillment boundaries",()=>{const input={tier:"story",names:{partnerOne:"Kate",partnerTwo:"Jonah"},eventDate:"2027-10-17",eventType:"Wedding",style:"Editorial",colorPalette:"Ivory",enabledCategories:["remember","advise"],personalizedPromptEligibility:true,addons:["open-5"]},parsed=deckCustomizationSchema.parse(input),summary=summarizeDeckCustomization(parsed);assert.equal(parsed.tier,"story");assert.deepEqual(summary.find(row=>row[0]==="Couple"),["Couple","Kate + Jonah"]);assert.throws(()=>deckCustomizationSchema.parse({...input,tier:"unknown"}))});
test("timeline chapters and map contributions enforce geographic bounds",()=>{assert.ok(timelineChapterSchema.parse({title:"First date",category:"First Date",story:"Coffee",latitude:39.1,longitude:-84.5,privacy:"link",sortOrder:1}));assert.throws(()=>timelineChapterSchema.parse({title:"Invalid",category:"Trip",latitude:100,longitude:0}));assert.ok(mapContributionSchema.parse({place:"Cincinnati",category:"Guest Origin",latitude:39.1,longitude:-84.5,contributor:"A guest"}));assert.throws(()=>mapContributionSchema.parse({place:"X",category:"Guest Origin",latitude:39.1,longitude:-84.5,contributor:"A guest"}))});
test("refinement migration is additive and preserves proof versions",async()=>{const sql=await readFile(new URL("../supabase/migrations/009_refinement_reliability_and_lifecycle.sql",import.meta.url),"utf8");for(const expected of ["contribution_status","contribution_closes_at","watermarked_storage_path","superseded_by_id","customer_support_notes","assigned_to","due_at"])assert.match(sql,new RegExp(expected,"i"));assert.doesNotMatch(sql,/drop\s+table|truncate\s+table/i)});
