import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("pricing separates entitlements from type presentation",()=>{const tiers=read("lib/product-tiers.ts"),types=read("lib/memento-map-types.ts"),page=read("app/memento-map/map-pricing.tsx");assert.match(tiers,/mapTierEntitlements/);assert.match(tiers,/mapTierPresentation/);assert.match(types,/tiers:Record<MapTierId,TierCopy>/);assert.match(page,/mapTierPresentation\(type\)/);assert.match(page,/mapComparison\(type\)/)});
test("every type owns semantic pricing, examples, timeline, longevity, and SEO",()=>{const source=read("lib/memento-map-types.ts");for(const value of ["family_reunion","celebration_of_life","next_chapter","events_community","wedding"])assert.match(source,new RegExp(`${value}:\\{[\\s\\S]*?tiers:`));for(const field of ["examples","timelineLabel","longevity","categoryDescriptions","seo"])assert.match(source,new RegExp(`${field}:`));assert.doesNotMatch(source.match(/celebration_of_life:\{[\s\S]*?next_chapter:/)?.[0]||"",/relationship timeline|Want to Go|deceased.*future/i)});
test("type survives direct and cart checkout through map provisioning",()=>{for(const file of ["app/order/page.tsx","app/api/checkout/route.ts","app/api/stripe-webhook/route.ts","app/api/order-status/route.ts","lib/fulfillment.ts","lib/cart.ts","app/api/cart/checkout/route.ts","lib/cart-paid-items.ts","lib/cart-fulfillment.ts"])assert.match(read(file),/mapType|map_type/,file);assert.match(read("app/api/checkout/route.ts"),/Choose a valid Memento Map type/);assert.match(read("lib/fulfillment.ts"),/p_map_type:input\.mapType/)});
test("paid map provisioning is required before fulfillment completes",()=>{const fulfillment=read("lib/fulfillment.ts"),status=read("app/api/order-status/route.ts");assert.match(fulfillment,/provision_paid_memento_map/);assert.match(fulfillment,/did not return a map/);assert.match(status,/deliverOrderConfirmation/)});
test("umbrella requires context before package selection",()=>{const page=read("app/memento-map/page.tsx");assert.match(page,/What are you bringing together/);assert.doesNotMatch(page,/orderHref|mapTiers|venue distance|relationship timeline/)});
test("participant and dashboard use persisted type configuration",()=>{assert.match(read("app/map/[slug]/wedding-experience.tsx"),/mapTypeConfig\(wedding\?\.map_type\)/);assert.match(read("app/dashboard/dashboard.tsx"),/mapDashboardLabels\(wedding\.map_type\)/);assert.match(read("app/api/contribution/route.ts"),/mapTypeConfig\(mapType\)/)});
