import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("pricing separates entitlements from type presentation",()=>{const tiers=read("lib/product-tiers.ts"),types=read("lib/memento-map-types.ts"),page=read("app/memento-map/map-pricing.tsx");assert.match(tiers,/mapTierEntitlements/);assert.match(tiers,/mapTierPresentation/);assert.match(types,/tiers:Record<MapTierId,TierCopy>/);assert.match(page,/mapTierPresentation\(type,occasion\)/);assert.match(page,/mapComparison\(type\)/)});
test("every type owns semantic pricing, examples, timeline, longevity, and SEO",()=>{const source=read("lib/memento-map-types.ts");for(const value of ["family_reunion","celebration_of_life","next_chapter","events_community","wedding"])assert.match(source,new RegExp(`${value}:\\{[\\s\\S]*?tiers:`));for(const field of ["examples","timelineLabel","longevity","categoryDescriptions","seo"])assert.match(source,new RegExp(`${field}:`));assert.doesNotMatch(source.match(/celebration_of_life:\{[\s\S]*?next_chapter:/)?.[0]||"",/relationship timeline|Want to Go|deceased.*future/i)});
test("type survives direct and cart checkout through map provisioning",()=>{for(const file of ["app/order/page.tsx","app/api/checkout/route.ts","app/api/stripe-webhook/route.ts","app/api/order-status/route.ts","lib/fulfillment.ts","lib/cart.ts","app/api/cart/checkout/route.ts","lib/cart-paid-items.ts","lib/cart-fulfillment.ts"])assert.match(read(file),/mapType|map_type/,file);assert.match(read("app/api/checkout/route.ts"),/Choose a valid Memento Map type/);assert.match(read("lib/fulfillment.ts"),/p_map_type:input\.mapType/)});
test("paid map provisioning is required before fulfillment completes",()=>{const fulfillment=read("lib/fulfillment.ts"),status=read("app/api/order-status/route.ts");assert.match(fulfillment,/provision_paid_memento_map/);assert.match(fulfillment,/did not return a map/);assert.match(status,/deliverOrderConfirmation/)});
test("umbrella requires context before package selection",()=>{const page=read("app/memento-map/page.tsx");assert.match(page,/What are you bringing together/);assert.doesNotMatch(page,/orderHref|mapTiers|venue distance|relationship timeline/)});
test("brand homepage presents occasion-neutral keepsakes and a three-step contribution story",()=>{const page=read("app/page.tsx");assert.match(page,/Our keepsakes/);assert.match(page,/Participate[\s\S]*Contribute[\s\S]*Keep/);assert.doesNotMatch(page,/Wedding Collection|wedding collection|Explore the wedding demo|last dance/)});
test("Memento Map landing distinguishes the home outcome from downloadable files",()=>{const page=read("app/memento-map/page.tsx"),journey=read("app/memento-map/map-journey.tsx"),delivery=read("app/memento-map/export-example.tsx");assert.match(page,/See Memento Map in action/);assert.match(page,/Questions people ask before purchasing/);assert.match(journey,/Bring the story home/);assert.match(delivery,/The digital deliverable/);assert.match(delivery,/High-resolution PNG/);assert.match(delivery,/Print-ready PDF/);assert.match(delivery,/No physical print or frame is included/)});
test("Memento Map experience chooser uses a balanced visual grid",()=>{const page=read("app/memento-map/page.tsx"),css=read("app/globals.css");for(const value of ["Wedding","Family Reunion","Celebration of Life","Next Chapter","Events & Communities","Anniversary"])assert.match(page+read("lib/memento-map-types.ts"),new RegExp(value.replace("&","&(?:amp;)?")));assert.match(page,/MEMENTO_MAP_TYPE_VISUALS/);assert.match(css,/\.mapTypeDiscovery>div:last-child\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/)});
test("participant and dashboard use persisted type configuration",()=>{assert.match(read("app/map/[slug]/wedding-experience.tsx"),/mapTypeConfig\(wedding\?\.map_type,wedding\?\.map_subtype\)/);assert.match(read("app/dashboard/dashboard.tsx"),/mapDashboardLabels\(wedding\.map_type,wedding\.map_subtype\)/);assert.match(read("app/api/contribution/route.ts"),/mapTypeConfig\(mapType,wedding.map_subtype\)/)});
