import type {CardTemplate,Palette,Project,ThemeId} from './types';
export const CARD={trimW:3.5,trimH:5,bleed:.125,safe:.125,canvasW:3.75,canvasH:5.25,dpi:300,pxW:1125,pxH:1575};
export const SIGN={trimW:5,trimH:7,bleed:.125,safe:.125,canvasW:5.25,canvasH:7.25,dpi:300,pxW:1575,pxH:2175};
export const TIER_PACKAGES={
 essential:{guestQuantity:50,rareCount:0,includeDividers:false,bespokePromptCount:0,confess:false,deckCount:1},
 signature:{guestQuantity:75,rareCount:0,includeDividers:true,bespokePromptCount:0,confess:true,deckCount:1},
 story:{guestQuantity:95,rareCount:5,includeDividers:true,bespokePromptCount:10,confess:true,deckCount:1},
 bespoke:{guestQuantity:175,rareCount:8,includeDividers:true,bespokePromptCount:12,confess:true,deckCount:2}
} as const;
export const palettes:Record<string,Palette>={ivory:{background:'#f6f0e3',primary:'#171a18',accent:'#b89a5c'},sage:{background:'#f4f0e5',primary:'#36594f',accent:'#b49a62'},rose:{background:'#fff5ed',primary:'#a86669',accent:'#6f2837'},navy:{background:'#f5f0e6',primary:'#17324d',accent:'#b89a5c'},forest:{background:'#f5efe2',primary:'#173f36',accent:'#c4a97b'},burgundy:{background:'#f7f0e4',primary:'#702f3b',accent:'#b3975d'},champagne:{background:'#fbf6ea',primary:'#5c4c39',accent:'#c9ad72'},terracotta:{background:'#fbf1e7',primary:'#8f4f3c',accent:'#d29a70'},lavender:{background:'#f7f3f8',primary:'#574b68',accent:'#aaa0be'},blue:{background:'#f2f7f8',primary:'#315a68',accent:'#9abcc4'},emerald:{background:'#f4f0e7',primary:'#14513f',accent:'#d0ad62'},monochrome:{background:'#f7f7f4',primary:'#242424',accent:'#858585'},blackWhite:{background:'#ffffff',primary:'#090909',accent:'#555555'},charcoal:{background:'#ecebe8',primary:'#1d2022',accent:'#77736c'},midnight:{background:'#111827',primary:'#f8f4e9',accent:'#d1ae61'},plum:{background:'#f7f0f4',primary:'#4d263d',accent:'#b58a9f'},olive:{background:'#f3f0df',primary:'#4c5637',accent:'#aa8d54'},copper:{background:'#f8eee5',primary:'#663d2d',accent:'#bd744d'},seaGlass:{background:'#eff7f5',primary:'#285c61',accent:'#83aaa5'},dustyBlue:{background:'#f1f4f7',primary:'#3e5269',accent:'#91a5b8'},espresso:{background:'#f3e9dc',primary:'#34231d',accent:'#a5744d'},blushInk:{background:'#fff1ef',primary:'#332b2d',accent:'#c4817c'},peacock:{background:'#eef4f1',primary:'#123f46',accent:'#b28b4e'},aubergine:{background:'#f4eff3',primary:'#3d263b',accent:'#a47f98'},sandstone:{background:'#f7f0e3',primary:'#6b4e3d',accent:'#c3a070'}};
export const themes:Record<ThemeId,{label:string;className:string}>={vintage:{label:'Heirloom Collector',className:'theme-vintage'},minimal:{label:'Editorial Minimal',className:'theme-minimal'},romantic:{label:'Watercolor Romance',className:'theme-romantic'},moody:{label:'Dark Manor',className:'theme-moody'},deco:{label:'Gilded Art Deco',className:'theme-deco'},botanical:{label:'Pressed Botanical',className:'theme-botanical'},letterpress:{label:'Heritage Letterpress',className:'theme-letterpress'},regency:{label:'Regency Cameo',className:'theme-regency'},celestial:{label:'Midnight Celestial',className:'theme-celestial'},tuscan:{label:'Tuscan Estate',className:'theme-tuscan'},coastal:{label:'Coastal Vellum',className:'theme-coastal'},luxe:{label:'Modern Luxe',className:'theme-luxe'}};
export const themeColorways:Record<ThemeId,{id:string;name:string}[]>={
 vintage:[{id:'ivory',name:'Antique Ivory'},{id:'sage',name:'Archive Sage'},{id:'navy',name:'Heritage Navy'},{id:'burgundy',name:'Museum Burgundy'},{id:'espresso',name:'Sepia Album'},{id:'dustyBlue',name:'Faded Blue Album'},{id:'rose',name:'Victorian Rose'},{id:'olive',name:'Old Library Olive'},{id:'monochrome',name:'Silver Archive'}],
 minimal:[{id:'blackWhite',name:'Gallery Black & White'},{id:'charcoal',name:'Soft Charcoal'},{id:'dustyBlue',name:'Editorial Blue'},{id:'blushInk',name:'Blush & Ink'},{id:'ivory',name:'Warm Paper'},{id:'navy',name:'Museum Navy'},{id:'forest',name:'Studio Green'},{id:'plum',name:'Editorial Plum'},{id:'sandstone',name:'Quiet Sand'}],
 romantic:[{id:'rose',name:'Rose Garden'},{id:'blushInk',name:'Blushing Ink'},{id:'lavender',name:'Lilac Veil'},{id:'champagne',name:'Champagne Petal'},{id:'dustyBlue',name:'Something Blue'},{id:'sage',name:'Garden Sage'},{id:'plum',name:'Mauve Bouquet'},{id:'burgundy',name:'Claret Rose'},{id:'ivory',name:'Ivory Blossom'}],
 moody:[{id:'blackWhite',name:'Black & White Manor'},{id:'forest',name:'Evergreen Manor'},{id:'burgundy',name:'Oxblood Manor'},{id:'aubergine',name:'Aubergine Night'},{id:'navy',name:'Midnight Hall'},{id:'espresso',name:'Dark Walnut'},{id:'peacock',name:'Teal Drawing Room'},{id:'charcoal',name:'Stone Manor'},{id:'plum',name:'Dusty Gothic'}],
 deco:[{id:'blackWhite',name:'Noir Deco'},{id:'navy',name:'Sapphire & Gold'},{id:'emerald',name:'Emerald Ballroom'},{id:'burgundy',name:'Garnet Gala'},{id:'champagne',name:'Champagne Gold'},{id:'peacock',name:'Peacock Club'},{id:'aubergine',name:'Amethyst Deco'},{id:'copper',name:'Copper Age'},{id:'charcoal',name:'Silver Screen'}],
 botanical:[{id:'sage',name:'Pressed Sage'},{id:'olive',name:'Herbarium Olive'},{id:'forest',name:'Forest Specimen'},{id:'terracotta',name:'Autumn Pressing'},{id:'monochrome',name:'Graphite Botanical'},{id:'dustyBlue',name:'Blue Herbarium'},{id:'rose',name:'Pressed Rose'},{id:'sandstone',name:'Dried Meadow'},{id:'peacock',name:'Teal Conservatory'}],
 letterpress:[{id:'ivory',name:'Natural Cotton'},{id:'blackWhite',name:'Black Ink'},{id:'navy',name:'Navy Ink'},{id:'burgundy',name:'Wine Ink'},{id:'forest',name:'Pine Ink'},{id:'terracotta',name:'Clay Ink'},{id:'dustyBlue',name:'Slate Ink'},{id:'plum',name:'Plum Ink'},{id:'espresso',name:'Coffee Ink'}],
 regency:[{id:'champagne',name:'Gilded Cream'},{id:'dustyBlue',name:'Wedgewood Blue'},{id:'lavender',name:'Regency Lilac'},{id:'rose',name:'Cameo Rose'},{id:'emerald',name:'Emerald Salon'},{id:'blackWhite',name:'Ivory & Ebony'},{id:'sage',name:'Palladian Sage'},{id:'plum',name:'Royal Plum'},{id:'burgundy',name:'Claret Drawing Room'}],
 celestial:[{id:'midnight',name:'Midnight Gold'},{id:'navy',name:'Deep Constellation'},{id:'blackWhite',name:'Monochrome Sky'},{id:'aubergine',name:'Plum Eclipse'},{id:'peacock',name:'Teal Aurora'},{id:'charcoal',name:'Silver Cosmos'},{id:'burgundy',name:'Crimson Nebula'},{id:'emerald',name:'Emerald Orbit'},{id:'dustyBlue',name:'Dawn Sky'}],
 tuscan:[{id:'terracotta',name:'Terracotta Villa'},{id:'olive',name:'Olive Grove'},{id:'sandstone',name:'Sunwashed Stone'},{id:'copper',name:'Copper Sunset'},{id:'burgundy',name:'Chianti Estate'},{id:'sage',name:'Sage Courtyard'},{id:'espresso',name:'Walnut Shutters'},{id:'champagne',name:'Limestone Villa'},{id:'dustyBlue',name:'Tuscan Sky'}],
 coastal:[{id:'seaGlass',name:'Sea Glass'},{id:'dustyBlue',name:'Coastal Blue'},{id:'sandstone',name:'Dune Linen'},{id:'peacock',name:'Deep Tide'},{id:'monochrome',name:'Fog & Charcoal'},{id:'navy',name:'Harbor Navy'},{id:'sage',name:'Salt Marsh'},{id:'champagne',name:'Sunlit Shell'},{id:'blackWhite',name:'Winter Coast'}],
 luxe:[{id:'blackWhite',name:'Black Tie'},{id:'champagne',name:'Champagne Luxe'},{id:'charcoal',name:'Concrete & Ink'},{id:'emerald',name:'Emerald Luxe'},{id:'blushInk',name:'Blush Atelier'},{id:'navy',name:'Midnight Tailoring'},{id:'burgundy',name:'Bordeaux Luxe'},{id:'peacock',name:'Teal Couture'},{id:'sandstone',name:'Cashmere Neutral'}]
};
export const defaultTemplates:CardTemplate[]=[
 {id:'remember',badge:'REMEMBER',title:'Take Us Back',purpose:'Preserve the past',prompt:"What is your favorite memory involving us?",prompts:["What is your favorite memory involving us?","When did you first realize we were perfect for each other?","What is a moment with one of us you'll never forget?","What is something about one of us you hope the other always appreciates?","Take us back to a day together that still makes you smile.","What part of our story deserves to be told forever?","Where were we when you first met us as a couple?","What ordinary moment with us became unexpectedly memorable?","What song, place, or smell reminds you of us?","What is the kindest thing you have seen one of us do?","Finish this sentence: We knew it was serious when…","What wedding-day moment do you hope we always remember?"],fields:[{label:'From'}],active:true,prefix:'REM'},
 {id:'advise',badge:'ADVISE',title:'A Word to Keep',purpose:'Wisdom for marriage',prompt:"What's one rule we should always remember?",prompts:["What's one rule we should always remember?","What's the best relationship advice you've ever received?","When we're driving each other crazy, what should we remember?","What's one marriage rule worth breaking?","What small habit keeps love strong?","What should we never stop making time for?","How should we make up after a disagreement?","What is the secret to staying curious about each other?","What should we protect even when life gets busy?","What is worth splurging on together?","What lesson about love took you the longest to learn?","Give us one sentence to reread on a hard day."],fields:[{label:'From'}],active:true,prefix:'ADV'},
 {id:'predict',badge:'PREDICT',title:'The Year Is 2047…',purpose:'Imagine the future',prompt:'Where are we living, and what are we doing?',prompts:['Where are we living, and what are we doing?','Which one of us will plan the next big adventure?','What will we argue about when we are 80?','Describe our 25th anniversary.','What will our favorite weekend look like in ten years?','Who will be the first to suggest getting another pet?','What will our future home always have in it?','Which phrase will one of us say every single day?','What hobby will we unexpectedly take up together?','Where will we return to again and again?','What will still make us laugh twenty years from now?'],fields:[{label:'From'}],active:true,prefix:'PRE'},
 {id:'adventure',badge:'ADVENTURE',title:'Send Us Somewhere',purpose:'Build the bucket list',prompt:'Where is somewhere we absolutely need to go?',prompts:['Where is somewhere we absolutely need to go?','What is something everyone should do at least once?','Give us one ridiculous adventure to attempt.','Where should we travel before our fifth anniversary?','What road trip should we take together?','Name one experience worth getting out of our comfort zone for.','Plan us a perfect long weekend in one city.','What should we learn to do together?','Where should we go without making an itinerary?','What adventure sounds terrible but will make a great story?','Send us somewhere beautiful that most people overlook.','What should be the first item on our shared bucket list?'],fields:[{label:'From'}],active:true,prefix:'ADV'},
 {id:'together',badge:'TOGETHER',title:'Plan It for Us',purpose:'Create future experiences',prompt:'Plan us a date for under $50.',prompts:['Plan us a date for under $50.','What should we do on a rainy Saturday?','Give us a tradition to start.','What is one restaurant we need to try?','Plan the perfect no-phones evening for us.','What should become our annual anniversary ritual?','Design our ideal lazy Sunday.','What meal should we learn to cook together?','Give us a monthly ritual that costs nothing.','What movie should we save for our next cozy night?','Plan a date using only things already at home.','What tiny celebration should we invent?'],fields:[{label:'From'}],active:true,prefix:'TOG'},
 {id:'confess',badge:'CONFESS',title:'You Can Tell Us Now…',purpose:'Funny and personal stories',prompt:"What's something you can finally tell us now?",prompts:["What's something you can finally tell us now?","What's the funniest thing you've seen one of us do?","Who was really more nervous about this wedding?","What's something about our relationship you noticed before we did?","Which one of us is most likely to get us into trouble?","Tell us the story we will laugh about for years.","Who made the first move—really?","What is one habit the other person should be warned about?","Which one of us would survive longest on a reality show?","What harmless secret have you been keeping from us?","What did you predict about us that turned out to be right?","Settle this now: which one of us is more dramatic?"],fields:[{label:'From'}],active:true,prefix:'CON'}
];
export const demoProject:Project={version:1,info:{projectName:'Carter_Memento_Deck_2027',orderNumber:'MH-270612',customerName:'Olivia Carter',partner1:'Olivia',partner2:'James',lastName:'Carter',weddingDate:'2027-06-12',venue:'The Monastery',city:'Cincinnati',state:'Ohio',weddingYear:'2027',yearsTogether:'7',engagementDate:'2026-04-18',quote:'The best is yet to come.',funFact:'Together 7 Years',funFact2:'Met over coffee',notes:'Demo Story deck',firstMet:'A neighborhood coffee shop',firstDate:'The Cincinnati Art Museum',story:'From an accidental coffee-shop meeting to a lifetime together, our favorite story has always been the one we are writing side by side.',howMet:'They reached for the same table at a neighborhood coffee shop',favoriteCity:'Cincinnati',pets:'Smokey, their rescue dog',favoriteVacation:'A rainy week in Charleston',college:'University of Cincinnati',sportsTeams:'FC Cincinnati and the Bengals',insideJokes:'The missing left sock',hobbies:'Museum days, cooking, and hiking',proposalLocation:'Ault Park overlook',favoriteRestaurant:'Sotto'},photo:{dataUrl:'',width:0,height:0,zoom:1,x:0,y:0,rotation:0},templates:defaultTemplates,settings:{tier:'story',theme:'vintage',paletteId:'sage',customPalette:palettes.sage,showBranding:true,numbering:'simple',writingLines:'light',guestQuantity:95,quantities:{remember:16,advise:16,predict:16,adventure:16,together:16,confess:15},showGuides:false,includePrinterGuides:false,proofWatermark:true,experienceMode:'mixed',rareCount:5,includeDividers:true,includeOpenOnAddOn:true,bespokePromptCount:10,fonts:{display:'Cormorant Garamond',body:'Georgia',label:'Arial'}},delayedCards:[{title:'OPEN ON YOUR FIRST ANNIVERSARY',prompt:'Write something you hope we remember about this first year.',active:true},{title:'OPEN WHEN YOU BUY YOUR NEXT HOME',prompt:'What do you hope fills the rooms of our future home?',active:true},{title:'OPEN WHEN YOU NEED A DATE IDEA',prompt:'Give us one simple plan that can rescue an ordinary night.',active:true},{title:'OPEN AFTER YOUR FIRST BIG ARGUMENT',prompt:'Remind us what is worth choosing again.',active:true},{title:'OPEN ON YOUR 10TH ANNIVERSARY',prompt:'Write something you want us to remember ten years from today.',active:true}],instructionText:'1. Pick a category that speaks to you.\n2. Draw a Memento from that stack.\n3. Share your memory, prediction, wisdom, adventure, or confession.\n4. Sign it and add it to our collection.',signText:'Pick a card.\n\nShare a memory, prediction, piece of wisdom, adventure, or confession.\n\nSign it and add it to our Memento Deck.',updatedAt:new Date().toISOString()};
