import {LegalPage} from "../legal-page";
export const metadata={title:"Privacy policy",description:"How Memento House collects, uses, shares, retains, and protects couple, customer, and guest information.",alternates:{canonical:"/privacy"}};
export default function Privacy(){return <LegalPage eyebrow="Your privacy" title="Privacy policy" updated="August 31, 2026">
<p>This policy explains how Memento House handles personal information when people browse our site, create an account, purchase or customize a keepsake, contribute to a shared experience, or contact us.</p>
<h2>Who we are</h2><p>Memento House is operated from Cincinnati, Ohio, United States. For privacy questions, rights requests, or the operator’s current postal contact address, email <a href="mailto:jonahnr@gmail.com">jonahnr@gmail.com</a>.</p>
<h2>Scope</h2><p>This policy applies to mementohouse.com, customer accounts, Memento Map and Timeline experiences, customization studios, questionnaires, proof review, order fulfillment, and guest contribution forms. Third-party sites reached from our service have their own policies.</p>
<h2>Information couples and customers provide</h2><p>This can include names, email address, account details, celebration date and venue, shipping and billing details, couple story information, map locations, relationship words, prompts, customization choices, questionnaire responses, proof feedback, messages, and uploaded photos.</p>
<h2>Information guests provide</h2><p>Guests may provide a display name, origin, recommendation, memory, date, location, written message, reaction, or optional photo. A guest account is not normally required. Guests should not submit sensitive information or content they do not have permission to share.</p>
<h2>Information collected automatically</h2><p>We and our providers may process IP address, device and browser information, timestamps, requested pages, referral information, session identifiers, security signals, diagnostic logs, and checkout or email delivery events to operate and protect the service.</p>
<h2>Purposes and lawful bases</h2><div className="legalTable"><div><b>Purpose</b><b>Information</b><b>Basis where applicable</b></div><div><span>Provide accounts, purchases, personalization, maps, proofs, and fulfillment</span><span>Account, order, customization, location, and content data</span><span>Contract or requested pre-contract steps</span></div><div><span>Protect guests, customers, and the service</span><span>Technical, submission, and security records</span><span>Legitimate interests and legal obligations</span></div><div><span>Send transactional communications</span><span>Email, order, proof, and shipping data</span><span>Contract and legitimate interests</span></div><div><span>Optional marketing or analytics</span><span>Contact and usage information</span><span>Consent where required; otherwise legitimate interests with controls</span></div><div><span>Accounting, disputes, and compliance</span><span>Order, payment, communication, and audit records</span><span>Legal obligations and legitimate interests</span></div></div>
<h2>Payment processing</h2><p>Stripe processes card and payment information. Memento House does not store complete payment-card details. Stripe may process billing information, fraud signals, and transaction records under its own privacy terms.</p>
<h2>Hosting, database, storage, and subprocessors</h2><p>We use Vercel for hosting and application delivery, Supabase for authentication, database, and file storage, Stripe for payments, Resend for transactional email, and mapping or geocoding providers for place search and map display. They process information as needed to provide their services, subject to their agreements and applicable law.</p>
<h2>Map visibility and sharing</h2><p>Couples receive a unique guest link and QR code. Anyone with that link may be able to view information the couple has chosen to share and submit a contribution while submissions are open. Treat the link as shareable rather than secret. Couples can manage visible content and request removal of unwanted submissions.</p>
<h2>Cookies and analytics</h2><p>Essential browser storage keeps sessions active, preserves customization progress, limits repeated reactions, and supports security. If non-essential analytics or advertising tools are introduced, we will provide notice and consent controls where required.</p>
<h2>International transfers</h2><p>Our providers may process information in the United States and other countries. Where law requires it, transfers use recognized safeguards such as contractual protections or an applicable adequacy mechanism.</p>
<h2>Retention</h2><p>We retain account and digital-keepsake information while the account or experience is active; guest contributions while the related experience is active or until removed; customization, proof, fulfillment, and support records as needed to complete and support an order; security logs for a limited diagnostic and abuse-prevention period; and transaction records for required tax, accounting, chargeback, and legal periods. Some transaction records may remain after a deletion request where required.</p>
<h2>Security</h2><p>We use access controls, authenticated customer and administrative areas, encrypted network connections, signed file links, provider security controls, and abuse-prevention measures. No online system is risk-free, so use a unique password and share guest links thoughtfully.</p>
<h2>Your choices and rights</h2><p>Depending on where you live, you may ask to access, correct, delete, restrict, or receive a copy of personal information; object to certain processing; withdraw consent; close an account; or appeal a privacy decision. Couples can request removal of a guest contribution. We may verify identity before acting.</p>
<h2>EU and EEA rights</h2><p>People in the European Economic Area may have the rights described above, including the right to object to legitimate-interest processing and lodge a complaint with their local data-protection supervisory authority.</p>
<h2>California rights</h2><p>California residents may request categories and specific pieces of information, sources, purposes, and disclosures, and may request correction or deletion subject to exceptions. We do not sell personal information for money. If our practices constitute “sharing” for cross-context behavioral advertising, we will provide the required choice.</p>
<h2>Children and minors</h2><p>The service is intended for adults and is not directed to children under 13. Do not intentionally submit a child’s personal information without authority from a parent or guardian. Contact us to request removal.</p>
<h2>Deletion and account closure</h2><p>Email us from the account or order email and describe what should be closed or removed. Closing an account may make purchased digital experiences unavailable. We will explain any information that must be retained.</p>
<h2>Changes, contact, and complaints</h2><p>We may update this policy as products and legal requirements evolve. Material changes will be communicated when appropriate. Contact us with concerns; where applicable, you may also complain to the privacy or data-protection authority in your jurisdiction.</p>
</LegalPage>}
