import {withWeddingStory} from "../../../lib/wedding-story";
import {createClient} from "@supabase/supabase-js";
import {resolveMapTier} from "../../../lib/map-entitlement";
import {supabaseServerConfig} from "../../../lib/server-config";
const mediaFields="id,media_type,status,public_url,playback_url,thumbnail_url,cloudflare_uid,alt_text,duration_seconds,timeline_entry_id,story_location_id,error_message";
export async function GET(request:Request){
 const slug=new URL(request.url).searchParams.get("slug")||"",{url,serviceRoleKey:key}=supabaseServerConfig();if(!slug)return Response.json({error:"Map slug is required."},{status:400});if(!url||!key)return Response.json({error:"Timeline service is unavailable."},{status:503});
 const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),wedding=await admin.from("weddings").select("id,owner_user_id,partner_one_name,partner_two_name,wedding_date").eq("slug",slug).eq("status","active").maybeSingle();if(wedding.error)return Response.json({error:"The map could not be loaded."},{status:503});if(!wedding.data)return Response.json({error:"Map not found."},{status:404});const user=await admin.auth.admin.getUserById(wedding.data.owner_user_id),tier=await resolveMapTier(admin,wedding.data.owner_user_id,user.data.user?.user_metadata,user.data.user?.email);if(user.error)return Response.json({error:"Map access could not be checked."},{status:503});if(tier!=="timeline-plus")return Response.json({error:"Timeline access is unavailable."},{status:403});
 const[entries,storyRows]=await Promise.all([admin.from("timeline_entries").select("id,date_value,approximate_date_label,sort_date,title,category,story,contributor_name,visibility,status,destination_id").eq("wedding_id",wedding.data.id).eq("status","published").in("visibility",["public","link"]).order("sort_date"),admin.from("story_locations").select("id,title,story_type,description,image_url,location_name,latitude,longitude,event_date,sort_order").eq("wedding_id",wedding.data.id).order("sort_order")]);if(entries.error||storyRows.error)return Response.json({error:"The timeline could not be refreshed."},{status:503});
 const ids=(entries.data||[]).map(entry=>entry.id),storyIds=(storyRows.data||[]).map(row=>row.id),destinationIds=(entries.data||[]).map(entry=>entry.destination_id).filter(Boolean),mediaOr=[ids.length?`timeline_entry_id.in.(${ids.join(",")})`:"",storyIds.length?`story_location_id.in.(${storyIds.join(",")})`:""].filter(Boolean).join(","),[photos,destinations,media]=await Promise.all([ids.length?admin.from("timeline_photos").select("entry_id,public_url,alt_text").in("entry_id",ids):Promise.resolve({data:[],error:null}),destinationIds.length?admin.from("destinations").select("id,location_name,latitude,longitude").in("id",destinationIds):Promise.resolve({data:[],error:null}),mediaOr?admin.from("media_assets").select(mediaFields).in("status",["uploading","processing","ready","failed"]).is("deleted_at",null).or(mediaOr):Promise.resolve({data:[],error:null})]);
 if(photos.error||destinations.error||media.error)return Response.json({error:"Timeline media could not be refreshed."},{status:503});
 const timeline=(entries.data||[]).map(entry=>({...entry,photo:(photos.data||[]).find((photo:any)=>photo.entry_id===entry.id)||null,media:(media.data||[]).filter((asset:any)=>asset.timeline_entry_id===entry.id),destination:(destinations.data||[]).find((destination:any)=>destination.id===entry.destination_id)||null})),seen=new Set(timeline.map(entry=>`${entry.title.toLowerCase()}|${entry.date_value||entry.sort_date}`)),couple=[wedding.data.partner_one_name,wedding.data.partner_two_name].filter(Boolean).join(" & ");
 const milestones=withWeddingStory(wedding.data,storyRows.data||[]).filter((row:any)=>!seen.has(`${String(row.title).toLowerCase()}|${row.event_date||`${1900+Number(row.sort_order||0)}-01-01`}`)).map((row:any)=>({id:`story-${row.id}`,date_value:row.event_date||null,approximate_date_label:row.event_date?null:"Date saved by the couple",sort_date:row.event_date||`${1900+Number(row.sort_order||0)}-01-01`,title:row.title,category:row.story_type==="Wedding Venue"?"Wedding":row.story_type||"Our Story",story:row.description||`A chapter from ${couple||"the couple"}’s story.`,contributor_name:couple||"The couple",visibility:"link",status:"published",destination_id:null,photo:row.image_url?{public_url:row.image_url,alt_text:row.title}:null,media:(media.data||[]).filter((asset:any)=>asset.story_location_id===row.id),destination:Number.isFinite(row.latitude)&&Number.isFinite(row.longitude)?{location_name:row.location_name,latitude:Number(row.latitude),longitude:Number(row.longitude)}:null}));
 return Response.json({entries:[...timeline,...milestones].sort((a,b)=>String(a.sort_date).localeCompare(String(b.sort_date)))},{headers:{"Cache-Control":"no-store"}})
}
