"use client";
import {useEffect,useRef,useState} from "react";
import {getSupabaseBrowserClient} from "../../lib/supabase";
export function DeleteExperience({id,name,onDeleted}:{id:string;name:string;onDeleted:()=>void}){
 const [stage,setStage]=useState(0),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const dialog=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(stage)dialog.current?.focus()},[stage]);
 function close(){if(busy)return;setStage(0);setConfirmation("");setError("");trigger.current?.focus()}
 async function remove(){if(confirmation!=="DELETE"||busy||stage!==2)return;setBusy(true);setError("");try{const session=(await getSupabaseBrowserClient()?.auth.getSession())?.data.session;const response=await fetch("/api/maps/delete",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({mapId:id,confirmation})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Deletion failed.");onDeleted()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
 return <><button ref={trigger} type="button" className="deleteExperience" onClick={()=>setStage(1)}>Delete experience</button>{stage>0&&<div className="confirmationBackdrop"><div ref={dialog} className="experienceConfirmation" tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={`delete-${id}`} onKeyDown={event=>{if(event.key==="Escape")close();if(event.key==="Tab"){const buttons=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}}><h2 id={`delete-${id}`}>{stage===1?"Delete this experience?":`Permanently delete “${name}”?`}</h2><p>{stage===1?"Are you sure you want to delete this experience?":"This action cannot be undone. Your map, contributions, memories, and associated media will be removed."}</p>{stage===2&&<label>Type DELETE to confirm<input autoComplete="off" value={confirmation} disabled={busy} onChange={event=>setConfirmation(event.target.value)}/></label>}{error&&<p role="alert" className="authError">{error}</p>}<div className="buttonRow"><button className="button light" disabled={busy} onClick={close}>Cancel</button>{stage===1?<button className="button gold" onClick={()=>setStage(2)}>Continue</button>:<button className="deleteExperience final" disabled={confirmation!=="DELETE"||busy} onClick={()=>void remove()}>{busy?"Deleting…":"Delete Permanently"}</button>}</div></div></div>}</>
}
