"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../lib/supabase";
const human=(value="")=>value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
export default function Account(){
 const[data,setData]=useState<any>({loading:true,orders:[]}),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const client=getSupabaseBrowserClient(),session=(await client?.auth.getSession())?.data.session;if(!session){location.href=`/login?return_to=${encodeURIComponent(location.pathname+location.search)}`;return}const response=await fetch("/api/account/orders",{headers:{authorization:`Bearer ${session.access_token}`}}),result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error||"Your orders could not be loaded.");setData((v:any)=>({...v,loading:false}))}else setData({...result,loading:false})})()},[]);
 function reviewProof(id:string){location.href=`/account/proof?id=${encodeURIComponent(id)}`}
 return <main className="orderPage accountOrdersPage"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><section className="accountPanel"><div className="eyebrow">Your Memento House account</div><h1>Your orders</h1><p>Follow each keepsake from payment through design, proofing, production, and delivery.</p>{error&&<p className="authError">{error}</p>}{data.loading&&!error&&<p>Loading your orders…</p>}<div className="customerOrderList">{data.orders?.map((order:any)=>{const proof=order.proofs?.[0];return <article className="customerOrder" key={order.id}><header><div><small>ORDER {order.id.slice(0,8).toUpperCase()}</small><h2>{human(order.catalog_key||`${order.product} ${order.tier}`)}</h2><time>{new Date(order.created_at).toLocaleDateString()}</time></div><strong>{human(order.order_status)}</strong></header><div className="orderProgress"><span className="complete">Payment received</span><span className={proof?"complete":""}>Design & proof</span><span className={["approved","in_production","ready_to_ship","shipped","delivered","completed","active"].includes(order.order_status)?"complete":""}>Production</span><span className={["shipped","delivered","completed","active"].includes(order.order_status)?"complete":""}>Delivery / activation</span></div><div className="customerOrderActions">{order.questionnaire_status==="not_started"&&<a className="button light" href={`/account/questionnaire?order=${order.id}`}>Complete questionnaire →</a>}{proof&&<button className="button gold" onClick={()=>reviewProof(proof.id)}>Review proof v{proof.version} →</button>}{order.tracking_url&&<a className="button gold" href={order.tracking_url} target="_blank" rel="noreferrer">Track shipment →</a>}<span>{order.shipping_carrier&&order.tracking_number?`${order.shipping_carrier} · ${order.tracking_number}`:"We will show tracking here as soon as it ships."}</span></div></article>})}{!data.loading&&!data.orders?.length&&<div className="emptyAccount"><h2>No orders yet</h2><p>Your purchases will appear here automatically.</p><a href="/#keepsakes" className="button gold">Explore the collection →</a></div>}</div></section></main>
}
