"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {getSupabaseBrowserClient} from "../lib/supabase";
import {friendlyAuthError} from "../lib/auth-message";
import {canonicalAuthOrigin,moveToCanonicalAuth} from "../lib/oauth-origin";

export function LoginForm({returnTo="/dashboard"}:{returnTo?:string}){
 const router=useRouter(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),oauthStarted=useRef(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const client=getSupabaseBrowserClient();if(!client){setError("Account service is not configured.");setBusy(false);return}const result=await client.auth.signInWithPassword({email,password});if(result.error){setError(friendlyAuthError(result.error.message));setBusy(false);return}router.replace(returnTo);router.refresh()}
 const google=useCallback(async()=>{if(oauthStarted.current)return;oauthStarted.current=true;if(moveToCanonicalAuth(`/login?oauth=google&return_to=${encodeURIComponent(returnTo)}`))return;const client=getSupabaseBrowserClient();if(!client){setError("Account service is not configured.");oauthStarted.current=false;return}setBusy(true);setError("");const result=await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${canonicalAuthOrigin()}/auth/callback?next=${encodeURIComponent(returnTo)}`,queryParams:{prompt:"select_account"},skipBrowserRedirect:true}});if(result.error||!result.data.url){setError(friendlyAuthError(result.error?.message||"Google did not return a sign-in URL."));setBusy(false);oauthStarted.current=false;return}location.assign(result.data.url)},[returnTo]);
 useEffect(()=>{if(new URL(location.href).searchParams.get("oauth")!=="google")return;const timer=setTimeout(()=>void google(),0);return()=>clearTimeout(timer)},[google]);
 return <form onSubmit={submit}><div className="eyebrow">Welcome back</div><h1>Your next adventure awaits.</h1><p>Sign in to manage your Memento House account and keepsakes.</p><button type="button" className="button light oauthButton" disabled={busy} onClick={()=>void google()}>Continue with Google</button><div className="authDivider"><span>or use email</span></div><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="authError" role="alert">{error}</p>}<button disabled={busy} className="button gold">{busy?"Signing in…":"Sign in →"}</button><p><a href="/forgot-password">Forgot your password?</a></p></form>
}

export function ForgotPasswordForm(){
 const[email,setEmail]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const client=getSupabaseBrowserClient();if(!client){setError("Account service is not configured.");setBusy(false);return}const result=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/account/reset-password`});if(result.error)setError(friendlyAuthError(result.error.message));else setMessage("If that email has an account, a secure reset link is on its way.");setBusy(false)}
 return <form onSubmit={submit}><div className="eyebrow">Account recovery</div><h1>Reset your password.</h1><p>We’ll email you a secure link to choose a new password.</p><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<p className="authError" role="alert">{error}</p>}{message&&<p className="authSuccess" role="status">{message}</p>}<button disabled={busy||!!message} className="button gold">{busy?"Sending…":"Send reset link →"}</button><p><a href="/login">Return to sign in</a></p></form>
}

export function SetPasswordForm({mode}:{mode:"invite"|"recovery"}){
 const router=useRouter(),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError("Passwords do not match.");return}setBusy(true);setError("");const client=getSupabaseBrowserClient();if(!client){setError("Account service is not configured.");setBusy(false);return}await client.auth.getSession();const result=await client.auth.updateUser({password});if(result.error){setError(friendlyAuthError(result.error.message));setBusy(false);return}router.replace("/dashboard");router.refresh()}
 return <form onSubmit={submit}><div className="eyebrow">{mode==="invite"?"Welcome to Memento House":"Secure your account"}</div><h1>{mode==="invite"?"Create your password.":"Choose a new password."}</h1><p>Use at least 10 characters that you do not reuse elsewhere.</p><label>New password<input required type="password" minLength={10} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input required type="password" minLength={10} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{error&&<p className="authError" role="alert">{error}</p>}<button disabled={busy} className="button gold">{busy?"Saving…":"Save password →"}</button></form>
}
