"use client";
import {useCallback,useEffect,useState} from "react";
import {formatVideoTime,type MediaAsset,type VideoUsage} from "../lib/media";
import {getSupabaseBrowserClient} from "../lib/supabase";
import {uploadTusFile} from "../lib/tus-upload";

export function MediaPlayer({asset,title}:{asset:MediaAsset;title:string}){const[play,setPlay]=useState(false);if(asset.media_type==="photo"&&asset.public_url)return <img src={asset.public_url} alt={asset.alt_text||title}/>;if(asset.status!=="ready")return <div className={`mediaState ${asset.status}`}><b>{asset.status==="failed"?"Video upload failed":"Video is processing"}</b>{asset.error_message&&<small>{asset.error_message}</small>}</div>;if(!asset.cloudflare_uid)return null;return <div className="streamPlayer">{play?<iframe src={`https://iframe.videodelivery.net/${encodeURIComponent(asset.cloudflare_uid)}?autoplay=true`} title={title} loading="lazy" allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setPlay(true)} style={asset.thumbnail_url?{backgroundImage:`url(${asset.thumbnail_url})`}:undefined}><span>▶</span><b>Play video</b></button>}</div>}

export function VideoUploader({weddingId,anonymousId="",onUploaded}:{weddingId:string;anonymousId?:string;onUploaded:(id:string)=>void}){
 const[usage,setUsage]=useState<VideoUsage|null>(null),[enabled,setEnabled]=useState<boolean|null>(null),[progress,setProgress]=useState(0),[state,setState]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void fetch(`/api/media?weddingId=${encodeURIComponent(weddingId)}`,{cache:"no-store"}).then(response=>response.ok?response.json():null).then(data=>{if(data?.usage)setUsage(data.usage);setEnabled(Boolean(data?.videoEnabled))})},[weddingId]);
 async function upload(file:File){setError("");setProgress(0);if(!file.type.startsWith("video/")){setError("Choose a video file.");return}if(file.size>500_000_000){setError("Choose a video smaller than 500 MB.");return}setState("authorizing");try{const session=(await getSupabaseBrowserClient()?.auth.getSession())?.data.session,response=await fetch("/api/media/video-authorize",{method:"POST",headers:{"Content-Type":"application/json",...(session?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({weddingId,anonymousId,fileName:file.name,mimeType:file.type,fileSize:file.size})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Video upload could not start.");setUsage(current=>current?{...current,reservedSeconds:current.reservedSeconds+data.maxDurationSeconds,remainingSeconds:data.remainingSeconds}:current);setState("uploading");await uploadTusFile(file,data.uploadUrl,setProgress);setState("processing");onUploaded(data.mediaId)}catch(reason){setState("");setError(reason instanceof Error?reason.message:"Video upload failed.")}}
 const exhausted=usage?.remainingSeconds===0||usage?.videoCount===usage?.maxVideos;
 return <div className="videoUploader">{enabled?<label><b>Add video <small>(optional)</small></b><input type="file" accept="video/*" disabled={Boolean(state)||exhausted} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/><small>Up to 60 seconds and 500 MB · resumable upload</small></label>:enabled===false?<p>Video uploads will be available after media setup is complete.</p>:<p>Checking video availability…</p>}{usage&&<p>{formatVideoTime(usage.usedSeconds)} of {formatVideoTime(usage.maxSeconds)} used{usage.reservedSeconds>0?` · ${formatVideoTime(usage.reservedSeconds)} processing`:""}</p>}{exhausted&&<p className="authError">This Memento has reached its video upload limit.</p>}{state==="authorizing"&&<p role="status">Preparing secure upload…</p>}{state==="uploading"&&<p role="status">Uploading video… {progress}%</p>}{state==="processing"&&<p role="status">Upload complete. Video is processing and will appear when ready.</p>}{error&&<p className="authError" role="alert">{error}</p>}</div>
}

export function MediaLibrary({weddingId}:{weddingId:string}){const[assets,setAssets]=useState<MediaAsset[]>([]),[usage,setUsage]=useState<VideoUsage|null>(null),[error,setError]=useState("");const load=useCallback(async()=>{const session=(await getSupabaseBrowserClient()?.auth.getSession())?.data.session;if(!session)return;const response=await fetch(`/api/media?weddingId=${encodeURIComponent(weddingId)}`,{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"}),data=await response.json();if(response.ok){setAssets(data.assets||[]);setUsage(data.usage)}},[weddingId]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);async function remove(id:string){const session=(await getSupabaseBrowserClient()?.auth.getSession())?.data.session;if(!session)return;const response=await fetch(`/api/media/${encodeURIComponent(id)}`,{method:"DELETE",headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json().catch(()=>({}));if(!response.ok){setError(data.error||"Media could not be deleted.");return}await load()}return <section className="panel mediaLibrary"><div className="panelHead"><div><small>YOUR MEDIA</small><h3>Photos and videos</h3><p>{usage?`${formatVideoTime(usage.usedSeconds)} of ${formatVideoTime(usage.maxSeconds)} of video used · ${usage.videoCount} of ${usage.maxVideos} videos`:"Loading video usage…"}</p></div></div>{assets.length?<div className="mediaGrid">{assets.map(asset=><article key={asset.id}><MediaPlayer asset={asset} title="Memento media"/><div><b>{asset.media_type==="video"?"Video":"Photo"}</b><small>{asset.status}{asset.duration_seconds?` · ${formatVideoTime(asset.duration_seconds)}`:""}</small><button className="textLink" type="button" onClick={()=>void remove(asset.id)}>Delete {asset.media_type}</button></div></article>)}</div>:<p>No uploaded media yet.</p>}{error&&<p className="authError" role="alert">{error}</p>}</section>}
