export const metadata={title:"Memento House — Meaningful moments, beautifully kept",description:"Interactive wedding keepsakes made for the moment and kept for a lifetime."};
const Logo=()=> <a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a>;
export default function Home(){return <main className="housePage">
 <nav className="houseNav"><Logo/><div><a href="#keepsakes">Our keepsakes</a><a href="#story">Our story</a><a href="/login">Sign in</a><a href="/signup" className="button small">Begin your map</a></div></nav>
 <section className="houseHero"><div className="houseHeroCopy"><div className="eyebrow">Interactive wedding keepsakes</div><h1>The people you love.<br/>Part of the moment.<br/><em>Kept forever.</em></h1><p>Memento House creates beautiful, participatory wedding experiences that turn the people, stories, and places surrounding your celebration into keepsakes you’ll return to for years.</p><div className="houseActions"><a className="button gold" href="/memento-map">Discover Memento Map →</a><a className="textLink" href="#keepsakes">Explore the collection ↓</a></div></div><div className="houseHeroArt"><div className="artCard artBack"><small>THE UNITY TILE GUESTBOOK</small><b>Two names.<br/>One story.</b><i>J + K</i></div><div className="artCard artFront"><small>MEMENTO MAP</small><b>Our Adventure<br/><em>Map</em></b><div className="artWorld"><i>✦</i><i>♥</i><i>✦</i></div><span>Jonah & Kate · 08.29.26</span></div><div className="waxSeal"><img src="/brand/memento-house-logo.webp" alt=""/></div></div></section>
 <section className="housePromise"><span>✦</span><p>Not simply décor. Each piece gives your guests a meaningful role in the celebration—and leaves you with something only they could create.</p><span>✦</span></section>
 <section className="products" id="keepsakes"><div className="productsIntro"><div className="eyebrow">The Memento House collection</div><h2>Three ways to make your guests<br/><em>part of the keepsake.</em></h2><p>Designed to be experienced during the wedding and treasured long after it.</p></div><div className="productGrid">
  <article className="productCard"><div className="productVisual mapVisual"><span className="productNumber">01</span><i className="pvPin a">✦</i><i className="pvPin b">♥</i><i className="pvPin c">✦</i><small>DIGITAL EXPERIENCE</small></div><div className="productCopy"><div><span>RECOMMENDATIONS FOR THE LIFE AHEAD</span><h3>Memento Map</h3><p>Guests recommend real places for the newlyweds to visit. Every suggestion is mapped, signed, and kept as a living record of future adventures.</p></div><div className="productLinks"><a href="/memento-map">Explore the product →</a><a href="/map/jonah-kate">View live demo ↗</a></div></div></article>
  <article className="productCard"><div className="productVisual productImage"><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Jonah and Kate personalized word-tile unity guest sheet"/><span className="productNumber">02</span><small>UNITY CEREMONY + GUESTBOOK</small></div><div className="productCopy"><div><span>TWO NAMES BECOME ONE</span><h3>The Unity Tile Guestbook</h3><p>A personalized word-tile guest sheet used during the unity ceremony. The couple places their names together to symbolize two lives joining, then guests sign the surrounding space to complete a one-of-a-kind wedding keepsake.</p></div><div className="productLinks"><a href="#notify">Request early access →</a></div></div></article>
  <article className="productCard"><div className="productVisual cardProduct"><img src="/brand/memento-deck-cover.webp" alt="Personalized couple trading card guestbook cover"/><img src="/brand/memento-deck-card.webp" alt="Example story prompt card for the couple"/><span className="productNumber">03</span><small>INTERACTIVE CARD GUESTBOOK</small></div><div className="productCopy"><div><span>DRAW A CARD. LEAVE A STORY.</span><h3>The Memento Deck</h3><p>A personalized couple trading-card guestbook. Each guest draws a card, answers a meaningful or playful prompt about the couple, signs it, and adds it to a collectible deck the newlyweds keep forever.</p></div><div className="productLinks"><a href="#notify">Request early access →</a></div></div></article>
 </div></section>
 <section className="houseStory" id="story"><div><div className="eyebrow">Why Memento House</div><h2>Guest experiences that become<br/><em>part of your story.</em></h2></div><div><p>A traditional guestbook records who attended. A Memento House keepsake captures what they gave you: a place to discover, a handwritten name beside yours, or a story only they could tell.</p><p>Elegant enough for the ceremony. Effortless for every guest. Meaningful long after the last dance.</p></div></section>
 <section className="houseCta" id="notify"><div className="eyebrow">Begin with Memento Map</div><h2>Let the people you love<br/>help map what comes next.</h2><p>Create a wedding keepsake your guests can understand in seconds and you can keep for a lifetime.</p><div><a href="/signup" className="button gold">Create your map →</a><a href="/map/jonah-kate" className="button light">Explore the demo map</a></div></section>
 <footer className="houseFooter"><Logo/><div><a href="/memento-map">Memento Map</a><a href="#keepsakes">Our keepsakes</a><a href="/login">Sign in</a></div><small>© 2026 Memento House</small></footer>
 </main>}
