export const metadata={title:"Memento House — Meaningful moments, beautifully kept",description:"Interactive wedding keepsakes made for the moment and kept for a lifetime."};
const Logo=()=> <a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a>;
export default function Home(){return <main className="housePage">
 <nav className="houseNav"><Logo/><div><a href="#keepsakes">Our keepsakes</a><a href="#story">Our story</a><a href="/login">Sign in</a><a href="#keepsakes" className="button small">Choose a keepsake</a></div><details className="mobileMenu"><summary>Menu</summary><div><a href="#keepsakes">Our keepsakes</a><a href="#story">Our story</a><a href="/login">Couple login</a></div></details></nav>
 <section className="houseHero"><div className="houseHeroCopy"><div className="eyebrow">Interactive wedding keepsakes</div><h1>The people you love.<br/>Part of the moment.<br/><em>Kept forever.</em></h1><p>Memento House creates beautiful, participatory wedding experiences that turn the people, stories, and places surrounding your celebration into keepsakes you’ll return to for years.</p><div className="houseActions"><a className="button gold" href="/memento-map">Discover Memento Map →</a><a className="textLink" href="#keepsakes">Explore the collection ↓</a></div></div><div className="houseHeroArt"><a className="artCard artBack realArt" href="/unity-tile-signature-board"><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Personalized Unity Tile Signature Board"/><small>THE UNITY TILE SIGNATURE BOARD</small></a><a className="artCard artFront realArt" href="/memento-map"><img src="/brand/memento-map-product-mockup.png" alt="Memento Map wedding experience"/><small>MEMENTO MAP</small></a><div className="waxSeal"><img src="/brand/memento-house-logo.webp" alt=""/></div></div></section>
 <section className="housePromise"><span>✦</span><p>Not simply décor. Each piece gives your guests a meaningful role in the celebration—and leaves you with something only they could create.</p><span>✦</span></section>
 <section className="products" id="keepsakes"><div className="productsIntro"><div className="eyebrow">The Memento House collection</div><h2>Three ways to make your guests<br/><em>part of the keepsake.</em></h2><p>Designed to be experienced during the wedding and treasured long after it.</p></div><div className="productGrid">
  <a className="productCard" href="/memento-map"><div className="productVisual productImage mapProductImage"><img src="/brand/memento-map-product-mockup.png" alt="Memento Map invitation, mobile map, and framed keepsake"/><span className="productNumber">01</span><small>DIGITAL EXPERIENCE</small><span className="hoverPrompt">Explore Memento Map →</span></div><div className="productCopy"><div><span>RECOMMENDATIONS FOR THE LIFE AHEAD</span><h3>Memento Map</h3><p>Guests map where they came from and recommend real places for the newlyweds to visit—then the couple can keep building the story.</p></div><div className="productLinks"><span>Explore the product →</span><span>From $99</span></div></div></a>
  <a className="productCard" href="/unity-tile-signature-board"><div className="productVisual productImage"><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Jonah and Kate personalized word-tile unity signature board"/><span className="productNumber">02</span><small>INTERACTIVE GUESTBOOK + WALL ART</small><span className="hoverPrompt">See how it works →</span></div><div className="productCopy"><div><span>YOUR STORY STARTS IN THE CENTER</span><h3>The Unity Tile Signature Board</h3><p>Your names and meaningful words begin the artwork. Your guests surround it with signatures, creating a guestbook designed to live on your wall.</p></div><div className="productLinks"><span>Explore the product →</span><span>From $179</span></div></div></a>
  <a className="productCard" href="/memento-deck"><div className="productVisual cardProduct"><img src="/brand/memento-deck-cover.webp" alt="Personalized couple collectible guestbook cover"/><img src="/brand/memento-deck-card.webp" alt="Example story prompt card for the couple"/><span className="productNumber">03</span><small>COLLECTIBLE INTERACTIVE GUESTBOOK</small><span className="hoverPrompt">Discover the deck →</span></div><div className="productCopy"><div><span>DRAW A CARD. LEAVE A STORY.</span><h3>The Memento Deck</h3><p>Guests draw, answer, and sign oversized collectible cards—creating the content of a one-of-one guestbook the couple reads and keeps forever.</p></div><div className="productLinks"><span>Explore the product →</span><span>From $139</span></div></div></a>
 </div></section>
 <section className="houseStory" id="story"><div><div className="eyebrow">Why Memento House</div><h2>Guest experiences that become<br/><em>part of your story.</em></h2></div><div><p>A traditional guestbook records who attended. A Memento House keepsake captures what they gave you: a place to discover, a handwritten name beside yours, or a story only they could tell.</p><p>Elegant enough for the ceremony. Effortless for every guest. Meaningful long after the last dance.</p></div></section>
 <section className="houseCta" id="notify"><div className="eyebrow">Choose what your guests will create</div><h2>One celebration.<br/>A keepsake only your people could make.</h2><p>Explore all three experiences and find the one that feels most like your wedding.</p><div><a href="#keepsakes" className="button gold">Explore the collection →</a><a href="/map/jonah-kate" className="button light">Try the Memento Map demo</a></div></section>
 <footer className="houseFooter"><Logo/><div><a href="/memento-map">Memento Map</a><a href="#keepsakes">Our keepsakes</a><a href="/login">Sign in</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></div><small>© 2026 Memento House</small></footer>
 </main>}
