import {orderHref,unityTiers} from "../../lib/product-tiers";
export const metadata={title:"Unity Tile Signature Board | Memento House",description:"An interactive wedding guestbook designed to become personalized wall art."};
export default function UnityTile(){return <main className="productPage">
 <nav className="houseNav"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/#keepsakes">All keepsakes</a><a href="/create/unity-tile" className="button small">Create yours</a></div></nav>
 <section className="productHero"><div><div className="eyebrow">Unity Tile</div><h1>Your names begin it.<br/><em>Your guests complete it.</em></h1><p>A personalized word-tile guestbook surrounded by the signatures and messages of the people who celebrated with you, designed to become part of your home afterward.</p><p className="heroPromise">Signed at your wedding. Displayed long after it.</p><div className="heroActions"><a href="/create/unity-tile" className="button gold">Create Your Unity Tile →</a><a href="#how" className="button light">See How It Works</a></div></div><figure><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Personalized Jonah and Kate Unity Tile guestbook artwork"/><figcaption>Your story starts in the center. Your people complete it.</figcaption></figure></section>
 <section className="deckManifesto"><div className="eyebrow">An interactive guestbook made to become wall art</div><h2>Beautiful before the first signature.<br/>Irreplaceable after the last.</h2><p>Instead of signing pages that disappear into storage, everyone contributes to one shared piece—already elegant enough for the reception and designed to live in your home.</p></section>
 <section id="how" className="productSteps"><div className="eyebrow">From your story to your walls</div><h2>Created for you. United by you. Completed by them.</h2><div><article><b>01</b><h3>Make it yours</h3><p>Your names, wedding date, meaningful relationship words, colors, style, size, and material become an intentionally composed centerpiece.</p></article><article><b>02</b><h3>Unite your names</h3><p>Most tiles arrive in place. During the unity ceremony, each partner adds only their adhesive first-name tile, visibly joining the two names without making the moment complicated.</p></article><article><b>03</b><h3>Your guests complete it</h3><p>Guests later sign around the joined names. The finished piece comes home as wall art carrying everyone who witnessed the union.</p></article></div></section>
 <section className="transformation unityTransform"><div className="eyebrow">The before-and-after reveal</div><h2>We create the centerpiece.<br/><em>Your favorite people make it irreplaceable.</em></h2><div><article><span>BEFORE</span><h3>Personalized artwork</h3><p>Your interlocking names and relationship words, surrounded by open signature space.</p></article><b>→</b><article><span>AFTER</span><h3>Completed by your guests</h3><p>The same artwork filled with real names, short messages, and the handwriting of the people who were there.</p></article><b>→</b><article><span>AT HOME</span><h3>A guestbook you actually see</h3><p>A quiet piece of wall art that carries your wedding community with it.</p></article></div></section>
 <section className="productFeature"><figure><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Unity Tile artwork with personalized signing spaces"/></figure><div><div className="eyebrow">Make it yours</div><h2>More than two names in the center.</h2><ul><li>Meaningful words, places, traditions, pets, values, or inside references</li><li>Your wedding date incorporated into the finished artwork</li><li>Signature-space count coordinated to your guest list</li><li>Wedding palette and visual direction</li><li>Frame-ready 18 × 24 artwork</li></ul></div></section>
 <section className="pricingSection" id="pricing"><div className="eyebrow">Pricing</div><h2>Choose your level of customization.</h2><div className="pricingGrid two">{unityTiers.map(t=><article className={`priceCard ${t.popular?"popular":""}`} key={t.id}>{t.popular&&<span className="popularTag">BESPOKE</span>}<h3>{t.name}</h3><strong>{t.id==="bespoke"?"+":""}${t.price}</strong><p>{t.subtitle}</p><ul>{t.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a className="button gold" href={orderHref("unity",t.id)}>{t.cta} →</a></article>)}</div></section>
 <section className="deckFaq"><div className="eyebrow">Questions, answered</div><h2>Designed around your wedding—and your home.</h2><details><summary>Is this primarily a sign or a guestbook?</summary><p>It is an interactive wedding guestbook designed from the beginning to become personalized wall art.</p></details><details><summary>Can we choose meaningful words?</summary><p>Yes. You provide the names, words, and story details important to your relationship; we coordinate them into the composition.</p></details><details><summary>Can the signature space fit our guest count?</summary><p>Yes. The number and layout of signature spaces can be customized for your celebration.</p></details><details><summary>Is framing required?</summary><p>No. The artwork is frame-ready, and framing can be treated as a natural premium finishing option.</p></details></section>
 <section className="houseCta"><div className="eyebrow">The signatures stay where the memories live</div><h2>A guestbook you’ll see<br/>more than once.</h2><div><a href="#pricing" className="button gold">Create Your Unity Tile →</a></div></section>
 <footer className="houseFooter"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/memento-map">Memento Map</a><a href="/memento-deck">Memento Deck</a></div><small>© 2026 Memento House</small></footer>
 </main>}
