import {orderHref,unityTiers} from "../../lib/product-tiers";
export const metadata={title:"Unity Tile Signature Board | Memento House",description:"A personalized word-tile unity ceremony and guest signature board in one lasting keepsake."};
export default function UnityTile(){return <main className="productPage">
 <nav className="houseNav"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/#keepsakes">All keepsakes</a><a href={orderHref("unity","signature-board")} className="button small">Order yours</a></div></nav>
 <section className="productHero"><div><div className="eyebrow">Unity ceremony + signature board</div><h1>The Unity Tile<br/><em>Signature Board</em></h1><p>Your names—and the words at the heart of your relationship—become part of a coordinated tile design. Join your name tiles during the ceremony, then invite every guest to sign the surrounding space.</p><a href={orderHref("unity","signature-board")} className="button gold">Choose your board →</a></div><figure><img src="/brand/unity-word-tile-guest-sheet.webp" alt="Personalized Jonah and Kate Unity Tile Signature Board"/><figcaption>18 × 24 · personalized for your story, guest count, and wedding palette.</figcaption></figure></section>
 <section className="productSteps"><div className="eyebrow">How it works</div><h2>Built from the words that make you, you.</h2><div><article><b>01</b><h3>Tell us your words</h3><p>Share names and meaningful words—places, values, traditions, pets, or inside references fundamental to your relationship.</p></article><article><b>02</b><h3>Join the tiles</h3><p>We coordinate the words into the board. During the ceremony, each partner places a name tile to symbolize two lives becoming one.</p></article><article><b>03</b><h3>Invite every signature</h3><p>Choose the number of signature spaces you need. Guests complete the board, creating a frame-ready record of everyone who gathered.</p></article></div></section>
 <section className="pricingSection"><div className="eyebrow">Pricing</div><h2>Choose your level of customization.</h2><div className="pricingGrid two">{unityTiers.map(t=><article className={`priceCard ${t.popular?"popular":""}`} key={t.id}>{t.popular&&<span className="popularTag">BESPOKE</span>}<h3>{t.name}</h3><strong>{t.id==="bespoke"?"+":""}${t.price}</strong><p>{t.subtitle}</p><ul>{t.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a className="button gold" href={orderHref("unity",t.id)}>{t.cta} →</a></article>)}</div></section>
 <footer className="houseFooter"><a href="/" className="houseBrand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/memento-map">Memento Map</a><a href="/memento-deck">Memento Deck</a></div><small>© 2026 Memento House</small></footer>
 </main>}
