import {LegalPage} from "../legal-page";
export const metadata={title:"Terms of service",description:"Commercial and service terms for Memento House accounts, personalized keepsakes, digital experiences, guest content, payments, proofs, and fulfillment.",alternates:{canonical:"/terms"}};
export default function Terms(){return <LegalPage eyebrow="Using Memento House" title="Terms of service" updated="August 31, 2026">
<p>These Terms govern use of mementohouse.com and purchases from Memento House, operated from Cincinnati, Ohio, United States. Questions and formal notices may be sent to <a href="mailto:jonahnr@gmail.com">jonahnr@gmail.com</a>. By creating an account, purchasing, or using an experience, you agree to these Terms.</p>
<h2>Eligibility and account responsibilities</h2><p>You must be legally able to enter a contract and provide accurate, current information. You are responsible for activity under your account, protecting sign-in credentials and shared guest links, and promptly reporting unauthorized use.</p>
<h2>Products, pricing, payments, and taxes</h2><p>Available features, quantities, personalization, and prices are shown at purchase. Prices are in U.S. dollars unless stated otherwise. Stripe processes payment. Applicable sales tax, shipping exceptions, upgrades, and approved custom charges may be added at checkout or by separate invoice. An order is accepted when payment is confirmed and we send an order confirmation; we may cancel and refund an order we cannot fulfill.</p>
<h2>Personalized-product process</h2><p>You are responsible for complete and accurate names, dates, spelling, addresses, images, quantities, and creative direction. Standard packages use the options identified on the product page; Bespoke work may include a questionnaire and the stated revision rounds. Additional concepts, late changes, or work outside the selected tier may require a quote.</p>
<h2>Timing, proof approval, and production</h2><p>Physical personalized products should be started at least eight weeks before the celebration. Timelines are estimates until required information is complete and the final proof is approved. You must review every detail. Production begins after approval, and approved spelling, dates, colors, content, and layout are final. Screen colors can differ from printed materials.</p>
<h2>Shipping, delivery, and risk</h2><p>Our <a href="/shipping">Shipping and production policy</a> is incorporated here. Delivery estimates are not guarantees, especially for carrier delays or incorrect addresses. Risk of loss passes as permitted by applicable law. Inspect packages promptly and report damage or an incorrect item within the policy period. Local pickup is available only when expressly arranged.</p>
<h2>Cancellations and refunds</h2><p>Our <a href="/refunds">Cancellation and refund policy</a> is incorporated here. Personalized work may become non-refundable once design or production begins. Nothing in these Terms limits non-waivable consumer rights.</p>
<h2>Digital services and access</h2><p>Digital access depends on the purchased tier and may require an active account. Guest contribution windows, visibility, storage, map layers, exports, Timeline features, and moderation tools vary by tier. We may maintain, secure, improve, or replace technical components while preserving the material purchased experience. Internet and third-party interruptions can temporarily affect availability.</p>
<h2>Memento House intellectual property</h2><p>Memento House owns or licenses the site, software, templates, product systems, branding, visual designs, prompts, and materials we provide, excluding customer content. Purchase grants a personal, non-transferable right to use the delivered product or digital experience for its intended celebration and keepsake purpose. You may not copy, resell, reverse engineer, remove proof watermarks, or commercially exploit our designs or software.</p>
<h2>Customer-content license</h2><p>You retain ownership of photos, words, story details, and other content you submit. You grant Memento House and its providers a limited, worldwide license to host, reproduce, format, edit for technical or production purposes, display to authorized viewers, print, and deliver that content solely to provide, secure, support, and fulfill the service. You represent that you have the necessary rights.</p>
<h2>Guest contributions and moderation</h2><p>The account owner controls distribution of the guest link and is responsible for reviewing contributions. Guests grant the same limited service license for their submissions. We may reject, hide, preserve as evidence, or remove content that is unlawful, abusive, infringing, unsafe, deceptive, or inconsistent with these Terms, and may restrict excessive or automated submissions.</p>
<h2>Prohibited behavior</h2><p>You may not misuse accounts or links; interfere with security or operation; probe, scrape, overwhelm, or automate submissions without permission; upload malware; impersonate another person; violate privacy or intellectual-property rights; submit illegal or harmful content; evade limits; or use the service to harass, defraud, or exploit anyone.</p>
<h2>Service modifications and termination</h2><p>We may add, remove, or modify features, suspend an unsafe contribution link, or terminate access for material breach, fraud, abuse, nonpayment, or legal necessity. Where practical, we will give notice and a chance to cure. Customers may stop using the service or request account closure, subject to outstanding orders and legally required retention.</p>
<h2>Warranty disclaimers</h2><p>To the extent permitted by law, the service and previews are provided “as is” and “as available.” We do not warrant uninterrupted operation, exact color matching across screens and print, carrier performance, or that every guest submission will be appropriate. Statutory warranties that cannot be excluded remain in effect.</p>
<h2>Limitation of liability</h2><p>To the extent permitted by law, Memento House is not liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or lost profits, data, goodwill, or opportunities. Aggregate liability for a product or service will not exceed the amount paid for the affected order during the twelve months before the claim. This does not apply where prohibited or to liability that cannot lawfully be limited.</p>
<h2>Indemnity</h2><p>To the extent permitted by law, you agree to defend and indemnify Memento House against third-party claims, losses, and reasonable costs arising from content you submit, your infringement of another person’s rights, or your unlawful or material breach of these Terms. This does not require indemnity for Memento House’s own unlawful conduct.</p>
<h2>Governing law, venue, and disputes</h2><p>These Terms are governed by Ohio law, excluding conflict-of-law rules, except where mandatory consumer law provides otherwise. Before filing a claim, each side agrees to send written notice and allow 30 days for good-faith resolution. Unless applicable law requires another forum, disputes may be brought in the state or federal courts serving Hamilton County, Ohio.</p>
<h2>Notices, amendments, and severability</h2><p>Notices to us go to the email above; notices to you may go to the account or order email. We may update these Terms for product, legal, or security changes, with the updated date posted above and additional notice for material changes when appropriate. If one provision is unenforceable, the remaining provisions continue. These Terms and incorporated policies are the entire agreement unless a signed custom agreement states otherwise.</p>
</LegalPage>}
