import {requireUser} from "../../../../lib/request-user";
import {mapTypeConfig,resolveMementoMapType} from "../../../../lib/memento-map-types";

const clean=(value:unknown,max=200)=>String(value||"").trim().slice(0,max);
export async function POST(request:Request){
 const identity=await requireUser(request);if(!identity)return Response.json({error:"Please sign in again."},{status:401});
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null,mapId=clean(body?.mapId,50);if(!body||!mapId)return Response.json({error:"Choose the Memento Map you are setting up."},{status:400});
 const current=await identity.admin.from("weddings").select("id,map_type,map_type_locked,configured_at").eq("id",mapId).eq("owner_user_id",identity.user.id).maybeSingle();if(current.error||!current.data)return Response.json({error:"Your Memento Map could not be found."},{status:404});
 const type=resolveMementoMapType(current.data.map_type),config=mapTypeConfig(type),primary=clean(body.primaryName)||clean(body.eventName)||"Our",secondary=type==="wedding"?clean(body.secondaryName)||"Partner":"",eventName=clean(body.eventName)||({family_reunion:"Our Family Reunion",celebration_of_life:`Remembering ${primary}`,next_chapter:`${primary}'s Next Chapter`,events_community:"Our Community Map",wedding:`${primary} & ${secondary}`} as const)[type],eventLocation=clean(body.eventLocation),eventLat=Number(body.eventLat),eventLng=Number(body.eventLng),hasCoordinates=Number.isFinite(eventLat)&&eventLat>=-90&&eventLat<=90&&Number.isFinite(eventLng)&&eventLng>=-180&&eventLng<=180,metadata={event_name:eventName,event_location:eventLocation,description:clean(body.description,1000),organization_name:clean(body.organizationName),primary_person_name:clean(body.primaryName),birth_date:clean(body.birthDate,10)||null,passing_date:clean(body.passingDate,10)||null,community_subtype:clean(body.communitySubtype)||null,participant_label:config.participantPlural};
 if(eventLocation&&!hasCoordinates)return Response.json({error:"Choose the event location from the address search results so it can be mapped."},{status:400});
 if(eventLocation){
  const anchorType=type==="wedding"?"Wedding Venue":"Event Location",existingVenue=await identity.admin.from("story_locations").select("id").eq("wedding_id",current.data.id).eq("story_type",anchorType).maybeSingle();
  if(existingVenue.error)return Response.json({error:"The event location could not be prepared."},{status:500});
  const venue={wedding_id:current.data.id,story_type:anchorType,title:type==="wedding"?`${primary} & ${secondary}'s wedding`:`${config.shortName} location`,description:type==="wedding"?"The gathering place used to calculate guest travel distance.":`The location connected to this ${config.eventSingular}.`,location_name:eventLocation,latitude:eventLat,longitude:eventLng,event_date:clean(body.eventDate,10)||null,sort_order:-1};
  const venueResult=existingVenue.data?await identity.admin.from("story_locations").update(venue).eq("id",existingVenue.data.id):await identity.admin.from("story_locations").insert(venue);
  if(venueResult.error)return Response.json({error:"The event location coordinates could not be saved."},{status:500});
 }
 const result=await identity.admin.from("weddings").update({map_subtype:clean(body.subtype)||null,event_metadata:metadata,partner_one_name:primary,partner_two_name:secondary,title:eventName,wedding_date:clean(body.eventDate,10)||null,welcome_message:clean(body.description,1000)||undefined,configured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",current.data.id).eq("owner_user_id",identity.user.id).select("id,slug,map_type").single();if(result.error)return Response.json({error:"Your Memento Map details could not be saved."},{status:500});return Response.json({map:result.data});
}
