export type CelebrationExperience={slug:string;name:string;status:"Available now"|"Coming soon";headline:string;intro:string;products:{name:string;description:string;href:string}[];moments:string[]};

export const CELEBRATIONS:CelebrationExperience[]=[
 {slug:"wedding",name:"Wedding",status:"Available now",headline:"Let everyone you love become part of the day.",intro:"Four participatory keepsakes turn the people, places, stories, and promises surrounding your wedding into something you can revisit for years.",products:[{name:"Memento Map",description:"Map where guests traveled from and where they hope your life together takes you.",href:"/memento-map"},{name:"Timeline Plus",description:"Connect the chapters of your relationship to the real places where they happened.",href:"/memento-map#pricing"},{name:"Unity Tile Signature Board",description:"Join your first names during the ceremony, then invite every guest to leave a signature around them.",href:"/unity-tile-signature-board"},{name:"Memento Deck",description:"Guests create a collectible archive of memories, advice, predictions, and future messages.",href:"/memento-deck"}],moments:["Ceremony participation","Guest storytelling","Post-wedding discovery","A keepsake built to revisit"]},
 {slug:"anniversary",name:"Anniversary",status:"Coming soon",headline:"Celebrate every chapter that brought you here.",intro:"An anniversary edition for retracing the places, people, promises, and small traditions that shaped a life together.",products:[{name:"Anniversary Map",description:"Revisit meaningful places and collect ideas for the adventures still ahead.",href:"/contact?celebration=Anniversary"},{name:"Anniversary Timeline",description:"Turn your relationship milestones into a chronological, place-based story.",href:"/contact?celebration=Anniversary"},{name:"Anniversary Tile Board",description:"Build a shared word portrait from the names and values at the center of your relationship.",href:"/contact?celebration=Anniversary"},{name:"Anniversary Deck",description:"Invite family and friends to contribute memories, reflections, and messages for the years ahead.",href:"/contact?celebration=Anniversary"}],moments:["Where it began","Traditions you created","Milestones you crossed","What comes next"]},
 {slug:"milestone-birthday",name:"Milestone Birthday",status:"Coming soon",headline:"A life this full deserves more than signatures.",intro:"Bring together the stories, inside jokes, advice, and defining words that make one remarkable person unmistakably themselves.",products:[{name:"Milestone Tile Board",description:"Create a personalized word grid surrounded by messages from everyone in the room.",href:"/contact?celebration=Milestone%20Birthday"},{name:"Milestone Deck",description:"Guests draw prompts and build a one-of-one archive of stories, laughter, and wishes.",href:"/contact?celebration=Milestone%20Birthday"}],moments:["Favorite memories","Words that define them","Stories worth retelling","Wishes for the next decade"]},
 {slug:"family-reunion",name:"Family Reunion",status:"Coming soon",headline:"See how far your family reaches, and what holds it together.",intro:"A shared family experience for mapping hometowns, preserving generations of stories, and creating a keepsake together in one place.",products:[{name:"Family Map",description:"Pin where every branch traveled from and preserve the geography of your gathering.",href:"/contact?celebration=Family%20Reunion"},{name:"Family Timeline",description:"Connect migrations, homes, reunions, and turning points across generations.",href:"/contact?celebration=Family%20Reunion"},{name:"Family Tile Board",description:"Build a personalized word grid from surnames, traditions, values, and signatures.",href:"/contact?celebration=Family%20Reunion"}],moments:["Family origins","Generational stories","Shared traditions","The next reunion"]},
 {slug:"retirement",name:"Retirement",status:"Coming soon",headline:"Honor the work. Celebrate the person beyond it.",intro:"Colleagues, friends, and family contribute the memories, lessons, destinations, and future plans that mark a meaningful transition.",products:[{name:"Retirement Map",description:"Map career chapters and the adventures waiting beyond the final workday.",href:"/contact?celebration=Retirement"},{name:"Career Timeline",description:"Trace defining roles, teams, moves, achievements, and relationships.",href:"/contact?celebration=Retirement"},{name:"Retirement Tile Board",description:"Gather signatures around the values and words that defined a career.",href:"/contact?celebration=Retirement"},{name:"Retirement Deck",description:"Collect stories, advice, gratitude, and ideas for what comes next.",href:"/contact?celebration=Retirement"}],moments:["Career chapters","People influenced","Lessons learned","Future adventures"]},
 {slug:"graduation",name:"Graduation",status:"Coming soon",headline:"Capture who helped them get here, and where they may go next.",intro:"A forward-looking keepsake experience built from advice, memories, hometowns, campus landmarks, and dreams for the next chapter.",products:[{name:"Graduation Map",description:"Map the journey to graduation and the places the future might lead.",href:"/contact?celebration=Graduation"},{name:"Graduation Timeline",description:"Connect schools, achievements, mentors, and defining moments.",href:"/contact?celebration=Graduation"},{name:"Graduation Deck",description:"Guests contribute advice, predictions, memories, and messages to open later.",href:"/contact?celebration=Graduation"}],moments:["The road here","People who helped","Advice for tomorrow","Dream destinations"]},
 {slug:"baby-shower",name:"Baby Shower",status:"Coming soon",headline:"A first collection of stories for a life just beginning.",intro:"Loved ones create a deck of advice, family memories, hopes, and future messages for parents and child to discover over time.",products:[{name:"Baby Shower Memento Deck",description:"Guests answer thoughtful prompts and leave messages for first days, hard days, birthdays, and years from now.",href:"/contact?celebration=Baby%20Shower"}],moments:["Advice for new parents","Family stories","Future birthday messages","Hopes for who they become"]},
 {slug:"new-home",name:"New Home",status:"Coming soon",headline:"Let the people you love leave their mark on your next chapter.",intro:"A signature board designed around the names, places, values, and hopes that will make a new house feel like home.",products:[{name:"New Home Unity Tile Board",description:"Create a personalized word grid for guests to sign at a housewarming, closing celebration, or family gathering.",href:"/contact?celebration=New%20Home"}],moments:["Names under one roof","Words for the home","Housewarming signatures","A framed first memory"]}
];
export const celebrationBySlug=(slug:string)=>CELEBRATIONS.find(item=>item.slug===slug);
