export type CelebrationExperience={slug:string;name:string;status:"Available now"|"Coming soon";headline:string;intro:string;products:{name:string;description:string;href:string}[];moments:string[]};

const legacyCelebrations:CelebrationExperience[]=[{"slug":"wedding","name":"Wedding","headline":"Let everyone you love become part of the day.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this wedding.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"anniversary","name":"Anniversary","headline":"Celebrate every chapter that brought you here.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this anniversary.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"milestone-birthday","name":"Milestone Birthday","headline":"A life this full deserves more than signatures.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this milestone birthday.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"family-reunion","name":"Family Reunion","headline":"See how far your family reaches, and what holds it together.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this family reunion.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"retirement","name":"Retirement","headline":"Honor the work. Celebrate the person beyond it.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this retirement.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"graduation","name":"Graduation","headline":"Capture the road here and the possibilities ahead.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this graduation.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"baby-shower","name":"Baby Shower","headline":"A first collection of stories for a life just beginning.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this baby shower.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]},{"slug":"new-home","name":"New Home","headline":"Let the people you love leave their mark on your next chapter.","status":"Available now","intro":"Bring your people together to share the places, stories, and wishes behind this new home.","products":[],"moments":["Meaningful places","Shared memories","Words from loved ones","A keepsake to revisit"]}];
const nextChapterSlugs=['retirement','graduation','baby-shower','new-home','milestone-birthday'];
const productsFor=(slug:string)=>slug==='wedding'?[
 {name:'Memento Map',description:'Guests map where they came from and recommend real places for the newlyweds to visit—then the couple can keep building the story.',href:'/memento-map/wedding'},
 {name:'Tile Board',description:'The couple’s names and meaningful words begin the artwork. Guests surround it with signatures, creating a wedding guestbook designed to display.',href:'/unity-tile-signature-board?occasion=wedding'},
 {name:'Memento Deck',description:'Guests draw, answer, and sign collectible cards, creating a one-of-one wedding guestbook the couple can read and keep.',href:'/memento-deck?occasion=wedding'}
]:[
 {name:'Memento Map',description:'Collect meaningful places, memories, and future ideas in a map tailored to this occasion.',href:'/memento-map/'+(slug==='events-communities'?'events':slug)},
 ...(!['celebration-of-life','graduation','milestone-birthday','events-communities'].includes(slug)?[{name:'Tile Board',description:'Gather names, meaningful words, and signatures in one personalized keepsake.',href:'/unity-tile-signature-board?occasion='+slug}]:[]),
 {name:'Memento Deck',description:'Invite memories, advice, and messages with a personalized collection of cards.',href:'/memento-deck?occasion='+slug}
];
export const CELEBRATIONS:CelebrationExperience[]=legacyCelebrations.map(item=>({...item,status:'Available now',intro:item.slug==='wedding'?'Three participatory keepsakes bring the people, places, and stories surrounding your wedding together.':item.intro,products:productsFor(item.slug)}));
CELEBRATIONS.push({slug:'celebration-of-life',name:'Celebration of Life',status:'Available now',headline:'Remember a life through the stories you share.',intro:'Gather meaningful places and memories at a pace that feels right for your family.',products:productsFor('celebration-of-life'),moments:['A life in places','Memories from loved ones','Thoughtful contribution review','A tribute to revisit']},{slug:'events-communities',name:'Events & Communities',status:'Available now',headline:'See the people and places that bring your community together.',intro:'Invite attendee contributions and preserve the story of your gathering.',products:[productsFor('events-communities')[0]],moments:['Attendee origins','Shared history','Event display','A finished digital keepsake']},{slug:'next-chapter',name:'Next Chapter',status:'Available now',headline:'A new chapter, shaped by the people who care.',intro:'Choose retirement, graduation, baby shower, new home, or milestone birthday to find the right keepsakes.',products:nextChapterSlugs.map(slug=>({name:legacyCelebrations.find(item=>item.slug===slug)!.name,description:'Explore the keepsakes and map created for this occasion.',href:'/celebrations/'+slug})),moments:['The story so far','The people who helped','Wishes and advice','What comes next']});
export const CELEBRATION_GROUPS=CELEBRATIONS.filter(item=>!nextChapterSlugs.includes(item.slug));
export const celebrationBySlug=(slug:string)=>CELEBRATIONS.find(item=>item.slug===slug);
