type ShipmentEmail={recipient:string;orderId:string;carrier:string;trackingNumber:string;trackingUrl?:string};
type ProofEmail={recipient:string;orderId:string;productName:string};
type OrderEmail={recipient:string;orderId:string;productName:string};
type RefundEmail=OrderEmail&{amount:number;currency:string};
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
async function send(recipient:string,subject:string,html:string,text:string,key:string){const apiKey=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL||"Memento House <orders@mementohouse.com>";if(!apiKey)return {sent:false,error:"RESEND_API_KEY is not configured"};try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({from,to:[recipient],reply_to:process.env.RESEND_REPLY_TO||"jonahnr@gmail.com",subject,html,text}),signal:AbortSignal.timeout(10000)}),payload=await response.json().catch(()=>({})) as {id?:string;message?:string};return response.ok&&payload.id?{sent:true,id:payload.id}:{sent:false,error:payload.message||`Resend returned ${response.status}`}}catch(error){return{sent:false,error:error instanceof Error?error.message:"Email delivery timed out"}}}
const shell=(title:string,body:string)=>`<div style="font-family:Georgia,serif;color:#282621;max-width:600px;margin:auto;padding:36px"><img src="https://mementohouse.com/brand/memento-house-logo.webp" width="82" height="82" alt="Memento House" style="display:block;object-fit:contain;margin-bottom:18px"><p style="color:#a77b3f;letter-spacing:.18em;font:12px Arial,sans-serif">MEMENTO HOUSE</p><h1 style="font-weight:400">${title}</h1>${body}<p style="margin-top:38px;color:#786f64">Made for the moment. Kept for a lifetime.</p></div>`;
export async function sendShipmentEmail(message:ShipmentEmail){const carrier=escapeHtml(message.carrier),tracking=escapeHtml(message.trackingNumber),url=message.trackingUrl?escapeHtml(message.trackingUrl):"";return send(message.recipient,"Your Memento House order is on the way",shell("Your keepsake is on its way.",`<p>Your order has been handed to ${carrier}.</p><p><strong>Tracking number:</strong> ${tracking}</p>${url?`<p><a href="${url}" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">Track your shipment</a></p>`:""}`),`Your Memento House order is on its way. Carrier: ${message.carrier}. Tracking number: ${message.trackingNumber}.${message.trackingUrl?` Track it at ${message.trackingUrl}`:""}`,`shipment-${message.orderId}-${message.trackingNumber}`)}
export async function sendProofEmail(message:ProofEmail){const site=(process.env.NEXT_PUBLIC_SITE_URL||"https://mementohouse.com").replace(/\/$/,""),url=`${site}/account?order=${encodeURIComponent(message.orderId)}`;return send(message.recipient,"Your Memento House proof is ready",shell("Your proof is ready to review.",`<p>We prepared the next proof for your ${escapeHtml(message.productName)}.</p><p><a href="${url}" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">Review your proof</a></p><p>Sign in with the same email used at checkout to approve it or request changes.</p>`),`Your Memento House proof is ready. Sign in at ${url} to review it, approve it, or request changes.`,`proof-${message.orderId}-${Date.now()}`)}
export async function sendOrderConfirmationEmail(message:OrderEmail){const number=message.orderId.slice(0,8).toUpperCase(),site=(process.env.NEXT_PUBLIC_SITE_URL||"https://mementohouse.com").replace(/\/$/,"");return send(message.recipient,`Memento House order ${number} confirmed`,shell("We received your order.",`<p><strong>Order ${number}</strong></p><p>Thank you for choosing the ${escapeHtml(message.productName)}.</p><p>We saved your selections and will send your next update as soon as your proof or digital experience is ready.</p><p><a href="${site}/account?order=${encodeURIComponent(message.orderId)}" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">View your order</a></p>`),`We received Memento House order ${number} for ${message.productName}. Sign in at ${site}/account?order=${encodeURIComponent(message.orderId)} to view your order and next steps.`,`order-confirmation-${message.orderId}`)}
export const sendTestOrderEmail=sendOrderConfirmationEmail;
export async function sendRefundEmail(message:RefundEmail){const number=message.orderId.slice(0,8).toUpperCase(),amount=new Intl.NumberFormat("en-US",{style:"currency",currency:message.currency.toUpperCase()}).format(message.amount/100);return send(message.recipient,`Refund issued for Memento House order ${number}`,shell("Your refund has been issued.",`<p><strong>Order ${number}</strong></p><p>We issued a refund of <strong>${escapeHtml(amount)}</strong> for your ${escapeHtml(message.productName)}.</p><p>Your related digital access has been revoked. Your bank may take several business days to display the credit.</p>`),`A refund of ${amount} was issued for Memento House order ${number}. Related digital access has been revoked.`,`refund-${message.orderId}`)}
