type ShipmentEmail={recipient:string;orderId:string;carrier:string;trackingNumber:string;trackingUrl?:string};
type ProofEmail={recipient:string;orderId:string;productName:string};
type TestOrderEmail={recipient:string;orderId:string;productName:string};
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
async function send(recipient:string,subject:string,html:string,text:string,key:string){const apiKey=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL||"Memento House <orders@mementohouse.com>";if(!apiKey)return {sent:false,error:"RESEND_API_KEY is not configured"};const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({from,to:[recipient],reply_to:process.env.RESEND_REPLY_TO||"jonahnr@gmail.com",subject,html,text})}),payload=await response.json().catch(()=>({})) as {id?:string;message?:string};return response.ok&&payload.id?{sent:true,id:payload.id}:{sent:false,error:payload.message||`Resend returned ${response.status}`}}
const shell=(title:string,body:string)=>`<div style="font-family:Georgia,serif;color:#282621;max-width:600px;margin:auto;padding:36px"><p style="color:#a77b3f;letter-spacing:.18em;font:12px Arial,sans-serif">MEMENTO HOUSE</p><h1 style="font-weight:400">${title}</h1>${body}<p style="margin-top:38px;color:#786f64">Made for the moment. Kept for a lifetime.</p></div>`;
export async function sendShipmentEmail(message:ShipmentEmail){const carrier=escapeHtml(message.carrier),tracking=escapeHtml(message.trackingNumber),url=message.trackingUrl?escapeHtml(message.trackingUrl):"";return send(message.recipient,"Your Memento House order is on the way",shell("Your keepsake is on its way.",`<p>Your order has been handed to ${carrier}.</p><p><strong>Tracking number:</strong> ${tracking}</p>${url?`<p><a href="${url}" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">Track your shipment</a></p>`:""}`),`Your Memento House order is on its way. Carrier: ${message.carrier}. Tracking number: ${message.trackingNumber}.${message.trackingUrl?` Track it at ${message.trackingUrl}`:""}`,`shipment-${message.orderId}-${message.trackingNumber}`)}
export async function sendProofEmail(message:ProofEmail){return send(message.recipient,"Your Memento House proof is ready",shell("Your proof is ready to review.",`<p>We prepared the next proof for your ${escapeHtml(message.productName)}.</p><p><a href="https://mementohouse.com/dashboard" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">Review your proof</a></p><p>Sign in with the same email used at checkout to approve it or request changes.</p>`),`Your Memento House proof is ready. Sign in at https://mementohouse.com/dashboard to review it, approve it, or request changes.`,`proof-${message.orderId}`)}
export async function sendTestOrderEmail(message:TestOrderEmail){return send(message.recipient,"Memento House admin test order created",shell("Your private test order was created.",`<p>The no-charge fulfillment simulation for ${escapeHtml(message.productName)} completed successfully.</p><p><a href="https://mementohouse.com/admin/orders" style="display:inline-block;background:#a77b3f;color:white;text-decoration:none;padding:14px 22px">Open fulfillment console</a></p>`),`Your private Memento House test order for ${message.productName} was created. Open https://mementohouse.com/admin/orders to continue testing.`,`test-order-${message.orderId}`)}
