import type {SupabaseClient} from "@supabase/supabase-js";
import {initialPaidState} from "./order-domain";
import {resolveCatalog} from "./product-catalog";
type Input={source:"stripe"|"admin";sourceId:string;eventId?:string;email:string;name?:string;userId?:string|null;product:string;tier:string;addons:string[];amount:number;currency?:string;customizationId?:string|null;paymentIntentId?:string|null};
async function findOrInvite(admin:SupabaseClient,email:string,item:ReturnType<typeof resolveCatalog>,existing?:string|null){if(existing)return existing;let page=1;while(page<20){const result=await admin.auth.admin.listUsers({page,perPage:100});if(result.error)throw result.error;const found=result.data.users.find(u=>u.email?.toLowerCase()===email);if(found)return found.id;if(result.data.users.length<100)break;page++}const invited=await admin.auth.admin.inviteUserByEmail(email,{redirectTo:"https://mementohouse.com/account/setup",data:{entitlement:item.entitlement,purchase_status:"paid"}});if(invited.error)throw invited.error;return invited.data.user.id}
export async function fulfillPurchase(admin:SupabaseClient,input:Input){const item=resolveCatalog(input.product,input.tier,input.addons),userId=await findOrInvite(admin,input.email,item,input.userId);const orderState=initialPaidState(item.fulfillmentWorkflow);
 const orderResult=await admin.from("orders").upsert({stripe_session_id:input.source==="stripe"?input.sourceId:null,external_reference:input.sourceId,stripe_payment_intent_id:input.paymentIntentId||null,customer_user_id:userId,customer_email:input.email,customer_name:input.name||"",product:item.productId,tier:item.tierId,catalog_key:item.key,addons:[...item.includedAddons,...input.addons],amount_total:input.amount,currency:input.currency||"usd",payment_status:input.source==="admin"?"admin_bypass":"paid",order_status:orderState,fulfillment_workflow:item.fulfillmentWorkflow,questionnaire_status:"not_started",entitlement_status:"active",customization_id:input.customizationId||null,is_test:input.source==="admin",paid_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"external_reference"}).select("*").single();if(orderResult.error)throw orderResult.error;const order=orderResult.data;
 await admin.from("entitlements").upsert({order_id:order.id,user_id:userId,entitlement:item.entitlement,status:"active"},{onConflict:"order_id,entitlement"});
 await admin.from("questionnaires").upsert({order_id:order.id,user_id:userId,questionnaire_type:item.questionnaireType,schema_version:1,status:"not_started"},{onConflict:"order_id"});
 await admin.from("fulfillment_jobs").upsert({order_id:order.id,workflow:item.fulfillmentWorkflow,status:orderState},{onConflict:"order_id"});
 await admin.from("order_events").insert({order_id:order.id,event_type:"purchase_fulfilled",from_status:"payment_pending",to_status:orderState,actor_type:input.source,metadata:{source_id:input.sourceId}});
 await admin.auth.admin.updateUserById(userId,{user_metadata:{entitlement:item.entitlement,product_tier:item.productId==="map"?item.tierId:undefined,purchase_status:"paid",last_order_id:order.id}});
 return{order,item,userId,questionnaireType:item.questionnaireType,nextSteps:item.nextSteps};}
