import type {SupabaseClient} from "@supabase/supabase-js";
import {initialPaidState} from "./order-domain";
import {resolveCatalog} from "./product-catalog";
type Input={source:"stripe"|"admin";sourceId:string;stripeSessionId?:string|null;eventId?:string;email:string;name?:string;userId?:string|null;product:string;tier:string;addons:string[];amount:number;currency?:string;customizationId?:string|null;paymentIntentId?:string|null;isTest?:boolean};
async function findOrInvite(admin:SupabaseClient,email:string,item:ReturnType<typeof resolveCatalog>,existing?:string|null){if(existing)return existing;let page=1;while(page<20){const result=await admin.auth.admin.listUsers({page,perPage:100});if(result.error)throw result.error;const found=result.data.users.find(u=>u.email?.toLowerCase()===email);if(found)return found.id;if(result.data.users.length<100)break;page++}const invited=await admin.auth.admin.inviteUserByEmail(email,{redirectTo:"https://mementohouse.com/account/setup",data:{entitlement:item.entitlement,purchase_status:"paid"}});if(invited.error)throw invited.error;return invited.data.user.id}
async function checked(operation:PromiseLike<{error:unknown}>){const result=await operation;if(result.error)throw result.error}
export async function fulfillPurchase(admin:SupabaseClient,input:Input){const item=resolveCatalog(input.product,input.tier,input.addons),userId=await findOrInvite(admin,input.email,item,input.userId);const prior=await admin.from("orders").select("*").eq("external_reference",input.sourceId).maybeSingle();if(prior.error)throw prior.error;if(prior.data){const completed=await admin.from("order_events").select("id").eq("order_id",prior.data.id).eq("event_type","purchase_fulfilled").limit(1);if(completed.error)throw completed.error;if(completed.data?.length)return{order:prior.data,item,userId,questionnaireType:item.questionnaireType,nextSteps:item.nextSteps};}const needsQuestionnaire=item.questionnaire.length>0,orderState=initialPaidState(item.fulfillmentWorkflow,needsQuestionnaire);
 const orderResult=await admin.from("orders").upsert({stripe_session_id:input.source==="stripe"?(input.stripeSessionId===undefined?input.sourceId:input.stripeSessionId):null,external_reference:input.sourceId,stripe_payment_intent_id:input.paymentIntentId||null,customer_user_id:userId,customer_email:input.email,customer_name:input.name||"",product:item.productId,tier:item.tierId,catalog_key:item.key,addons:[...item.includedAddons,...input.addons],amount_total:input.amount,currency:input.currency||"usd",payment_status:input.source==="admin"?"admin_bypass":input.isTest?"test_paid":"paid",order_status:orderState,fulfillment_workflow:item.fulfillmentWorkflow,questionnaire_status:needsQuestionnaire?"not_started":"not_required",entitlement_status:"active",customization_id:input.customizationId||null,is_test:input.source==="admin"||input.isTest===true,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"external_reference",ignoreDuplicates:true});if(orderResult.error)throw orderResult.error;const saved=await admin.from("orders").select("*").eq("external_reference",input.sourceId).single();if(saved.error)throw saved.error;const order=saved.data;
 if(input.customizationId)await checked(admin.from("checkout_customizations").update({claimed_order_id:order.id}).eq("id",input.customizationId));
 await checked(admin.from("entitlements").upsert({order_id:order.id,user_id:userId,entitlement:item.entitlement,status:"active"},{onConflict:"order_id,entitlement",ignoreDuplicates:true}));
 if(needsQuestionnaire)await checked(admin.from("questionnaires").upsert({order_id:order.id,user_id:userId,questionnaire_type:item.questionnaireType,schema_version:1,status:"not_started"},{onConflict:"order_id",ignoreDuplicates:true}));
 await checked(admin.from("fulfillment_jobs").upsert({order_id:order.id,workflow:item.fulfillmentWorkflow,status:orderState},{onConflict:"order_id",ignoreDuplicates:true}));

 await checked(admin.auth.admin.updateUserById(userId,{user_metadata:{entitlement:item.entitlement,product_tier:item.productId==="map"?item.tierId:undefined,purchase_status:"paid",last_order_id:order.id}}));
 await checked(admin.from("order_events").insert({order_id:order.id,event_type:"purchase_fulfilled",from_status:"payment_pending",to_status:orderState,actor_type:input.source,metadata:{source_id:input.sourceId}}));
 return{order,item,userId,questionnaireType:item.questionnaireType,nextSteps:item.nextSteps};}
