export type GuestbookKind="traditional"|"signature"|"media"|"map"|"plus"|"timeline";
type Choice={label:string;weights:Partial<Record<GuestbookKind,number>>};
export const QUIZ_QUESTIONS:{question:string;choices:Choice[]}[]=[
{question:"What do you most want to keep from your wedding?",choices:[{label:"Messages and advice",weights:{traditional:3,map:1}},{label:"Photos and videos",weights:{media:4,timeline:2}},{label:"Signatures",weights:{signature:4,traditional:2}},{label:"Travel recommendations",weights:{plus:4,map:2,timeline:2}},{label:"Something we can keep using",weights:{plus:3,timeline:3}},{label:"A little bit of everything",weights:{timeline:3,media:1}}]},
{question:"Which sounds most like you?",choices:[{label:"Travelers",weights:{plus:2,map:1,timeline:1}},{label:"Sentimental",weights:{media:2,timeline:2,traditional:1}},{label:"Creative",weights:{signature:3}},{label:"Traditional",weights:{traditional:3,signature:1}},{label:"Adventurous",weights:{plus:3,map:1}},{label:"Social",weights:{media:2,map:1}}]},
{question:"How would you like guests to participate?",choices:[{label:"Scan a QR code",weights:{map:4,plus:2,timeline:2}},{label:"Write something",weights:{traditional:3,signature:1}},{label:"Take a photo",weights:{media:4}},{label:"Record something",weights:{media:4}},{label:"Give recommendations",weights:{plus:4,map:2}},{label:"Multiple options",weights:{timeline:3,map:1,media:1}}]},
{question:"What do you want to do with the guestbook afterward?",choices:[{label:"Display it",weights:{signature:4}},{label:"Store it",weights:{traditional:3}},{label:"Look through it sometimes",weights:{traditional:2,media:2}},{label:"Continue using it",weights:{timeline:3,plus:2}},{label:"Use it to plan future experiences",weights:{plus:5,timeline:1}}]},
{question:"How important are photos and videos?",choices:[{label:"Very",weights:{media:2,timeline:4}},{label:"Nice to have",weights:{timeline:1,plus:1,media:1}},{label:"Not important",weights:{traditional:2,signature:2,map:2}}]},
{question:"Should your guestbook keep growing after your wedding?",choices:[{label:"Definitely",weights:{timeline:4,plus:3}},{label:"Maybe",weights:{plus:1,timeline:1,map:1}},{label:"No",weights:{traditional:3,signature:2,media:2}}]},
];
export const QUIZ_RESULTS:Record<GuestbookKind,{title:string;description:string;href:string;cta:string}>={traditional:{title:"Traditional Guestbook",description:"You lean toward written messages and a keepsake to browse or store. A book with a few thoughtful prompts can fit those preferences without adding screens or equipment.",href:"/wedding-guest-book-alternative",cta:"Compare handwritten options"},signature:{title:"Physical Signature Keepsake",description:"Signatures and a piece you can display fit your answers. Consider an illustration, signed artwork, or a collaborative physical keepsake, with a tested pen and enough writing space.",href:"/unique-wedding-guest-book-ideas",cta:"Explore displayable ideas"},media:{title:"Audio/Photo Guestbook",description:"You care about voices, photos, or recordings. Choose a photo album, audio station, or video invitation around the medium you want to revisit, and plan equipment and file backup.",href:"/ideas/10-alternatives-to-a-traditional-wedding-guestbook",cta:"Compare audio and photo formats"},map:{title:"Memento Map",description:"Your answers lean toward a browser-based invitation and meaningful places. The shared map gathers guest origins and recommendations; compare the package details if you also want planning, exports, or a timeline.",href:"/memento-map/wedding#pricing",cta:"Explore Memento Map"},plus:{title:"Memento Map Plus",description:"Recommendations and future experiences matter to you. Map Plus lets guest ideas become places in your Travel Journal, with ranking, Want to Go, Planning, and Visited tracking, plus digital export files.",href:"/memento-map/wedding#pricing",cta:"Explore Map Plus"},timeline:{title:"Timeline Plus",description:"You lean toward a story that keeps growing with memories and context. Timeline Plus adds dated guest memories and a chronological relationship story to the map and Map Plus planning tools.",href:"/memento-map/wedding#pricing",cta:"Explore Timeline Plus"}};
export function quizRecommendation(answers:number[]){if(answers.length!==QUIZ_QUESTIONS.length||answers.some((answer,index)=>!Number.isInteger(answer)||!QUIZ_QUESTIONS[index].choices[answer]))throw new Error("Answer all six questions.");const scores:Record<GuestbookKind,number>={traditional:0,signature:0,media:0,map:0,plus:0,timeline:0};answers.forEach((answer,index)=>{const weights=QUIZ_QUESTIONS[index].choices[answer].weights;for(const [key,value]of Object.entries(weights))scores[key as GuestbookKind]+=value});const kind=(Object.keys(scores) as GuestbookKind[]).sort((a,b)=>scores[b]-scores[a])[0];return {kind,...QUIZ_RESULTS[kind],reasons:[0,2,3,5].map(index=>({question:QUIZ_QUESTIONS[index].question,answer:QUIZ_QUESTIONS[index].choices[answers[index]].label}))}}
export type GeneratorInput={size:"small"|"medium"|"large";style:"classic"|"travel"|"creative"|"relaxed";preference:"physical"|"digital"|"either";goal:"messages"|"signatures"|"photos"|"travel"|"story";budget:50|100|150|1000;participation:"quick"|"thoughtful"|"multiple"};
type Idea={id:string;title:string;format:"physical"|"digital";goals:string[];styles:string[];minimumBudget:number;complexity:string;participation:string;after:string;why:string;href:string;map?:boolean};
const OPTIONS:Idea[]=[
{id:"book",title:"A prompted handwritten guestbook",format:"physical",goals:["messages","story"],styles:["classic","relaxed"],minimumBudget:0,complexity:"Low · book, tested pens, seated space",participation:"Write a memory or wish",after:"Read together and keep the original handwriting",why:"A direct written invitation keeps setup manageable and gives guests space for a personal answer.",href:"/wedding-guest-book-alternative"},
{id:"art",title:"Signed artwork or venue illustration",format:"physical",goals:["signatures"],styles:["classic","creative"],minimumBudget:0,complexity:"Low to medium · prepare and test the surface",participation:"Leave a signature or short note",after:"Frame a piece made by your guests",why:"A visual contribution fits a keepsake you want to display rather than file away.",href:"/unique-wedding-guest-book-ideas"},
{id:"cards",title:"Advice and date-night cards",format:"physical",goals:["messages","travel"],styles:["relaxed","classic"],minimumBudget:0,complexity:"Low · print prompts and provide a collection box",participation:"Answer one prompt at the table",after:"Choose an idea to try on a date night",why:"Small contributions fit naturally into the reception and give you practical ideas to revisit.",href:"/wedding-bucket-list-guest-book"},
{id:"postcards",title:"A postcard story collection",format:"physical",goals:["travel","story"],styles:["travel","creative"],minimumBudget:0,complexity:"Low · provide spare postcards and prompts",participation:"Describe a meaningful place",after:"Keep a destination album with names and tips",why:"Handwritten places and stories connect a travel theme to the people at your wedding.",href:"/travel-themed-wedding-guest-book"},
{id:"photos",title:"An instant-photo album",format:"physical",goals:["photos"],styles:["creative","relaxed"],minimumBudget:50,complexity:"Medium · camera, film, lighting, and a helper",participation:"Take a group photo and add a caption",after:"Browse the pictures and messages together",why:"A photo plus a short note preserves faces and the context around the picture.",href:"/ideas/interactive-wedding-guest-book-ideas"},
{id:"puzzle",title:"A collaborative signature puzzle",format:"physical",goals:["signatures"],styles:["creative"],minimumBudget:0,complexity:"Medium · suitable pieces, tested pens, and inventory",participation:"Sign a piece and return it to the tray",after:"Assemble together or frame the result",why:"A small shared activity suits guests who enjoy a tactile contribution.",href:"/unique-wedding-guest-book-ideas"},
{id:"digital-messages",title:"A shared digital message collection",format:"digital",goals:["messages"],styles:["relaxed","classic"],minimumBudget:0,complexity:"Low to medium · choose a tool and verify guest access",participation:"Open a link and leave a message",after:"Read and back up the collection",why:"A link can be shared around the room and later; verify privacy and export terms in your chosen tool.",href:"/digital-wedding-guest-book"},
{id:"gallery",title:"A guest photo gallery with captions",format:"digital",goals:["photos"],styles:["creative","relaxed"],minimumBudget:0,complexity:"Medium · test uploads and guest permissions",participation:"Upload a picture and explain the moment",after:"Review, select, and back up the photos",why:"Guests can contribute their own view of the day without finding a single camera station.",href:"/wedding-memory-ideas"},
{id:"voice",title:"A collection of recorded wishes",format:"digital",goals:["messages","story"],styles:["classic","relaxed"],minimumBudget:0,complexity:"Medium · quiet area, recording setup, file delivery",participation:"Record one short story or wish",after:"Listen to familiar voices and save the files",why:"Voices add detail beyond signatures; provide a written option for guests who prefer it.",href:"/ideas/10-alternatives-to-a-traditional-wedding-guestbook"},
{id:"video",title:"Short video messages",format:"digital",goals:["photos","story"],styles:["creative","relaxed"],minimumBudget:0,complexity:"Medium to high · sound, light, consent, and storage",participation:"Record alone or with a small group",after:"Watch a collection of expressions and stories",why:"A focused recording prompt can capture the people around the memory as well as their words.",href:"/wedding-memory-ideas"},
{id:"memory-pages",title:"A digital relationship scrapbook",format:"digital",goals:["story","photos"],styles:["classic","creative"],minimumBudget:0,complexity:"Medium · template, dates, permissions, and backups",participation:"Send a memory and optional photograph",after:"Arrange the collection into chapters",why:"A story-centered format gives personal memories context even when you do not need geographic features.",href:"/wedding-memory-ideas"},
{id:"map",title:"Memento Map",format:"digital",goals:["travel","messages"],styles:["travel"],minimumBudget:99,complexity:"Low to medium · configure the map, test QR signs, and invite guests",participation:"Add an origin or recommended place",after:"Revisit the people and places in the shared map",why:"Real locations give guest recommendations and origins a natural home. The base package is $99; planning and exports require an upgraded package.",href:"/memento-map/wedding#pricing",map:true},
{id:"plus",title:"Memento Map Plus",format:"digital",goals:["travel"],styles:["travel"],minimumBudget:129,complexity:"Low to medium · map setup and a participation plan",participation:"Recommend places the couple can experience",after:"Rank plans and track Want to Go, Planning, and Visited",why:"The $129 package adds a Travel Journal and digital exports for couples who want to act on guest ideas.",href:"/memento-map/wedding#pricing",map:true},
{id:"timeline",title:"Timeline Plus",format:"digital",goals:["story","photos"],styles:["travel","classic"],minimumBudget:179,complexity:"Medium · prepare milestones and explain dated memories",participation:"Add meaningful places and dated memories",after:"Keep the chronological relationship story growing",why:"The $179 package connects the map, guest memories, and chronological chapters with Plus planning and export features.",href:"/memento-map/wedding#pricing",map:true},
];
export function generateGuestbookIdeas(input:GeneratorInput){const eligible=OPTIONS.filter(idea=>(input.preference==="either"||idea.format===input.preference)&&(input.budget===50?idea.minimumBudget<50:idea.minimumBudget<=input.budget)&&(!idea.map||(input.goal==="travel"||input.goal==="story"||input.goal==="photos")));const ranked=eligible.map(idea=>({idea,score:(idea.goals.includes(input.goal)?8:0)+(idea.styles.includes(input.style)?3:0)+(input.participation==="quick"&&idea.complexity.startsWith("Low")?2:0)+(input.size==="large"&&idea.format==="digital"?2:0)})).sort((a,b)=>b.score-a.score||a.idea.title.localeCompare(b.idea.title));const result:Idea[]=[];for(const {idea}of ranked){if(idea.map&&result.some(item=>item.map))continue;result.push(idea);if(result.length===5)break}return result.map(idea=>({...idea,fit:`${idea.why} ${input.size==="large"?"For a larger guest list, spread the invitation across tables and avoid a single queue.":input.size==="small"?"A smaller gathering gives guests room for a more personal contribution.":"Place clear prompts where guests naturally pause."} ${input.participation==="thoughtful"?"Offer a story prompt and enough time for a longer answer.":input.participation==="multiple"?"Keep optional extras separate from the first contribution.":"Keep the first action brief and easy to understand."}`}))}
