import {readFileSync,readdirSync} from "node:fs";
import {join} from "node:path";
import {z} from "zod";
export const IDEA_TOPICS=[{slug:"guest-book-ideas",name:"Guest Book Ideas",description:"Choose what guests leave behind and how you will keep it.",image:"/brand/unity-word-tile-guest-sheet.webp"},{slug:"guest-participation",name:"Guest Participation",description:"Simple invitations that make contributing feel natural.",image:"/brand/celebrations/wedding-1.webp"},{slug:"qr-codes",name:"QR Codes",description:"Give each scan a clear purpose and an easy next step.",image:"/brand/memento-map-scan-qr.webp"},{slug:"travel-and-maps",name:"Travel & Maps",description:"Connect your people, your places, and what comes next.",image:"/brand/map-wedding-map.webp"},{slug:"wedding-memories",name:"Wedding Memories",description:"Keep the words, photos, and stories around your celebration.",image:"/brand/memento-map-digital-story.webp"},{slug:"after-the-wedding",name:"After the Wedding",description:"Bring your keepsake home and keep using what guests created.",image:"/brand/memento-map-framed-keepsake.webp"}] as const;
const link=z.object({label:z.string(),href:z.string().regex(/^\/(?!\/)/)});
const image=z.object({src:z.string().startsWith("/"),alt:z.string().min(1),caption:z.string().optional()});
const section=z.object({heading:z.string().min(1),paragraphs:z.array(z.string()).min(1),bullets:z.array(z.string()).optional(),links:z.array(link).optional(),image:image.optional(),callout:z.object({title:z.string(),text:z.string()}).optional(),table:z.object({headers:z.array(z.string()),rows:z.array(z.array(z.string()))}).optional()});
export const contentSchema=z.object({title:z.string().min(1),slug:z.string().regex(/^[a-z0-9-]+$/),description:z.string().min(1),publishedDate:z.iso.date(),updatedDate:z.iso.date(),author:z.string(),category:z.enum(IDEA_TOPICS.map(topic=>topic.slug)),tags:z.array(z.string()),heroImage:z.string().startsWith("/"),heroImageAlt:z.string().min(1),featured:z.boolean().default(false),published:z.boolean().default(true),seoTitle:z.string(),seoDescription:z.string(),relatedArticles:z.array(z.string()).default([]),relatedProduct:z.literal("memento-map-wedding").default("memento-map-wedding"),intro:z.array(z.string()).min(1),sections:z.array(section).min(1),faqs:z.array(z.object({question:z.string(),answer:z.string()})).default([]),callout:z.object({title:z.string(),text:z.string()}).optional()});
export type EditorialContent=z.infer<typeof contentSchema>;
function readCollection(folder:string){const dir=join(process.cwd(),"content",folder);return readdirSync(dir).filter(file=>file.endsWith(".json")).map(file=>contentSchema.parse(JSON.parse(readFileSync(join(dir,file),"utf8")))).filter(item=>item.published).sort((a,b)=>b.publishedDate.localeCompare(a.publishedDate)||a.title.localeCompare(b.title))}
export function articles(){return readCollection("ideas")}
export function landingPages(){return readCollection("landings")}
export function articleBySlug(slug:string){return articles().find(article=>article.slug===slug)}
export function landingBySlug(slug:string){return landingPages().find(page=>page.slug===slug)}
export function relatedArticles(article:EditorialContent){return articles().filter(item=>item.slug!==article.slug).map(item=>({item,score:(article.relatedArticles.includes(item.slug)?100:0)+(item.category===article.category?10:0)+item.tags.filter(tag=>article.tags.includes(tag)).length})).sort((a,b)=>b.score-a.score||a.item.title.localeCompare(b.item.title)).slice(0,3).map(({item})=>item)}
export function headingId(heading:string,index:number){return `${index+1}-${heading.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`}
