export const MEMENTO_MAP_TYPES={
 wedding:{name:"Wedding",shortName:"Wedding",route:"wedding",icon:"♡",description:"Turn your guests, memories, and future adventures into a map you can keep using long after the wedding.",headline:"The wedding map your guests help create.",marketingDescription:"See where everyone traveled from, collect recommendations for life together, and preserve the places behind your story.",examples:"Guest origins • Recommendations • Your story",ownerSingular:"couple",ownerPlural:"couples",participantSingular:"guest",participantPlural:"guests",eventSingular:"wedding",dashboardContributionLabel:"Guest Recommendations",emptyState:"No guest recommendations yet.",originPrompt:"Where did you travel from?",recommendationPrompt:"Recommend a place for the couple.",memoryPrompt:"Add a memory to their story.",categories:["Guest Origin","Romantic","Adventure","Food","Relaxing","Outdoors","City Trip","Beach","Weekend Trip","Bucket List"],setup:["partner_one_name","partner_two_name","event_date","event_location"]},
 family_reunion:{name:"Family Reunion",shortName:"Reunion",route:"family-reunion",icon:"⌂",description:"Bring your family's story together through the places you've lived, traveled, gathered, and made memories.",headline:"Map the places that connect your family.",marketingDescription:"Bring family origins, homes, vacations, gatherings, photos, and stories into one living geographic keepsake.",examples:"Family origins • Where we live • Memories",ownerSingular:"family",ownerPlural:"families",participantSingular:"family member",participantPlural:"family members",eventSingular:"reunion",dashboardContributionLabel:"Family Places & Memories",emptyState:"No family memories have been added yet.",originPrompt:"Where did you travel from?",recommendationPrompt:"Add a place connected to your family.",memoryPrompt:"Share a family memory.",categories:["Family Origins","Where We Live","Memories","Vacations","Important Places"],setup:["event_name","event_date","event_location","description"]},
 celebration_of_life:{name:"Celebration of Life",shortName:"Their Story",route:"celebration-of-life",icon:"✦",description:"Remember someone's story through the places, memories, photos, and experiences that shaped their life.",headline:"Remember their story through the places that shaped it.",marketingDescription:"Family and friends can gather the homes, schools, travels, favorite places, photos, videos, and memories connected to a life.",examples:"Childhood • Home • Travel • Favorite places",ownerSingular:"host",ownerPlural:"hosts",participantSingular:"contributor",participantPlural:"family and friends",eventSingular:"celebration of life",dashboardContributionLabel:"Memories & Places",emptyState:"No memories have been added yet.",originPrompt:"Add a place connected to their story.",recommendationPrompt:"Where did you make a memory together?",memoryPrompt:"Share a memory about this place.",categories:["Childhood","Home","School","Work","Travel","Favorite Places","Memories"],setup:["primary_person_name","event_date","event_location","birth_date","passing_date","description"]},
 next_chapter:{name:"Next Chapter",shortName:"Next Chapter",route:"next-chapter",icon:"↗",description:"Celebrate where you've been and collect ideas, memories, and destinations for whatever comes next.",headline:"Celebrate where they’ve been—and map what comes next.",marketingDescription:"Perfect for graduation, retirement, moving, career changes, and going-away moments that connect memories with future ideas.",examples:"Graduation • Retirement • Moving • Going Away",ownerSingular:"celebrant",ownerPlural:"celebrants",participantSingular:"friend",participantPlural:"friends and family",eventSingular:"next chapter",dashboardContributionLabel:"Recommendations for What's Next",emptyState:"No recommendations have been added yet.",originPrompt:"Share a place connected to this chapter.",recommendationPrompt:"Recommend somewhere they should visit next.",memoryPrompt:"Add a favorite memory.",categories:["Memories","Recommendations","Restaurants","Travel","Bucket List","Friends & Family"],setup:["primary_person_name","next_chapter_subtype","event_date","event_location","event_name"]},
 events_community:{name:"Events & Communities",shortName:"Community",route:"events",icon:"◎",description:"Show where your community comes from and create an interactive map of the people, places, and connections behind your event.",headline:"See the people and places behind your community.",marketingDescription:"Map attendee origins, organization locations, recommendations, memories, and community reach for events and groups of every size.",examples:"Conferences • Companies • Alumni • Nonprofits • Communities",ownerSingular:"organizer",ownerPlural:"organizers",participantSingular:"attendee",participantPlural:"attendees",eventSingular:"event",dashboardContributionLabel:"Community Contributions",emptyState:"No community contributions have been added yet.",originPrompt:"Where are you joining us from?",recommendationPrompt:"Share a place connected to this community.",memoryPrompt:"Add a community memory.",categories:["Attendees","Organization","Event Locations","Recommendations","Community"],setup:["organization_name","event_name","event_date","event_location","community_subtype"]}
} as const;
export type MementoMapType=keyof typeof MEMENTO_MAP_TYPES;
export type NextChapterSubtype="graduation"|"retirement"|"moving"|"going_away"|"career_change"|"other";
export const MEMENTO_MAP_TYPE_IDS=Object.keys(MEMENTO_MAP_TYPES) as MementoMapType[];
export function isMementoMapType(value:unknown):value is MementoMapType{return typeof value==="string"&&value in MEMENTO_MAP_TYPES}
export function resolveMementoMapType(value:unknown){return isMementoMapType(value)?value:"wedding"}
export function mapTypeConfig(value:unknown){return MEMENTO_MAP_TYPES[resolveMementoMapType(value)]}
export function typeFromRoute(route:string){return MEMENTO_MAP_TYPE_IDS.find(type=>MEMENTO_MAP_TYPES[type].route===route)}
