export type ProductKind="digital"|"physical"|"hybrid";
export type QuestionnaireField={id:string;label:string;type:"text"|"date"|"number"|"textarea"|"select"|"photo";required?:boolean;options?:string[]};
export type CatalogTier={
 key:string;productId:"map"|"deck"|"unity";productName:string;tierId:string;displayName:string;
 price:number;stripePriceEnv:string;kind:ProductKind;entitlement:string;questionnaireType:string;
 fulfillmentWorkflow:"digital_map"|"custom_print";features:string[];includedAddons:string[];allowedAddons:string[];
 publicStatus?:"available"|"coming_soon";upgradeFrom?:string[];
 nextSteps:string[];questionnaire:QuestionnaireField[];
};
const couple:QuestionnaireField[]=[{id:"partner_one",label:"First name one",type:"text",required:true},{id:"partner_two",label:"First name two",type:"text",required:true},{id:"celebration_date",label:"Celebration date",type:"date",required:true}];
const deckQuestions:QuestionnaireField[]=[{id:"palette",label:"Color palette direction",type:"text",required:true},{id:"prompt_requests",label:"Specific prompts you want included",type:"textarea",required:true},{id:"topic_categories",label:"Topics or custom categories to explore",type:"textarea",required:true},{id:"design_notes",label:"Additional design notes",type:"textarea"}];
const unityQuestions:QuestionnaireField[]=[...couple,{id:"relationship_words",label:"Words that define your relationship",type:"textarea",required:true},{id:"signature_capacity",label:"Signature spaces",type:"number",required:true},{id:"palette",label:"Color palette",type:"text",required:true},{id:"typography",label:"Typography direction",type:"text"},{id:"art_treatment",label:"Art or floral treatment",type:"text"},{id:"orientation",label:"Orientation",type:"select",options:["Portrait","Landscape"]}];
const mapNext=["Open your Memento Map dashboard.","Add your couple, celebration, and venue details directly in the dashboard.","Review your map, then share the guest link and QR code."];
const deckNext=["Review the customization saved from your deck studio.","We prepare and send your production proof.","Approve the proof before production begins."];
const unityNext=["Review the signature board saved from the design studio.","We prepare the board and ceremony-tile proof.","Approve the proof before production begins."];
const deckBespokeNext=["Complete the Bespoke creative-direction questionnaire.","We develop your custom deck and send a proof.","Approve the proof before production begins."];
const unityBespokeNext=["Complete the Bespoke art-direction questionnaire.","We develop your custom board and send a proof.","Approve the proof before production begins."];
const unityBespokeQuestions:QuestionnaireField[]=[{id:"palette",label:"Color palette",type:"text",required:true},{id:"typography",label:"Typography direction",type:"text",required:true},{id:"art_treatment",label:"Art or decoration style",type:"textarea",required:true},{id:"custom_wording",label:"Custom wording",type:"textarea"}];
const tier=(value:Omit<CatalogTier,"key">):CatalogTier=>({...value,key:`${value.productId}:${value.tierId}`});
export const PRODUCT_CATALOG:CatalogTier[]=[
 tier({productId:"map",productName:"Memento Map",tierId:"map",displayName:"Memento Map",price:9900,stripePriceEnv:"STRIPE_PRICE_MAP_BASIC",kind:"digital",entitlement:"map_basic",questionnaireType:"none",fulfillmentWorkflow:"digital_map",features:["Interactive map","Guest origins","Recommendations","QR code"],includedAddons:[],allowedAddons:[],nextSteps:mapNext,questionnaire:[]}),
 tier({productId:"map",productName:"Memento Map",tierId:"plus",displayName:"Memento Map Plus",price:12900,stripePriceEnv:"STRIPE_PRICE_MAP_PLUS",kind:"digital",entitlement:"map_plus",questionnaireType:"none",fulfillmentWorkflow:"digital_map",features:["Everything in Basic","Story editor","Travel Journal","Photos and premium exports","Likes and journey tracking"],includedAddons:[],allowedAddons:[],nextSteps:mapNext,questionnaire:[]}),
tier({productId:"map",productName:"Memento Map",tierId:"timeline-plus",displayName:"Memento Map Timeline Plus",price:17900,stripePriceEnv:"STRIPE_PRICE_MAP_TIMELINE_PLUS",kind:"hybrid",entitlement:"map_timeline_plus",questionnaireType:"none",fulfillmentWorkflow:"digital_map",publicStatus:"available",upgradeFrom:["map_basic","map_plus"],features:["Everything in Map Plus","Synchronized map and chronological timeline","Guest memories automatically update into your timeline","Private-link and public story views","Combined map-and-timeline keepsake export"],includedAddons:[],allowedAddons:[],nextSteps:mapNext,questionnaire:[]}),
 ...[["essential","Essential",13900,"STRIPE_PRICE_DECK_ESSENTIAL",50],["signature","Signature",16900,"STRIPE_PRICE_DECK_SIGNATURE",75],["story","Story",21900,"STRIPE_PRICE_DECK_STORY",95],["bespoke","Bespoke",38900,"STRIPE_PRICE_DECK_BESPOKE",175]].map(([id,name,price,env,count])=>tier({productId:"deck",productName:"Memento Deck",tierId:String(id),displayName:`Memento Deck — ${name}`,price:Number(price),stripePriceEnv:String(env),kind:"physical",entitlement:`deck_${id}`,questionnaireType:id==="bespoke"?"deck_bespoke":"none",fulfillmentWorkflow:"custom_print",features:[`Up to ${count} cards`,id==="story"?"Ten couple-specific cards and Rare Cards":id==="bespoke"?"A fully custom deck concept":"Names, date, photo, colors, and standard prompts",id==="bespoke"?"Custom categories, prompts, and visual direction":"Built in the customer deck studio"],includedAddons:id==="bespoke"?["open-10"]:[],allowedAddons:id==="bespoke"?[]:["open-5","open-10"],nextSteps:id==="bespoke"?deckBespokeNext:deckNext,questionnaire:id==="bespoke"?deckQuestions:[]})),
 tier({productId:"unity",productName:"Unity Tile Signature Board",tierId:"signature-board",displayName:"Unity Tile Signature Board",price:17900,stripePriceEnv:"STRIPE_PRICE_UNITY_STANDARD",kind:"physical",entitlement:"unity_standard",questionnaireType:"none",fulfillmentWorkflow:"custom_print",features:["18 × 24 board","Customize names, relationship words, palette, and signature capacity","Ceremony name tiles supplied separately for the unity moment","Saved design and customer proof approval"],includedAddons:[],allowedAddons:[],nextSteps:unityNext,questionnaire:[]}),
 tier({productId:"unity",productName:"Unity Tile Signature Board",tierId:"bespoke",displayName:"Unity Tile Signature Board — Bespoke",price:37800,stripePriceEnv:"STRIPE_PRICE_UNITY_BESPOKE",kind:"physical",entitlement:"unity_bespoke",questionnaireType:"unity_bespoke",fulfillmentWorkflow:"custom_print",features:["Everything in Standard","Custom art, palette, and typography","Two revision rounds"],includedAddons:[],allowedAddons:[],nextSteps:unityBespokeNext,questionnaire:unityBespokeQuestions})
];
export const ADDONS={"open-5":{name:"5-card Open When Collection",price:4000},"open-10":{name:"10-card Expanded Open When Collection",price:6000}} as const;
export function resolveCatalog(product:string,tierId:string,addons:string[]=[]){const item=PRODUCT_CATALOG.find(x=>x.productId===product&&x.tierId===tierId);if(!item)throw new Error("Invalid product or tier");if(addons.some(a=>!item.allowedAddons.includes(a)))throw new Error("Invalid add-on for this tier");return item}
export const catalogPublic=()=>PRODUCT_CATALOG.map(({questionnaire,...item})=>({...item,questionnaireFields:questionnaire.map(x=>x.id)}));
