import {createClient} from "@supabase/supabase-js";
import {supabaseServerConfig} from "./server-config";

export type HealthCheck={name:string;status:"healthy"|"degraded"|"failed";detail:string;durationMs:number};
const timed=async(name:string,run:()=>Promise<string>):Promise<HealthCheck>=>{const started=Date.now();try{return{name,status:"healthy",detail:await run(),durationMs:Date.now()-started}}catch(error){return{name,status:"failed",detail:error instanceof Error?error.message:String(error),durationMs:Date.now()-started}}};

export async function runSystemHealthChecks(){
 const config=supabaseServerConfig(),admin=createClient(config.url,config.serviceRoleKey,{auth:{persistSession:false}}),checks=await Promise.all([
  timed("Supabase read/write",async()=>{const result=await admin.from("orders").select("id",{count:"exact",head:true});if(result.error)throw result.error;return `Orders table reachable (${result.count||0} rows)`}),
  timed("Stripe API",async()=>{const key=process.env.STRIPE_SECRET_KEY||process.env.STRIPE_LIVE_SECRET_KEY;if(!key)throw new Error("Stripe secret is missing");const response=await fetch("https://api.stripe.com/v1/balance",{headers:{authorization:`Bearer ${key}`},signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`Stripe returned ${response.status}`);return"Authenticated API request succeeded"}),
  timed("Resend API",async()=>{const key=process.env.RESEND_API_KEY;if(!key)throw new Error("Resend API key is missing");const response=await fetch("https://api.resend.com/domains",{headers:{authorization:`Bearer ${key}`},signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`Resend returned ${response.status}`);return"Authenticated API request succeeded"}),
  timed("Order lifecycle integrity",async()=>{const [orders,jobs,notifications]=await Promise.all([admin.from("orders").select("id,order_status,payment_status,questionnaire_status,fulfillment_workflow,created_at").is("archived_at",null),admin.from("fulfillment_jobs").select("id,order_id,status"),admin.from("customer_notifications").select("id,status")]);if(orders.error||jobs.error||notifications.error)throw orders.error||jobs.error||notifications.error;const paid=(orders.data||[]).filter(order=>["paid","admin_bypass","test_paid"].includes(order.payment_status)),stalled=paid.filter(order=>order.order_status!=="completed"&&Date.now()-new Date(order.created_at).getTime()>30*86400000),failedJobs=(jobs.data||[]).filter(job=>job.status==="failed"),failedNotifications=(notifications.data||[]).filter(item=>item.status==="failed");if(stalled.length||failedJobs.length||failedNotifications.length)throw new Error(`${stalled.length} stalled orders, ${failedJobs.length} failed jobs, ${failedNotifications.length} failed notifications`);return `${paid.length} paid lifecycle records checked`}),
 ]),status=checks.some(check=>check.status==="failed")?"failed":"healthy",finishedAt=new Date().toISOString(),previous=await admin.from("system_health_runs").select("status").order("created_at",{ascending:false}).limit(1).maybeSingle();
 const persisted=await admin.from("system_health_runs").insert({status,checks,finished_at:finishedAt,source:"scheduled"}).select("id").single();
 if(persisted.error)console.error(JSON.stringify({level:"error",message:"health_run_persist_failed",error:persisted.error.message}));
 if(status==="failed"&&previous.data?.status!=="failed"&&process.env.RESEND_API_KEY){const recipient=process.env.SYSTEM_HEALTH_ALERT_EMAIL||process.env.ADMIN_EMAIL||"jonahnr@gmail.com";const alert=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL||"Memento House <orders@mementohouse.com>",to:[recipient],subject:"Memento House system health needs attention",html:`<h1>System health check failed</h1>${checks.filter(check=>check.status==="failed").map(check=>`<p><b>${check.name}</b>: ${check.detail}</p>`).join("")}<p>${finishedAt}</p>`}),signal:AbortSignal.timeout(8000)});if(!alert.ok)console.error(JSON.stringify({level:"error",message:"health_alert_failed",status:alert.status}))}
 console.log(JSON.stringify({level:status==="healthy"?"info":"error",message:"system_health_completed",status,checks,finishedAt}));
 return{status,checks,finishedAt,id:persisted.data?.id||null};
}
