/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- Comparison tables scroll horizontally; keyboard users need a focusable scroll region. */
import "./marketing.css";
import Image from "next/image";
import type {ReactNode} from "react";
import {IDEA_TOPICS,relatedArticles,headingId,type EditorialContent} from "../../lib/ideas-content";
import {breadcrumbSchema,jsonLd,MARKETING_SITE} from "../../lib/marketing-seo";
import {MarketingLink,MarketingView,ViewDemoCTA} from "./analytics";
export function MarketingShell({children}:{children:ReactNode}){return <main className="marketingPage"><nav className="marketingNav" aria-label="Memento House"><a href="/" className="houseBrand"><Image src="/brand/memento-house-logo.webp" alt="Memento House" width={52} height={52}/><div>Memento House<small>Made for the moment. Kept for a lifetime.</small></div></a><div><a href="/memento-map">Memento Map</a><a href="/ideas">Ideas</a><a href="/wedding-guest-book-quiz">Find your guestbook</a></div></nav>{children}<footer className="marketingFooter"><p>Memento House · Made for the moment. Kept for a lifetime.</p><div><a href="/ideas">Ideas</a><a href="/memento-map/wedding">Wedding Memento Map</a><a href="/guides">Planning guides</a><a href="/contact">Contact</a></div></footer></main>}
export function Breadcrumbs({items}:{items:{name:string;href:string}[]}){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(breadcrumbSchema(items))}}/><nav className="marketingBreadcrumbs" aria-label="Breadcrumb"><ol>{items.map((item,index)=><li key={item.href}>{index===items.length-1?<span aria-current="page">{item.name}</span>:<a href={item.href}>{item.name}</a>}</li>)}</ol></nav></>}
export function MementoMapCallout({source,title="A guestbook built around people, places, and memories.",text="Guests add places and recommendations to one shared map. Map Plus helps you turn suggestions into future trips; Timeline Plus connects dated memories and milestones.",demoLabel="View Wedding Demo"}:{source:string;title?:string;text?:string;demoLabel?:string}){return <aside className="marketingCallout"><div className="eyebrow">Meet Memento Map</div><h2>{title}</h2><p>{text}</p><div className="marketingActions"><MarketingLink href="/memento-map/wedding" source={source} label="See How It Works" event="article_product_cta_clicked" className="button gold">See How It Works →</MarketingLink><ViewDemoCTA source={source} label={demoLabel}/></div></aside>}
export function ArticleCard({article,source,related=false}:{article:EditorialContent;source:string;related?:boolean}){return <article className="ideaCard"><MarketingLink href={`/ideas/${article.slug}`} source={source} label={article.title} event={related?"related_article_clicked":undefined} className="ideaCardLink"><Image src={article.heroImage} alt={article.heroImageAlt} width={700} height={460} sizes="(max-width: 700px) 100vw, 33vw"/><small>{IDEA_TOPICS.find(topic=>topic.slug===article.category)?.name}</small><h3>{article.title}</h3><p>{article.description}</p><b>Read the story →</b></MarketingLink></article>}
export function RelatedContent({article,source}:{article:EditorialContent;source:string}){return <section className="marketingRelated"><h2>Keep Exploring</h2><div className="ideaGrid">{relatedArticles(article).map(item=><ArticleCard article={item} source={source} related key={item.slug}/>)}</div><MarketingLink href="/tools/wedding-guest-book-idea-generator" source={source} label="Try the idea generator">Build a shortlist for your wedding →</MarketingLink></section>}
const date=(value:string)=>new Intl.DateTimeFormat("en-US",{dateStyle:"long",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"));
export function EditorialPage({content,landing=false}:{content:EditorialContent;landing?:boolean}){
 const path=landing?`/${content.slug}`:`/ideas/${content.slug}`,topic=IDEA_TOPICS.find(item=>item.slug===content.category)!;
 const crumbs=landing?[{name:"Home",href:"/"},{name:content.title,href:path}]:[{name:"Home",href:"/"},{name:"Ideas",href:"/ideas"},{name:topic.name,href:`/ideas/${topic.slug}`},{name:content.title,href:path}];
 const schema={"@context":"https://schema.org","@type":"Article",headline:content.title,description:content.description,image:MARKETING_SITE+content.heroImage,datePublished:content.publishedDate,dateModified:content.updatedDate,author:{"@type":"Organization",name:content.author},publisher:{"@type":"Organization",name:"Memento House",logo:{"@type":"ImageObject",url:MARKETING_SITE+"/brand/memento-house-logo.webp"}},mainEntityOfPage:MARKETING_SITE+path};
 return <MarketingShell><MarketingView event={landing?"seo_landing_view":"ideas_article_viewed"} properties={landing?{page:path,topic:topic.name}:{slug:content.slug,category:topic.name}}/>{!landing&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/>}<Breadcrumbs items={crumbs}/><header className="editorialHero"><div className="eyebrow">{topic.name}</div><h1>{content.title}</h1>{content.intro.map(text=><p key={text}>{text}</p>)}{landing?<div className="marketingActions"><MarketingLink className="button gold" href="#explore" source={path} label="Explore the Options">Explore the Options ↓</MarketingLink><ViewDemoCTA source={path} label="View Interactive Map Demo"/></div>:<p className="articleByline">By {content.author} · Published {date(content.publishedDate)} · Updated {date(content.updatedDate)}</p>}<Image src={content.heroImage} alt={content.heroImageAlt} width={1400} height={850} priority sizes="(max-width: 1000px) 100vw, 1000px"/></header><div className="editorialLayout"><aside className="articleToc"><details open><summary>On this page</summary><ol>{content.sections.map((section,index)=><li key={section.heading}><a href={`#${headingId(section.heading,index)}`}>{section.heading}</a></li>)}</ol></details></aside><article className="editorialBody" id="explore">{content.sections.map((section,index)=><section id={headingId(section.heading,index)} key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(text=><p key={text}>{text}</p>)}{section.bullets&&<ul>{section.bullets.map(text=><li key={text}>{text}</li>)}</ul>}{section.image&&<figure><Image src={section.image.src} alt={section.image.alt} width={1000} height={700} sizes="(max-width: 700px) 100vw, 700px"/>{section.image.caption&&<figcaption>{section.image.caption}</figcaption>}</figure>}{section.table&&<div className="articleTable" role="region" aria-label={`${section.heading} comparison`} tabIndex={0}><table><caption>{section.heading}</caption><thead><tr>{section.table.headers.map(header=><th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{section.table.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>j===0?<th scope="row" key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}{section.callout&&<aside className="articleNote"><h3>{section.callout.title}</h3><p>{section.callout.text}</p></aside>}{section.links&&<div className="articleLinks">{section.links.map(link=><MarketingLink key={link.href} href={link.href} source={path} label={link.label}>{link.label} →</MarketingLink>)}</div>}</section>)}{content.faqs.length>0&&<section className="editorialFaq"><h2>Questions worth asking</h2>{content.faqs.map(faq=><details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>}<MementoMapCallout source={path} {...content.callout}/></article></div><RelatedContent article={content} source={path}/></MarketingShell>
}
