"use client";
import {useRef,useState} from "react";
import {sendGAEvent} from "@next/third-parties/google";
import {QUIZ_QUESTIONS,quizRecommendation,generateGuestbookIdeas,type GeneratorInput} from "../../lib/guestbook-tools";
import {MarketingLink,ViewDemoCTA} from "./analytics";
export function GuestbookQuiz(){const [step,setStep]=useState(0),[answers,setAnswers]=useState<number[]>([]),[result,setResult]=useState<ReturnType<typeof quizRecommendation>|null>(null),[started,setStarted]=useState(false);const focus=useRef<HTMLHeadingElement>(null);
 function select(choice:number){if(!started){sendGAEvent("event","quiz_started");setStarted(true)}setAnswers(previous=>{const next=[...previous];next[step]=choice;return next})}
 function next(){if(answers[step]===undefined)return;if(step===QUIZ_QUESTIONS.length-1){const recommendation=quizRecommendation(answers);setResult(recommendation);sendGAEvent("event","quiz_completed",{recommendation:recommendation.title})}else setStep(step+1);setTimeout(()=>focus.current?.focus(),0)}
 const question=QUIZ_QUESTIONS[step],source="/wedding-guest-book-quiz";
 return <section className="marketingInteractive" aria-label="Guestbook quiz">{result?<><h2 ref={focus} tabIndex={-1}>{result.title} Looks Like Your Best Match</h2><p>{result.description}</p><h3>You told us:</h3><ul className="quizReasons">{result.reasons.map(reason=><li key={reason.question}><small>{reason.question}</small><b>{reason.answer}</b></li>)}</ul><p className="toolNote">This is a preference-based starting point, not a guarantee. Compare setup needs and current package details before choosing.</p><div className="marketingActions"><MarketingLink href={result.href} source={source} label={result.cta} className="button gold">{result.cta} →</MarketingLink><ViewDemoCTA source={source}/><button className="button light" onClick={()=>{setStep(0);setAnswers([]);setResult(null);setStarted(false)}}>Retake quiz</button></div></>:<><small>QUESTION {step+1} OF {QUIZ_QUESTIONS.length}</small><progress max={QUIZ_QUESTIONS.length} value={step+1} aria-label="Quiz progress"/><h2 ref={focus} tabIndex={-1}>{question.question}</h2><fieldset><legend className="srOnly">{question.question}</legend><div className="quizChoices">{question.choices.map((choice,index)=><label className={answers[step]===index?"selected":""} key={choice.label}><input type="radio" name={`question-${step}`} checked={answers[step]===index} onChange={()=>select(index)}/><span>{choice.label}</span></label>)}</div></fieldset><div className="marketingActions"><button className="button light" disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button className="button gold" disabled={answers[step]===undefined} onClick={next}>{step===QUIZ_QUESTIONS.length-1?"See my result":"Next →"}</button></div></>}</section>
}
export function GuestbookGenerator(){const [input,setInput]=useState<GeneratorInput>({size:"medium",style:"relaxed",preference:"either",goal:"messages",budget:100,participation:"quick"}),[results,setResults]=useState<ReturnType<typeof generateGuestbookIdeas>|null>(null);const started=useRef(false),output=useRef<HTMLHeadingElement>(null);
 function update(key:keyof GeneratorInput,value:string){if(!started.current){sendGAEvent("event","idea_generator_started");started.current=true}setInput(previous=>({...previous,[key]:key==="budget"?Number(value):value}));setResults(null)}
 function generate(event:React.FormEvent){event.preventDefault();if(!started.current){sendGAEvent("event","idea_generator_started");started.current=true}setResults(generateGuestbookIdeas(input));sendGAEvent("event","idea_generator_completed",{format:input.preference,goal:input.goal,budget:input.budget});setTimeout(()=>{output.current?.focus();output.current?.scrollIntoView({block:"start",behavior:"smooth"})},0)}
 const fields:{key:keyof GeneratorInput;label:string;options:[string,string][]}[]=[{key:"size",label:"Wedding size",options:[["small","Under 50 guests"],["medium","50–150 guests"],["large","More than 150 guests"]]},{key:"style",label:"Wedding style",options:[["classic","Classic & sentimental"],["travel","Travel-inspired"],["creative","Creative & playful"],["relaxed","Relaxed & social"]]},{key:"preference",label:"Physical or digital?",options:[["either","Open to both"],["physical","Physical keepsake"],["digital","Digital experience"]]},{key:"goal",label:"Your primary goal",options:[["messages","Messages & advice"],["signatures","Signatures to display"],["photos","Photos & recordings"],["travel","Travel recommendations"],["story","A growing story"]]},{key:"budget",label:"Planning budget",options:[["50","Under $50"],["100","Up to $100"],["150","Up to $150"],["1000","$150 or more"]]},{key:"participation",label:"Guest participation style",options:[["quick","Quick contribution"],["thoughtful","Thoughtful story"],["multiple","Several optional ways to join"]]}];
 return <><form className="marketingInteractive generatorForm" onSubmit={generate}><div className="generatorInputs">{fields.map(field=><label key={field.key}>{field.label}<select value={input[field.key]} onChange={event=>update(field.key,event.target.value)}>{field.options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>)}</div><p className="toolNote">Budget bands are planning filters, not vendor quotes. DIY and recording ideas assume materials or devices you may already have; verify supplies and any service fees. Memento Map package prices are shown in its current product details.</p><button className="button gold">Generate my ideas →</button></form>{results&&<section className="generatorResults" aria-live="polite"><h2 ref={output} tabIndex={-1}>Five ideas for your wedding</h2><p>Compare the guest action and what you will keep afterward.</p>{results.map((idea,index)=><article key={idea.id}><small>{String(index+1).padStart(2,"0")} · {idea.format}</small><h3>{idea.title}</h3><p>{idea.fit}</p><dl><div><dt>Estimated complexity</dt><dd>{idea.complexity}</dd></div><div><dt>How guests join</dt><dd>{idea.participation}</dd></div><div><dt>After the wedding</dt><dd>{idea.after}</dd></div></dl><MarketingLink source="/tools/wedding-guest-book-idea-generator" href={idea.href} label={`Explore ${idea.title}`}>Explore this idea →</MarketingLink>{idea.map&&<ViewDemoCTA source="/tools/wedding-guest-book-idea-generator" className="textLink"/>}</article>)}</section>}</>
}
