"use client";
import {Suspense,useCallback,useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import {getSupabaseBrowserClient} from "../../lib/supabase";
import {friendlyAuthError} from "../../lib/auth-message";
import {canonicalAuthOrigin,moveToCanonicalAuth} from "../../lib/oauth-origin";

function SignupContent(){
 const params=useSearchParams(),returnTo=params.get("return_to")||"/account",[mode,setMode]=useState<"signup"|"login">("signup"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[awaitingConfirmation,setAwaitingConfirmation]=useState(false),oauthStarted=useRef(false);
 const google=useCallback(async()=>{if(oauthStarted.current)return;oauthStarted.current=true;if(moveToCanonicalAuth(`/signup?return_to=${encodeURIComponent(returnTo)}&oauth=google`))return;const client=getSupabaseBrowserClient();if(!client){oauthStarted.current=false;setMessage("Account service is not configured.");return}setBusy(true);setMessage("");const result=await client.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${canonicalAuthOrigin()}/auth/callback?next=${encodeURIComponent(returnTo)}`,queryParams:{prompt:"select_account"},skipBrowserRedirect:true}});if(result.error||!result.data.url){oauthStarted.current=false;setMessage(friendlyAuthError(result.error?.message||"Google did not return a sign-in URL."));setBusy(false);return}location.assign(result.data.url)},[returnTo]);
 useEffect(()=>{if(params.get("oauth")!=="google")return;const timer=setTimeout(()=>void google(),0);return()=>clearTimeout(timer)},[google,params]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");setAwaitingConfirmation(false);const client=getSupabaseBrowserClient();if(!client){setMessage("Account service is not configured.");setBusy(false);return}if(mode==="login"){const result=await client.auth.signInWithPassword({email,password});if(result.error){setMessage(friendlyAuthError(result.error.message));setBusy(false);return}location.href=returnTo;return}const result=await client.auth.signUp({email,password,options:{emailRedirectTo:`${canonicalAuthOrigin()}/auth/callback?next=${encodeURIComponent(returnTo)}`,data:{account_type:"customer"}}});if(result.error)setMessage(friendlyAuthError(result.error.message));else if(result.data.session)location.href=returnTo;else{setAwaitingConfirmation(true);setMessage(`We sent a confirmation link to ${email}. Confirm your email, then return here and sign in.`)}setBusy(false)}
 async function resend(){const client=getSupabaseBrowserClient();if(!client||!email){setMessage("Enter the email address you used to create the account first.");return}setBusy(true);setMessage("");const result=await client.auth.resend({type:"signup",email,options:{emailRedirectTo:`${canonicalAuthOrigin()}/auth/callback?next=${encodeURIComponent(returnTo)}`}});setBusy(false);if(result.error)setMessage(friendlyAuthError(result.error.message));else{setAwaitingConfirmation(true);setMessage(`Supabase accepted a new confirmation request for ${email}. Check spam and open only the newest message. If the address already belongs to an account, sign in or reset its password instead.`)}}
 return <main className="auth"><a href="/" className="brand"><img src="/brand/memento-house-logo.webp" alt="Memento House"/><span>Memento House</span></a><form onSubmit={submit}><div className="eyebrow">Your private Memento House account</div><h1>{mode==="signup"?"Keep your celebrations in one place.":"Welcome back."}</h1><p>Your account connects purchases, saved customizations, proofs, approvals, shipping updates, and order history.</p><button type="button" className="button light oauthButton" disabled={busy} onClick={()=>void google()}>Continue with Google</button><div className="authDivider"><span>or use email</span></div><label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={10} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p className={awaitingConfirmation?"authSuccess":"authError"}>{message}</p>}{awaitingConfirmation&&<div className="authHelp"><p>Links are time-sensitive. If the first one expired, request a new link and open only the newest message.</p><button type="button" className="button light" disabled={busy} onClick={resend}>Resend confirmation email</button></div>}<button className="button gold" disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create my account →":"Sign in →"}</button><button type="button" className="textLink" onClick={()=>{setMode(mode==="signup"?"login":"signup");setMessage("");setAwaitingConfirmation(false)}}>{mode==="signup"?"Already have an account? Sign in":"Need an account? Create one"}</button><small className="authTroubleshoot">Having trouble? Confirm you are using the newest email link, then try signing in. For help, <a href="/contact">contact Memento House</a>.</small></form></main>
}

export default function Signup(){return <Suspense fallback={<main className="auth"><p>Preparing your account…</p></main>}><SignupContent/></Suspense>}
