import {createClient} from "@supabase/supabase-js";
import {createStreamTusUpload,cloudflareStreamConfig} from "../../../../lib/cloudflare-stream";
import {videoLimits} from "../../../../lib/media";
import {resolveMapTier,tierIncludesPlus} from "../../../../lib/map-entitlement";
import {supabaseServerConfig} from "../../../../lib/server-config";

const clean=(value:unknown,max:number)=>String(value||"").trim().slice(0,max);
const digest=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,"0")).join("");
export async function POST(request:Request){
 const{url,serviceRoleKey:key}=supabaseServerConfig(),stream=cloudflareStreamConfig();if(!url||!key)return Response.json({error:"Media service is unavailable."},{status:503});if(!stream.accountId||!stream.apiToken)return Response.json({error:"Video uploads are not configured yet."},{status:503});
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return Response.json({error:"Invalid upload request."},{status:400});
 const weddingId=clean(body.weddingId,50),fileName=clean(body.fileName,180),mimeType=clean(body.mimeType,100),anonymousId=clean(body.anonymousId,100),fileSize=Number(body.fileSize);if(!weddingId||!fileName||!mimeType.startsWith("video/")||!Number.isInteger(fileSize)||fileSize<1)return Response.json({error:"Choose a valid video file."},{status:400});
 const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),wedding=await admin.from("weddings").select("id,owner_user_id,status,contribution_status").eq("id",weddingId).maybeSingle();if(!wedding.data||wedding.data.status!=="active")return Response.json({error:"This Memento is unavailable."},{status:404});
 const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,""),auth=token?await admin.auth.getUser(token):null,user=auth?.data.user,owner=user?.id===wedding.data.owner_user_id,uploaderKind=owner?"owner":"guest";
 if(!owner&&(wedding.data.contribution_status==="closed"||wedding.data.contribution_status==="paused"||anonymousId.length<10))return Response.json({error:"This Memento is not accepting guest media right now."},{status:403});
 const ownerAccount=await admin.auth.admin.getUserById(wedding.data.owner_user_id),tier=await resolveMapTier(admin,wedding.data.owner_user_id,ownerAccount.data.user?.user_metadata,ownerAccount.data.user?.email);if(!tierIncludesPlus(tier))return Response.json({error:"Media uploads require Memento Map Plus or Timeline Plus."},{status:403});
 const limits=videoLimits(tier);if(fileSize>limits.maxFileBytes)return Response.json({error:"Choose a video smaller than 500 MB."},{status:400});
 const ip=clean(request.headers.get("cf-connecting-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",80),actorHash=await digest(owner?`owner:${user!.id}`:`${ip}:${anonymousId}`),claimed=await admin.rpc("claim_guest_action",{p_wedding_id:weddingId,p_actor_hash:actorHash,p_action:"video_authorize",p_limit:owner?20:4,p_window_seconds:3600});if(claimed.error)return Response.json({error:"Video upload limits could not be checked."},{status:503});if(!claimed.data)return Response.json({error:"Too many video upload attempts. Please try again later."},{status:429});
 const mediaId=crypto.randomUUID(),expiry=new Date(Date.now()+24*60*60*1000).toISOString(),reserved=await admin.rpc("reserve_video_upload",{p_wedding_id:weddingId,p_media_id:mediaId,p_actor_hash:actorHash,p_uploader_kind:uploaderKind,p_uploader_user_id:owner?user!.id:null,p_file_name:fileName,p_mime_type:mimeType,p_file_size_bytes:fileSize,p_max_total_seconds:limits.maxSeconds,p_max_video_count:limits.maxVideos,p_max_individual_seconds:limits.maxIndividualSeconds,p_expires_at:expiry});if(reserved.error)return Response.json({error:"Video quota could not be reserved."},{status:503});const quota=reserved.data as {ok:boolean;reservationSeconds?:number;remainingSeconds?:number;usedSeconds?:number;videoCount?:number};if(!quota?.ok)return Response.json({error:quota?.remainingSeconds===0?"This Memento has reached its video upload limit.":"This Memento has reached its video count limit.",usage:quota},{status:409});
 try{const upload=await createStreamTusUpload({fileSize,maxDurationSeconds:Number(quota.reservationSeconds),expiry,creator:weddingId.replaceAll("-","").slice(0,32),mediaId,fileName}),updated=await admin.from("media_assets").update({cloudflare_uid:upload.uid,status:"uploading",updated_at:new Date().toISOString()}).eq("id",mediaId);if(updated.error)throw updated.error;return Response.json({mediaId,uploadUrl:upload.uploadUrl,maxDurationSeconds:quota.reservationSeconds,remainingSeconds:quota.remainingSeconds,usedSeconds:quota.usedSeconds,maxSeconds:limits.maxSeconds})}catch(error){await admin.rpc("release_video_reservation",{p_media_id:mediaId,p_error:error instanceof Error?error.message:"Upload authorization failed"});return Response.json({error:"A secure video upload could not be created. Please try again."},{status:502})}
}
