import {createClient} from "@supabase/supabase-js";
import {fulfillPurchase} from "../../../lib/fulfillment";
import {resolveCatalog} from "../../../lib/product-catalog";
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,"0")).join("");
const safeEqual=(a:string,b:string)=>{if(a.length!==b.length)return false;let mismatch=0;for(let i=0;i<a.length;i++)mismatch|=a.charCodeAt(i)^b.charCodeAt(i);return mismatch===0};
export async function POST(request:Request){
 const secret=process.env.STRIPE_WEBHOOK_SECRET,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY,url=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!secret||!serviceKey||!url)return new Response("Webhook is not configured",{status:503});
 const body=await request.text(),signature=request.headers.get("stripe-signature")||"",pairs=signature.split(",").map(v=>v.split("=")),timestamp=pairs.find(x=>x[0]==="t")?.[1],signatures=pairs.filter(x=>x[0]==="v1").map(x=>x[1]);if(!timestamp||Math.abs(Date.now()/1000-Number(timestamp))>300)return new Response("Expired signature",{status:400});
 const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),expected=hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(`${timestamp}.${body}`)));if(!signatures.some(v=>safeEqual(expected,v)))return new Response("Invalid signature",{status:400});
 const event=JSON.parse(body),admin=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),existing=await admin.from("stripe_events").select("status,attempts").eq("event_id",event.id).maybeSingle();if(existing.data?.status==="processed")return new Response("ok");
 if(existing.data)await admin.from("stripe_events").update({status:"processing",attempts:(existing.data.attempts||1)+1,updated_at:new Date().toISOString()}).eq("event_id",event.id);else{const claimed=await admin.from("stripe_events").insert({event_id:event.id,event_type:event.type});if(claimed.error&&claimed.error.code!=="23505")return new Response(claimed.error.message,{status:500})}
 try{const session=event.data?.object;if(event.type==="checkout.session.completed"&&session?.payment_status==="paid"){
   const email=String(session.customer_details?.email||"").toLowerCase(),product=String(session.metadata?.product||""),tier=String(session.metadata?.tier||""),addons=String(session.metadata?.addons||"").split(",").filter(Boolean),item=resolveCatalog(product,tier,addons);if(!email||session.metadata?.catalog_key!==item.key)throw new Error("Invalid checkout metadata");
   await fulfillPurchase(admin,{source:"stripe",sourceId:String(session.id),eventId:event.id,email,name:String(session.customer_details?.name||""),product,tier,addons,amount:Number(session.amount_total||0),currency:String(session.currency||"usd"),customizationId:String(session.metadata?.customization_id||"")||null,paymentIntentId:String(session.payment_intent||"")||null});
 }else if(["charge.refunded","checkout.session.expired"].includes(event.type)){const reference=String(session?.checkout_session||session?.id||"");if(reference)await admin.from("orders").update({order_status:event.type==="charge.refunded"?"refunded":"cancelled",updated_at:new Date().toISOString()}).or(`stripe_session_id.eq.${reference},stripe_payment_intent_id.eq.${String(session?.payment_intent||session?.id||"")}`)}
 await admin.from("stripe_events").update({status:"processed",processed_at:new Date().toISOString(),error_message:null,updated_at:new Date().toISOString()}).eq("event_id",event.id);return new Response("ok")
 }catch(error){const message=error instanceof Error?error.message:"Webhook processing failed";await admin.from("stripe_events").update({status:"failed",error_message:message,updated_at:new Date().toISOString()}).eq("event_id",event.id);return new Response(message,{status:500})}
}
