"use client";
import {useEffect,useRef,useState} from "react";
export type GeoPin={id:string|number;place:string;guest:string;message:string;category:string;likes:number;lng:number;lat:number;status?:string};
export type StoryPin={label:string;place:string;lng:number;lat:number};
const rasterStyle:any={version:8,sources:{openstreetmap:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}},layers:[{id:"openstreetmap",type:"raster",source:"openstreetmap",paint:{"raster-saturation":-.65,"raster-brightness-min":.16,"raster-brightness-max":.94,"raster-contrast":.04}}]};
export function AdventureMap({recommendations,stories,tab,selected,onSelect,onSnapshotReady,activeLayers}:{recommendations:GeoPin[];stories:StoryPin[];tab:string;selected:GeoPin|null;onSelect:(pin:GeoPin|null)=>void;onSnapshotReady?:(capture:()=>string)=>void;activeLayers?:string[]}){
 const container=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),markersRef=useRef<any[]>([]),[ready,setReady]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{if(!container.current||mapRef.current)return;const maplibre=await import("maplibre-gl");if(cancelled||!container.current)return;const map=new maplibre.Map({container:container.current,style:rasterStyle,center:[-20,35],zoom:1.2,renderWorldCopies:false,attributionControl:false,preserveDrawingBuffer:true});map.addControl(new maplibre.NavigationControl({showCompass:false}),"top-right");map.addControl(new maplibre.AttributionControl({compact:true}),"bottom-right");map.on("load",()=>setReady(true));mapRef.current=map})();return()=>{cancelled=true;markersRef.current.forEach(m=>m.remove());mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map||!ready)return;let cancelled=false;(async()=>{const maplibre=await import("maplibre-gl");if(cancelled)return;markersRef.current.forEach(m=>m.remove());markersRef.current=[];const bounds=new maplibre.LngLatBounds(),layers=activeLayers||[];const visible=layers.length?recommendations.filter(r=>(r.category==="Guest Origin"&&layers.includes("origins"))||(r.category!=="Guest Origin"&&r.status!=="visited"&&layers.includes("recommendations"))||(r.status==="visited"&&layers.includes("visited"))):tab==="all"?recommendations:tab==="recommendations"?recommendations.filter(r=>r.category!=="Guest Origin"&&r.status!=="visited"):tab==="origins"?recommendations.filter(r=>r.category==="Guest Origin"):tab==="visited"?recommendations.filter(r=>r.status==="visited"):[];visible.forEach(pin=>{const el=document.createElement("button");const kind=pin.category==="Guest Origin"?"originGeo":pin.category==="Our Story"?"storyGeo":pin.status==="visited"?"visitedGeo":"recommendationGeo";el.className="geoMarker "+kind+(selected?.id===pin.id?" selectedGeo":"");el.textContent=pin.status==="visited"?"✓":"✦";el.setAttribute("aria-label",pin.place);el.onclick=()=>onSelect(pin);markersRef.current.push(new maplibre.Marker({element:el,anchor:"bottom"}).setLngLat([pin.lng,pin.lat]).addTo(map));bounds.extend([pin.lng,pin.lat])});if(tab==="story"||layers.includes("story"))stories.forEach(story=>{const el=document.createElement("button");el.className="geoMarker storyGeo";el.textContent="♥";el.title=`${story.label}: ${story.place}`;markersRef.current.push(new maplibre.Marker({element:el,anchor:"bottom"}).setLngLat([story.lng,story.lat]).addTo(map));bounds.extend([story.lng,story.lat])});if(!bounds.isEmpty())map.fitBounds(bounds,{padding:{top:70,bottom:70,left:70,right:70},maxZoom:tab==="story"?5:4,duration:500});else map.flyTo({center:[-20,35],zoom:1.2,duration:500})})();return()=>{cancelled=true}},[recommendations,stories,tab,selected,onSelect,ready,activeLayers]);
 useEffect(()=>{if(!ready||!onSnapshotReady)return;const map=mapRef.current;onSnapshotReady(()=>{const source=map.getCanvas() as HTMLCanvasElement,canvas=document.createElement("canvas");canvas.width=source.width;canvas.height=source.height;const ctx=canvas.getContext("2d")!;ctx.drawImage(source,0,0);recommendations.forEach(pin=>{const p=map.project([pin.lng,pin.lat]),scale=source.width/source.clientWidth;ctx.beginPath();ctx.arc(p.x*scale,p.y*scale,13*scale,0,Math.PI*2);ctx.fillStyle=pin.category==="Guest Origin"?"#4f8067":pin.category==="Our Story"?"#a86f78":"#557fa5";ctx.fill();ctx.strokeStyle="#fffdf8";ctx.lineWidth=3*scale;ctx.stroke();ctx.fillStyle="#fff";ctx.font=`bold ${12*scale}px Georgia`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(pin.status==="visited"?"✓":"✦",p.x*scale,p.y*scale)});return canvas.toDataURL("image/png")})},[ready,onSnapshotReady,recommendations]);
 return <div ref={container} className="realMap" aria-label="Interactive world map with accurate geographic locations"/>;
}
