"use client";
import {useEffect,useState} from "react";
type Place={name:string;lat:number;lng:number;id:string};
export function LocationSearch({value,onSelect}:{value:string;onSelect:(place:Place)=>void}){
 const[query,setQuery]=useState(value),[results,setResults]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>setQuery(value),[value]);
 useEffect(()=>{if(query.trim().length<3||query===value){setResults([]);return}const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setError("");try{const response=await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(query.trim())}&limit=7&lang=en`,{signal:controller.signal});if(!response.ok)throw new Error();const json=await response.json();setResults((json.features||[]).map((feature:any)=>{const p=feature.properties||{},street=[p.housenumber,p.street].filter(Boolean).join(" "),parts=[street,p.name,p.district,p.city,p.county,p.state,p.postcode,p.country].filter(Boolean),label=parts.filter((x:string,index:number,array:string[])=>array.indexOf(x)===index).join(", ");return{name:label||p.name||query,lng:Number(feature.geometry.coordinates[0]),lat:Number(feature.geometry.coordinates[1]),id:String(p.osm_type||"")+String(p.osm_id||"")}}).filter((p:Place)=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)))}catch(e){if((e as Error).name!=="AbortError")setError("Location search is unavailable right now. Please try again.")}finally{setLoading(false)}},350);return()=>{clearTimeout(timer);controller.abort()}},[query,value]);
 return <div className="locationSearch"><input required aria-label="Search for a real address or location" placeholder="Start with a city, venue, address, or landmark…" value={query} onChange={e=>setQuery(e.target.value)} autoComplete="street-address"/>{loading&&<span className="searchStatus">Searching real places…</span>}{error&&<span className="searchError">{error}</span>}{results.length>0&&<ul>{results.map(place=><li key={place.id+place.name}><button type="button" onClick={()=>{setQuery(place.name);setResults([]);onSelect(place)}}><b>{place.name}</b><small>Exact pin: {place.lat.toFixed(5)}, {place.lng.toFixed(5)}</small></button></li>)}</ul>}{value&&query===value&&<div className="coordinateConfirmed">✓ Address selected and coordinates saved</div>}</div>
}
