import {createClient} from "@supabase/supabase-js";
import {summarizeVideoUsage} from "../../../lib/media";
import {resolveMapTier} from "../../../lib/map-entitlement";
import {supabaseServerConfig} from "../../../lib/server-config";
import {cloudflareStreamConfig,deleteStreamVideo,getStreamStorageUsage} from "../../../lib/cloudflare-stream";

const fields="id,media_type,status,public_url,playback_url,thumbnail_url,cloudflare_uid,alt_text,duration_seconds,reserved_seconds,timeline_entry_id,story_location_id,destination_id,error_message,created_at";
async function context(request:Request,weddingId:string){const{url,serviceRoleKey:key}=supabaseServerConfig();if(!url||!key)return null;const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),wedding=await admin.from("weddings").select("id,owner_user_id,status").eq("id",weddingId).maybeSingle();if(!wedding.data)return null;const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,""),auth=token?await admin.auth.getUser(token):null,owner=auth?.data.user?.id===wedding.data.owner_user_id,account=await admin.auth.admin.getUserById(wedding.data.owner_user_id),tier=await resolveMapTier(admin,wedding.data.owner_user_id,account.data.user?.user_metadata,account.data.user?.email);return{admin,wedding:wedding.data,owner,user:auth?.data.user,tier}}
export async function GET(request:Request){const params=new URL(request.url).searchParams,weddingId=params.get("weddingId")||"",value=await context(request,weddingId);if(!value||value.wedding.status!=="active")return Response.json({error:"Memento not found."},{status:404});const now=new Date().toISOString(),stale=await value.admin.from("media_assets").select("cloudflare_uid").eq("wedding_id",weddingId).in("status",["reserved","uploading","processing"]).lt("expires_at",now);await value.admin.from("media_assets").update({status:"expired",reserved_seconds:0,updated_at:now}).eq("wedding_id",weddingId).in("status",["reserved","uploading","processing"]).lt("expires_at",now);await Promise.allSettled((stale.data||[]).filter(row=>row.cloudflare_uid).map(row=>deleteStreamVideo(row.cloudflare_uid!)));let query=value.admin.from("media_assets").select(fields).eq("wedding_id",weddingId).is("deleted_at",null).order("created_at",{ascending:false});if(!value.owner)query=query.eq("id","00000000-0000-0000-0000-000000000000");for(const[key,column]of[["timelineEntryId","timeline_entry_id"],["storyLocationId","story_location_id"],["destinationId","destination_id"]] as const){const target=params.get(key);if(target)query=query.eq(column,target)}const[result,usageRows,storage]=await Promise.all([query,value.admin.from("media_assets").select("status,duration_seconds,reserved_seconds").eq("wedding_id",weddingId).eq("media_type","video").is("deleted_at",null),getStreamStorageUsage()]),stream=cloudflareStreamConfig(),configured=Boolean(stream.accountId&&stream.apiToken&&stream.webhookSecret&&!result.error&&!usageRows.error),storageFull=Boolean(storage&&storage.limitMinutes-storage.usedMinutes<1);return Response.json({assets:result.data||[],usage:summarizeVideoUsage(usageRows.data||[],value.tier),videoEnabled:configured&&!storageFull,videoUnavailableReason:storageFull?"storage_capacity":configured?null:"configuration"},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:Request){const body=await request.json().catch(()=>null) as {weddingId?:string;mediaId?:string;targetType?:string;targetId?:string}|null,value=body?.weddingId?await context(request,body.weddingId):null;if(!value?.owner||!body?.mediaId||!body.targetId)return Response.json({error:"Unauthorized"},{status:401});const column=body.targetType==="timeline"?"timeline_entry_id":body.targetType==="story"?"story_location_id":body.targetType==="destination"?"destination_id":"";if(!column)return Response.json({error:"Invalid media target."},{status:400});const targetTable=column==="timeline_entry_id"?"timeline_entries":column==="story_location_id"?"story_locations":"destinations",target=await value.admin.from(targetTable).select("id").eq("id",body.targetId).eq("wedding_id",body.weddingId).maybeSingle();if(!target.data)return Response.json({error:"Media target not found."},{status:404});const result=await value.admin.from("media_assets").update({[column]:body.targetId,updated_at:new Date().toISOString()}).eq("id",body.mediaId).eq("wedding_id",body.weddingId).select(fields).single();return result.error?Response.json({error:"Media could not be attached."},{status:500}):Response.json({asset:result.data})}
